### PR TITLE
Fix for ValueComparer when handling null values.

### LINKED ISSUE #3217: PostgreSQL Test System.NullReferenceException when select with subquery + multiple left join with View contain null value (worked before 3.4.4-rc.6409)
<details>
<summary>Views</summary>

```SQL
CREATE OR REPLACE VIEW "Member"."V_TableContainValue"
AS SELECT 1 AS "Id",
    'a'::text AS "Val1",
    'b'::text AS "Val2",
    'c'::text AS "Val3";

CREATE OR REPLACE VIEW "Member"."V_TableContainNullValue"
AS SELECT 1 AS "Id",
    'a'::text AS "Val1",
    NULL::text AS "Val2",
    'c'::text AS "Val3";
```

</details>

<details>
<summary>Model</summary>

```C#
[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull] public int      Id   { get; set; } // integer
		[Column,     NotNull] public DateTime Date { get; set; } // date
		[Column,     NotNull] public TimeSpan Time { get; set; } // time without time zone

		#region Associations

		/// <summary>
		/// FK_Table2_Table_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table2> Table2 { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="Table2")]
	public partial class Table2
	{
		[PrimaryKey(1), NotNull    ] public int   Id       { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public int   ParentId { get; set; } // integer
		[Column,           Nullable] public bool? IsTrue   { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Table2_Table
		/// </summary>
		[Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table2_Table", BackReferenceName="Table2")]
		public Table Table { get; set; }

		/// <summary>
		/// FK_Table3_Table2_BackReference
		/// </summary>
		[Association(ThisKey="Id, ParentId", OtherKey="Id, ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table3> Table3 { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="Table3")]
	public partial class Table3
	{
		[Column, NotNull    ] public int   Id       { get; set; } // integer
		[Column, NotNull    ] public int   ParentId { get; set; } // integer
		[Column, NotNull    ] public int   SubId    { get; set; } // integer
		[Column,    Nullable] public bool? IsTrue   { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Table3_Table2
		/// </summary>
		[Association(ThisKey="Id, ParentId", OtherKey="Id, ParentId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table3_Table2", BackReferenceName="Table3")]
		public Table2 Table2 { get; set; }

		#endregion
	}


	[Table(Schema="Member", Name="V_TableContainNullValue", IsView=true)]
	public partial class V_TableContainNullValue
	{
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public int?   Id   { get; set; } // integer
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val1 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val2 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val3 { get; set; } // text
	}

	[Table(Schema="Member", Name="V_TableContainValue", IsView=true)]
	public partial class V_TableContainValue
	{
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public int?   Id   { get; set; } // integer
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val1 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val2 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val3 { get; set; } // text
	}
```
</details>

Sample Condition must contain:
- LEFT JOIN other Table
- LEFT JOIN View that contain null value (V_TableContainNullValue)
- SubQuery with Data

Problem:
```C#
            db.Table3.Delete();
            db.Table2.Delete();
            db.Table.Delete();

            db.Insert(new Table { Id = 1, Date = DateTime.Today, Time = TimeSpan.FromSeconds(0) });
            db.Insert(new Table2 { Id = 1, ParentId = 1 });
            db.Insert(new Table3 { Id = 1, ParentId = 1, SubId = 1 });

            var query = (from x in db.Table2
                         join y1 in db.Table on x.ParentId equals y1.Id into a1
                         from z1 in a1.DefaultIfEmpty()
                         join y2 in db.V_TableContainNullValue on x.ParentId equals y2.Id into a2
                         from z2 in a2.DefaultIfEmpty()
                         select new
                         {
                             TId = z1 != null ? (int?)z1.Id : null,
                             Val1 = z2 != null ? z2.Val1 : null,
                             SubArrays = (from d in x.Table3
                                          select new
                                          {
                                              SubId = d.SubId,
                                          })
                         });
            query.ToArray(); //Error: System.NullReferenceException
```

last tested on linq2db 3.4.2 - 3.4.4-rc.6408 still works

error System.NullReferenceException when linq2db 3.4.4-rc.6409 - 3.4.4-rc.6421

### Environment details
linq2db version: 3.4.4-rc.6421
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #3217

### CODE REVIEW

File: Source/LinqToDB/Common/Internal/ValueComparer`.cs [hunk 1]
```diff
@@ -150,9 +150,9 @@ var expression
 						: Expression.Call(
 							Expression.Convert(param, typeof(object)), ObjectGetHashCodeMethod);
 
-			if (type != unwrappedType)
+			if (type != unwrappedType || type.IsClass || type.IsInterface)
```
Comment (MaceWindu) [inline Source/LinqToDB/Common/Internal/ValueComparer`.cs:153]: maybe `type.IsClass || type.IsInterface` -> `!type.ValueType` ?

**Review by MaceWindu — APPROVED** [review]
