### PR TITLE
Columns removal/orderby visitors refactoring.

### LINKED ISSUE #5103: Missing ORDER BY after DISTINCT.
### Description

It is simplified example of C# code producing the bug:

```C#
IQueryable<Account> accounts = this.GetAccountsUsingOrderBy(...);

var query = from account in accounts
            select new
            {
                Id = account.Id,
                Username = account.Username,
                Email = account.Email,
                Name = account.Name,
                Surname = account.Surname,
                CreationTime = account.CreationTime
            };
            
var some_output = query.Skip(n).Take(s).ToList();
```

It must preserve Order By inside nested query, but that does not happen. It seems some sort of regression.

Generated SQL looks like this:

```SQL
SELECT
	`account_2`.`Id`,
	`account_2`.`Username`,
	`account_2`.`Email`,
	`account_2`.`Name`,
	`account_2`.`Surname`,
	`account_2`.`CreationTime`
FROM
	(
		SELECT DISTINCT
			`account_1`.`Id`,
			`account_1`.`Username`,
			`account_1`.`Password`,
			`account_1`.`Salt`,
			`account_1`.`Email`,
			`account_1`.`Name`,
			`account_1`.`Surname`,
			`account_1`.`LanguageId`,
			`account_1`.`ActivityTime`,
			`account_1`.`CreationTime`
		FROM
			`Account` `account_1`
				INNER JOIN ...
		-- Missing: ORDER BY `account_1`.`Name`, `account_1`.`Surname`
	) `account_2`
LIMIT 0, 10
```

### Reproduction Steps

Look at description... It is reduced sample from real app. Tested on rc2 and rc3.

### Exception details

_No response_

### Regression?

I think version 5 works well.

### Linq To DB version

6-rc3

### .NET version

SDK 9 (TFM net8.0)

### Database

MariaDB

### Database provider

MySQLConnector

### Operating system

Linux

### Configuration

_No response_

### LINKED ISSUE #5327: Order By Missing From SQL when not selecting ordered column
### Description

linq2db doesn't properly order returned data when the ordered column not in the select statement. 

### Reproduction Steps

Using the below code I would expect the returned key list to be ordered by the sum, but it is not. 
```
db
  .Table
  .Select(c => new { c.Key, c.Value})
  .GroupBy(c => c.Key)
  .Select(c => new { c.Key, Sum = c.Sum(d => d.Value)})
  .OrderByDescending(c => c.Sum)
  .Select(c => c.Key)
  .ToList();

db
  .Table
  .Select(c => new { c.Key, c.Value})
  .GroupBy(c => c.Key)
  .OrderByDescending(c => c.Sum(d => d.Value))
  .Select(c => c.Key)
  .ToList();
```

The SQL generated for either query is
```
SELECT
    c_1.key
FROM
    table c_1
GROUP BY
    c_1.key
```

Which is clearly incorrect. 

```
db
  .Table
  .Select(c => new { c.Key, c.Value})
  .GroupBy(c => c.Key)
  .Select(c => new { c.Key, Sum = c.Sum(d => d.Value)})
  .OrderByDescending(c => c.Sum)
  .Select(c => c.Key)
  .Take(2)
  .ToList();

db
  .Table
  .Select(c => new { c.Key, c.Value})
  .GroupBy(c => c.Key)
  .Select(c => new { c.Key, Sum = c.Sum(d => d.Value)})
  .OrderByDescending(c => c.Sum)
  .ToList();
```

Leaving the column in the select statement or using take both apply the order by properly. 

### Exception details

_No response_

### Regression?

_No response_

### Linq To DB version

6.1.0

### .NET version

9

### Database

ClickHouse 25.8.15.35

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by sdanyliv**
- Redesigned unused columns removal visitor.
- Redesigned OrderBy corrector, more aggressive OrderBy preserving.
- `GroupBy` may become `Distinct` if there is no aggregations and right fields in `Select`.

Fix #5103
Fix #5327

### CODE REVIEW

File: Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryColumnOptimizerVisitor.cs [hunk 1]
```diff
@@ -0,0 +1,546 @@
...
+		protected internal override IQueryElement VisitSqlColumnReference(SqlColumn element)
+		{
+			if (_isCollecting)
+			{
+				// Collecting pass: track that this column is being used
+				MarkColumnUsed(element);
+			}
+			
+			// In Phase 2, don't visit column expressions - usage already collected
+			return _isCollecting ? base.VisitSqlColumnReference(element) : element;
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryColumnOptimizerVisitor.cs]:
```suggestion
			if (_isCollecting)
			{
				// Collecting pass: track that this column is being used
				MarkColumnUsed(element);
                return base.VisitSqlColumnReference(element);
			}
			
			// In Phase 2, don't visit column expressions - usage already collected
			return element;
```

File: Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryColumnOptimizerVisitor.cs [hunk 2]
```diff
@@ -0,0 +1,546 @@
...
+							}
+
+							break;
+						}
+					}
+				}
+			}
+			
+			// In Phase 2, don't visit field references - usage already collected
+			return _isCollecting ? base.VisitSqlFieldReference(element) : element;
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryColumnOptimizerVisitor.cs]:
```suggestion
				}

                return base.VisitSqlFieldReference(element);
			}
			
			// In Phase 2, don't visit field references - usage already collected
			return element;
```

File: Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryOrderByOptimizer.cs [hunk 3]
```diff
@@ -1,297 +1,258 @@
...
-		bool             _needsNestingUpdate;
+		SqlProviderFlags               _providerFlags          = default!;
+		SqlQueryColumnNestingCorrector _columnNestingCorrector = default!;
 
-		public bool IsOptimized => _optimized;
-		public bool NeedsNestingUpdate => _needsNestingUpdate;
+		bool _optimized;
 
-		public SqlQueryOrderByOptimizer() : base(VisitMode.Modify, null)
+		public bool IsOptimized        => _optimized;
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/SqlQuery/Visitors/SqlQueryOrderByOptimizer.cs]: why not 
```suggestion
		public bool IsOptimized { get; private set; }
```

**Comment by MaceWindu** [comment]
Baselines comments (see remaining baselines in PR):
- JoinToLimitedTests.* tests, e.g. `InnerJoinLimited2` add top level sort for databases without APPLY (?) support (e.g. CH, FB3, SQLITE)
- `Issue4167` optimization deoptimize `group by` to `distinct` with subquery introduced
- `OrderByDistinctAll1/2` tests could produce more optimal sql by removing some unused non-key columns from distinct with key
- `OrderByInUnion` not clear if sortng introduced to sql intentionally. If we wan't to support enumerable sort order, we need to use AssertQuery in test

File: Build/Azure/pipelines/templates/build-vars.yml [hunk 4]
```diff
@@ -2,7 +2,7 @@ variables:
 # also check hardcoded branch names in pipeline triggers and nuget-vars.yml
   master_branch: master
   release_branch: release
-  baselines_master: master
+  baselines_master: baselines/pr_5307_reviewed
```
Comment (MaceWindu) [inline Build/Azure/pipelines/templates/build-vars.yml]:
```suggestion
  baselines_master: master
```
