### PR TITLE
Сhanged the behavior of CommandTimeout properties

### LINKED ISSUE #1668: Timeout issue
Hello

I have the method         

public virtual int Delete(T item) => m_db.Delete(item); 

And call it in controller

arcReportRepository.Delete(guid);

And after that I have the error:
Время ожидания выполнения истекло. Время ожидания истекло до завершения операции, или сервер не отвечает.
The statement has been terminated.
StackTrace:
   в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   в System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   в System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   в System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   в System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   в System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   в System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   в LinqToDB.Data.DataConnection.ExecuteNonQuery() в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:строка 1040
   в LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, PreparedQuery preparedQuery) в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:строка 287
   в LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery() в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:строка 325
   в LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:строка 759
   в LinqToDB.Linq.QueryRunner.<>c__DisplayClass28_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:строка 752
   в LinqToDB.Linq.QueryRunner.Delete`1.Query(IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.Delete.cs:строка 66
   в LinqToDB.DataExtensions.Delete[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName) в C:\projects\linq2db\Source\LinqToDB\DataExtensions.cs:строка 462
   в Vero.Navicon.ProcessCube.Data.Repositories.Repository`3.Delete(P id) в E:\Projects\Git Vero.Navicon.ProcessCube\Vero.Navicon.ProcessCube.Data\Repositories\Repository.cs:строка 36
   в Vero.Navicon.ProcessCube.Web.Controllers.SalesoutReportController.DeleteArcFactsByReport(Guid guid) в E:\Projects\Git Vero.Navicon.ProcessCube\Vero.Navicon.ProcessCube.Web\Controllers\SalesoutReportController.cs:строка 64

How I can change timeout for command?
By default CommandTimeout for my DataConnection (m_db) is 0 (infinity), but it doesn't work.

### PR DESCRIPTION
**Pull request by GonzoSpire**
fix #1668

### CODE REVIEW

File: Source/LinqToDB/Data/DataConnection.cs [hunk 1]
```diff
@@ -1064,17 +1064,29 @@ internal void InitCommand(CommandType commandType, string sql, DataParameter[] p
...
+			get => _commandTimeout ?? -1;
 			set
 			{
-				_commandTimeout = value;
-				if (_command != null)
-					_command.CommandTimeout = value;
+				if (value < 0)
+				{
+					_commandTimeout = null;
+					if (_command != null)
```
Comment (MaceWindu) [inline Source/LinqToDB/Data/DataConnection.cs]: command disposal is not so simple. You need to call DisposeCommand() method
