### PR TITLE
Fix char constants support in compare operations with char? operands in expressions

### LINKED ISSUE #1287: about  char?
my database sql server 2008

image

my code 

````
[Column("card_status"), Nullable] 
public char? CardStatus { get; set; }  // char(1)

var vipInfo = await _conn.TRmVipInfo.SingleOrDefaultAsync(m => m.Mobile == mobile && m.CardStatus=='0');
````

translate

````
--数据可能会被截断并且可能无法表示服务器上运行的查询。
USE [EWYMT];

GO

--类型和值数据不适用于下列变量。它们的值已设为默认值。
DECLARE @mobile1 AS SQL_VARIANT;
SET @mobile1 = NULL;

SELECT
	[t1].[card_id],
	[t1].[card_no],
	[t1].[card_type],
	[t1].[vip_name],
	[t1].[vip_sex],
	[t1].[vip_tel],
	[t1].[mobile],
	[t1].[vip_email],
	[t1].[social_id],
	[t1].[bth_flag],
	[t1].[birthday],
	[t1].[vip_add],
	[t1].[vip_zip],
	[t1].[vip_tax],
	[t1].[vip_start_date],
	[t1].[vip_end_date],
	[t1].[sav_start_date],
	[t1].[sav_end_date],
	[t1].[use_num],
	[t1].[save_amt],
	[t1].[residual_amt],
	[t1].[consum_amt],
	[t1].[consum_count],
	[t1].[card_status],
	[t1].[now_acc_num],
	[t1].[acc_num],
	[t1].[dec_num],
	[t1].[branch_no],
	[t1].[oper_date],
	[t1].[pass],
	[t1].[father_card],
	[t1].[item_amt],
	[t1].[source_card_id],
	[t1].[marriage],
	[t1].[homeplace],
	[t1].[reg_place],
	[t1].[live_place],
	[t1].[company],
	[t1].[duty],
	[t1].[degree],
	[t1].[salary_level],
	[t1].[nation],
	[t1].[height],
	[t1].[weight],
	[t1].[blood_type],
	[t1].[favor],
	[t1].[vip_credentials],
	[t1].[vip_work],
	[t1].[vip_intent],
	[t1].[photo],
	[t1].[picture_type],
	[t1].[vip_add1],
	[t1].[memo],
	[t1].[vip_add2],
	[t1].[annex_property1],
	[t1].[annex_property2],
	[t1].[annex_property3],
	[t1].[annex_property4],
	[t1].[annex_property5],
	[t1].[annex_property6],
	[t1].[annex_property7],
	[t1].[annex_property8],
	[t1].[annex_property9],
	[t1].[annex_property10],
	[t1].[vip_spec_date1],
	[t1].[vip_spec_date2],
	[t1].[vip_spec_date3],
	[t1].[oper_id],
	[t1].[modify_date],
	[t1].[com_flag],
	[t1].[modify_oper],
	[t1].[change_amt],
	[t1].[hz_pfwt],
	[t1].[hz_date],
	[t1].[hz_memo],
	[t1].[hz_zz],
	[t1].[hz_qgyy],
	[t1].[hz_pffn],
	[t1].[hz_gzsx],
	[t1].[vip_zjm],
	[t1].[openid],
	[t1].[saleman_id],
	[t1].[sale_id],
	[t1].[vip_creditamt],
	[t1].[referrer_id],
	[t1].[GWQAmt],
	[t1].[isKZ],
	[t1].[vip_date]
FROM
	[dbo].[t_rm_vip_info] [t1]
WHERE
	[t1].[mobile] = @mobile1 AND [t1].[card_status] = 48
````

why it translate '0' to 48

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #1287

Actually it is overoptimization from compiler that we reverted for char but missed same logic for char?

### CODE REVIEW

File: Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs [hunk 1]
```diff
@@ -1525,6 +1525,19 @@ ISqlPredicate ConvertCompare(IBuildContext context, ExpressionType nodeType, Exp
 				}
 			}
 
+			if (left.NodeType == ExpressionType.Convert && left.Type == typeof(int?) && (right.NodeType == ExpressionType.Constant || (right.NodeType == ExpressionType.Convert && ((UnaryExpression)right).Operand.NodeType == ExpressionType.Convert)))
```
Comment (sdanyliv) [inline Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs]: Better to reformat this line. It’s hard to read.

File: Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs [hunk 2]
```diff
@@ -1538,6 +1551,19 @@ ISqlPredicate ConvertCompare(IBuildContext context, ExpressionType nodeType, Exp
 				}
 			}
 
+			if (right.NodeType == ExpressionType.Convert && right.Type == typeof(int?) && (left.NodeType == ExpressionType.Constant || (left.NodeType == ExpressionType.Convert && ((UnaryExpression)left).Operand.NodeType == ExpressionType.Convert)))
```
Comment (sdanyliv) [inline Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs]: Better to reformat this line. It’s hard to read.
