### PR TITLE
Complete Temporary Table support functionality

### LINKED ISSUE #1609: How to create a temporary table in postgresql?
### Steps to reproduce
This code:
```c#
var tempTable = db.CreateTempTable<User>("ttt1");
```
generate sql:
```
CREATE TABLE ttt1
(
        id   uuid         NOT NULL,
        name VarChar(128) NOT NULL,

        CONSTRAINT "PK_ttt1" PRIMARY KEY (id)
)
```
Correct SQL:
```
CREATE TEMP TABLE ttt1
(
        ...
)
```

I'm using this helpers:
```c#
public static async Task<ITable<T>> CreateTempTableAsync<T>(this LinqToDB.Data.DataConnection db)
{
    var tempTable = await db.CreateTableAsync<T>(
            tableName: "t_" + Guid.NewGuid().ToString().Replace("-", ""),
            statementHeader: "CREATE TEMP TABLE {0} ",
            defaultNullable: DefaultNullable.NotNull);
    return tempTable;
}

public static async Task<ITable<T>> CreateTempTableAsync<T>(this LinqToDB.Data.DataConnection db, IQueryable<T> query)
{
    var tempTable = await db.CreateTempTableAsync<T>();
    await query.InsertAsync(tempTable, t => t);
    return tempTable;
}
```
This code:
```c#
var query = (from user in db.Users 
            select new 
            {
                Id = user.Id,
                Name = user.Name
            }).Take(5);
var tempTable = await db.CreateTempTableAsync(query);
```
Generate SQL:
```
CREATE TEMP TABLE t_fc2f617d3c2a48c5a02fe12d6d89bfae
(
        "Id"   uuid,
        "Name" VarChar     NULL
)
```
```
INSERT INTO t_fc2f617d3c2a48c5a02fe12d6d89bfae
(
        "Id",
        "Name"
)
SELECT
        user_1.id,
        user_1.name
FROM
        users user_1
LIMIT 5
```

How to use temporary tables correctly? How to generate this SQL(to reduce the number of calls)?:
```
CREATE TEMP TABLE t_fc2f617d3c2a48c5a02fe12d6d89bfae AS 
SELECT
	id, 
	name 
FROM
	users
LIMIT 5
```

### Environment details
linq2db version: *2.6.4*
Database Server: *PostgreSQL 10*
Database Provider: *Npgsql 4.0.4*

### LINKED ISSUE #2368: Task: Complete Temporary Table support functionality
Current issues:

- There is no functions for creating temporary tables from IQueryable
- There is no support of temporary tables in SqlBuilder. I suggest to extend `SqlCreateTableStatement` to have `IsTemporrary` property and correct SQL Builders for every providers
- Extend TempTable API to define indexes.
```cs
var query = from t in some
   select new { t.Id1, t.Id2 };

using var temp = db.CreateTempTable(query,
   entity
       .HasIndex(e => e.Id2)
       .HasIndex(e => new {e.Id1, e.Id2)
);
```

### PR DESCRIPTION
**Pull request by igor-tkachev**
Fixes #2368, fixes #1609

### CODE REVIEW

File: Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs [hunk 1]
```diff
@@ -396,5 +397,69 @@ protected override void BuildInsertQuery(SqlStatement statement, SqlInsertClause
 				base.BuildInsertQuery(statement, insertClause, addAlias);
 			}
 		}
+
+		protected override void BuildCreateTableCommand(SqlTable table)
+		{
+			StringBuilder.Append(
+				table.TableOptions.HasIsGlobalTemporary() ?
+					"CREATE GLOBAL TEMPORARY TABLE " :
+//				(table.TableOptions.HasIsTemporary) != 0 ?
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs:406]: Leaving comments here intentional?

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs [hunk 2]
```diff
@@ -522,5 +523,65 @@ public override StringBuilder BuildTableName(StringBuilder sb, string? server, s
...
 		}
+
+		protected override void BuildCreateTableCommand(SqlTable table)
+		{
+			StringBuilder.Append(
+				table.TableOptions.HasIsTemporary() ?
+					"CREATE GLOBAL TEMPORARY TABLE " :
+					"CREATE TABLE ");
+//
+//			if ((table.TableOptions.HasCreateIfNotExists) != 0)
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs:534]: Leaving comments is intentional?

File: Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs [hunk 3]
```diff
@@ -352,28 +379,23 @@ protected override void BuildDropTableStatement(SqlDropTableStatement dropTable)
...
 			{
-				AppendIndent().Append("DROP TABLE ");
-				BuildPhysicalTable(table, null);
-				StringBuilder.AppendLine();
+				var defaultDatabaseName =
+					table.PhysicalName!.StartsWith("#") || (table.TableOptions & (TableOptions.IsTemporary | TableOptions.IsGlobalTemporary)) != 0 ?
+						"[tempdb]" : null;
+
+				StringBuilder.Append("IF (OBJECT_ID(N'");
+				BuildPhysicalTable(table, null, defaultDatabaseName : defaultDatabaseName);
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs:389]: If providing parameter names, should provide parameter name for `null`, since that is most likely to be opaque in later reading. `defaultDatabaseName` is self-explanatory here.

File: Source/LinqToDB/TempTable.cs [hunk 4]
```diff
@@ -954,25 +1008,283 @@ public static partial class DataExtensions
...
+		/// <param name="items">Initial records to insert into created table.</param>
+		/// <param name="options">Optional BulkCopy options.</param>
+		/// <param name="tableName">Optional name of temporary table. If not specified, value from mapping will be used.</param>
+		/// <param name="databaseName">Optional name of table's database. If not specified, value from mapping will be used.</param>
+		/// <param name="schemaName">Optional name of table schema/owner. If not specified, value from mapping will be used.</param>
+		/// <param name="serverName">Optional name of linked server. If not specified, value from mapping will be used.</param>
+		/// <param name="tableOptions">Optional Table options. Default is <see cref="TableOptions.IsTemporary"/>.</param>
+		/// <param name="cancellationToken">Asynchronous operation cancellation token.</param>
+		/// <returns>Returns temporary table instance.</returns>
+		public static Task<TempTable<T>> ToTempTableAsync<T>(
```
Comment (viceroypenguin) [inline Source/LinqToDB/TempTable.cs:1172]: Function above is named `IntoTempTable()`. Should update that to `ToTempTable()` or this to `IntoTempTableAsync()` for matching.

File: Source/LinqToDB/TempTable.cs [hunk 5]
```diff
@@ -954,25 +1008,283 @@ public static partial class DataExtensions
...
+		/// <param name="items">Initial records to insert into created table.</param>
+		/// <param name="options">Optional BulkCopy options.</param>
+		/// <param name="tableName">Optional name of temporary table. If not specified, value from mapping will be used.</param>
+		/// <param name="databaseName">Optional name of table's database. If not specified, value from mapping will be used.</param>
+		/// <param name="schemaName">Optional name of table schema/owner. If not specified, value from mapping will be used.</param>
+		/// <param name="serverName">Optional name of linked server. If not specified, value from mapping will be used.</param>
+		/// <param name="tableOptions">Optional Table options. If not specified, value from mapping will be used.</param>
+		/// <param name="cancellationToken">Asynchronous operation cancellation token.</param>
+		/// <returns>Returns temporary table instance.</returns>
+		public static Task<TempTable<T>> ToTableAsync<T>(
```
Comment (viceroypenguin) [inline Source/LinqToDB/TempTable.cs:1201]: Similar naming issue

**Comment by viceroypenguin** [comment]
Fixes #1201 by way of `TableOptions.CreateIfNotExists`

File: Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs (hunk 3 above)
Comment (igor-tkachev) [reply Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs:389]: This is OBJECT_ID specific behavior.

File: Source/LinqToDB/TempTable.cs (hunk 4 above)
Comment (igor-tkachev) [reply Source/LinqToDB/TempTable.cs:1172]: Yep.

File: Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs (hunk 1 above)
Comment (igor-tkachev) [reply Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs:406]: Not need anymore.

File: Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs (hunk 3 above)
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs:389]:
```suggestion
				BuildPhysicalTable(table, alias: null, defaultDatabaseName: defaultDatabaseName);
```

File: Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs [hunk 6]
```diff
@@ -352,28 +379,23 @@ protected override void BuildDropTableStatement(SqlDropTableStatement dropTable)
...
-					StringBuilder.Append("IF (OBJECT_ID(N'");
-					BuildPhysicalTable(table, null);
-					StringBuilder.AppendLine("', N'U') IS NOT NULL)");
-					Indent++;
-				}
 
-				AppendIndent().Append("DROP TABLE ");
-				BuildPhysicalTable(table, null);
+			AppendIndent().Append("DROP TABLE ");
+			BuildPhysicalTable(table, null);
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs:395]:
```suggestion
			BuildPhysicalTable(table, alias: null);
```

**Review by viceroypenguin — APPROVED** [review]

File: Source/LinqToDB/TempTable.cs [hunk 7]
```diff
@@ -954,25 +1008,283 @@ public static partial class DataExtensions
...
+		/// <param name="items">Query to get records to populate created table with initial data.</param>
+		/// <param name="tableName">Optional name of temporary table. If not specified, value from mapping will be used.</param>
+		/// <param name="databaseName">Optional name of table's database. If not specified, value from mapping will be used.</param>
+		/// <param name="schemaName">Optional name of table schema/owner. If not specified, value from mapping will be used.</param>
+		/// <param name="action">Optional action that will be executed after table creation, but before it populated with data from <paramref name="items"/>.</param>
+		/// <param name="serverName">Optional name of linked server. If not specified, value from mapping will be used.</param>
+		/// <param name="tableOptions">Optional Table options. Default is <see cref="TableOptions.IsTemporary"/>.</param>
+		/// <param name="setTable">Action to modify <typeparamref name="T"/> entity's mapping using fluent mapping.</param>
+		/// <returns>Returns temporary table instance.</returns>
+		public static TempTable<T> IntoTempTable<T>(
```
Comment (ili) [inline Source/LinqToDB/TempTable.cs:1105]: Two same methods with different names are confusing. User would expect `IntoTable` would create persistent table and `IntoTempTabe` would create temporary one, at least because there are *two* methods. Nobody reads docs :)

**Comment by MaceWindu** [comment]
linking #1609 to this pr

**Review by MaceWindu — CHANGES_REQUESTED** [review]
Missing support:
- access temporary tables: https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/create-table-statement-microsoft-access-sql
- sap hana global and local temp tables: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20d58a5f75191014b2fe92141b7df228.html

**Comment by MaceWindu** [comment]
release notes draft https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables

File: Source/LinqToDB/TableOptions.cs [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+	{
+		NotSet            = 0b00000,
+		None              = 0b00001,
+		/// <summary>
+		/// Table is temporary. This option will have effect only for databases that support temporary tables.
+		/// <para>Supported by: DB2, Informix, MySql, Oracle, PostgreSQL, SQLite, SQL Server, Sybase ASE.</para>
+		/// </summary>
+		IsTemporary       = 0b00010,
+		/// <summary>
+		/// Table is global temporary. This option will have effect only for databases that support temporary tables.
```
Comment (MaceWindu) [inline Source/LinqToDB/TableOptions.cs:20]: makes sense to specify difference between global temp and temp tables

**Comment by viceroypenguin** [comment]
> release notes draft https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables

@MaceWindu FYI for release notes: also fixes #1201 by way of new options on TableCreation.

File: Source/LinqToDB/Data/BulkCopyOptions.cs [hunk 9]
```diff
@@ -69,6 +70,11 @@ public BulkCopyOptions(BulkCopyOptions options)
 		/// Gets or sets explicit name of target table instead of one, configured for copied entity in mapping schema.
 		/// </summary>
 		public string?      TableName              { get; set; }
+		/// <summary>
+		/// Gets or sets explicit IsTemporary flag instead of one, configured for copied entity in mapping schema.
```
[the remark this answers is not in the document]
Comment (igor-tkachev) [reply Source/LinqToDB/Data/BulkCopyOptions.cs:74]: Yes, and we can add more.

File: Source/LinqToDB/TempTable.cs (hunk 7 above)
Comment (igor-tkachev) [reply Source/LinqToDB/TempTable.cs:1105]: Either I already fixed it or I didn't get it :( What two the same methods have different names?

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs [hunk 10]
```diff
@@ -522,5 +523,62 @@ public override StringBuilder BuildTableName(StringBuilder sb, string? server, s
 
 			return base.GetProviderTypeName(parameter);
 		}
+
+		protected override void BuildCreateTableCommand(SqlTable table)
+		{
+			StringBuilder.Append(
+				table.TableOptions.HasIsTemporary() ?
+					"CREATE GLOBAL TEMPORARY TABLE " :
```
[the remark this answers is not in the document]
Comment (igor-tkachev) [reply Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs:531]: Changed for Firebird.

[the remark this answers is not in the document]
Comment (MaceWindu) [reply Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs:531]: I think we should change oracle to use IsGlobalTemporary instead as it is visible to other sessions, data is not visible. It will match other databases behavior then:
- DB2:
 - CREATE GLOBAL: table visible to other sessions, data not shared (global)
 - DECLARE GLOBAL: table not visible from other sessions (local)
- FB: table visible to other sessions, data not shared (global)
- SQLITE, MYSQL/MARIADB, PGSQL, INFORMIX: table not visible from other sessions (local)
- SAP HANA:
 - GLOBAL: table visible to other sessions, data not shared (global)
 - LOCAL: table not visible from other sessions (local)
- SQL SERVER/SYBASE ASE:
 - ## table visible to other sessions (global)
 - #: table not visible from other sessions (local)

Also available here https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#temporary-tables as table

**Comment by MaceWindu** [comment]
I think we should have more tests for new functionality. SAP HANA tests passed but I don't see temp tables used there

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (igor-tkachev) [reply Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs:531]: We have 3 temp table implementations by different providers:

- session shared structure / session shared data (SqlServer ##)
- session shared structure / session private data (FB)
- session private structure / session private data (SqlServer #)

So, we can explicitly implement those flags and do not care about compatibility/provider support. Users will handle it somehow. Also we can implement some other temp table flags.

Another way is what I tried to implement - to simulate local/global session temp tables.

Probably, the first approach is better. Should I follow it?

[the remark this answers is not in the document]
Comment (MaceWindu) [reply Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs:531]: + for first approach, but I don't see value in adding 3rd option. Current separation into two types if looks fine to me: Global == shared structure (with any data isolation level), NonGlobal == session structure. There is no database that have two types of global tables.

**Comment by igor-tkachev** [comment]
In order to add a full support for temp tables, we need the following table options:

- IsGlobalTemporaryScope (IsGlobalTemporaryStructure)
- IsLocalTemporaryScope (IsLocalTemporaryStructure)
- IsGlobalTemporaryData
- IsLocalTemporaryData
- IsTransactionTemporaryData

Those options will be applied to

Database | Statement | Scope | Data | Options
-- | -- | -- | -- | --
DB2 | CREATE GLOBAL TEMPORARY TABLE | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
DB2 | DECLARE GLOBAL TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Firebird | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT DELETE ROWS (default) | Global | Transaction | IsGlobalTemporaryScope + IsTransactionTemporaryData
Firebird | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Global | Connection | IsGlobalTemporaryScope + IsLocalTemporaryData
Informix | CREATE TEMP TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
MySql | CREATE TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Oracle | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT DELETE ROWS   (default) | Global | Transaction | IsGlobalTemporaryScope + IsTransactionTemporaryData
Oracle | CREATE GLOBAL TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
Oracle | CREATE PRIVATE TEMPORARY TABLE (18c) | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT DELETE ROWS | Session | Transaction | IsLocalTemporaryScope + IsTransactionTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT PRESERVE ROWS | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
PostgreSQL | CREATE TEMPORARY TABLE … ON COMMIT DROP | Transaction | Transaction | NOT SUPPORTED ???
SAP Hana | CREATE GLOBAL TEMPORARY TABLE | Global | Session | IsGlobalTemporaryScope + IsLocalTemporaryData
SAP Hana | CREATE LOCAL TEMPORARY TABLE | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | CREATE TABLE #TableName | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | CREATE TABLE ##TableName | Last Session | Global | IsGlobalTemporaryScope + IsGlobalTemporaryData
SqlServer | DECLARE @TableName TABLE | Batch | Batch | NOT SUPPORTED
Sybase | CREATE TABLE #TableName | Session | Session | IsLocalTemporaryScope + IsLocalTemporaryData
Sybase | CREATE TABLE ##TableName | Last Session | Global | IsGlobalTemporaryScope + IsGlobalTemporaryData

Also I am going to add the IsTemporary option to implement Local/Local temp table

Database | IsTemporary
-- | --
DB2 | IsLocalTemporaryScope + IsLocalTemporaryData
Firebird | IsGlobalTemporaryScope + IsLocalTemporaryData + CreateIfNotExists +   DropIfExists
Informix | IsLocalTemporaryScope + IsLocalTemporaryData
MySql | IsLocalTemporaryScope + IsLocalTemporaryData
Oracle | IsGlobalTemporaryScope + IsLocalTemporaryData + CreateIfNotExists +   DropIfExists
PostgreSQL | IsLocalTemporaryScope + IsLocalTemporaryData
SAP Hana | IsLocalTemporaryScope + IsLocalTemporaryData
SqlServer | IsLocalTemporaryScope + IsLocalTemporaryData
Sybase | IsLocalTemporaryScope + IsLocalTemporaryData

File: Source/LinqToDB/TempTable.cs (hunk 7 above)
Comment (ili) [reply Source/LinqToDB/TempTable.cs:1172]: @igor-tkachev sorry, missed your comment:

- IntoTempTable https://github.com/linq2db/linq2db/pull/2391/files#diff-b9674cc2be27bba1242f41616b7b34c598e717fd273d8e26c2290313dba5a9e8R1118
- IntoTable https://github.com/linq2db/linq2db/pull/2391/files#diff-b9674cc2be27bba1242f41616b7b34c598e717fd273d8e26c2290313dba5a9e8R1145

There are few methods in `TempTable.cs` with name `IntoTable` returning `TempTable<T>` - this is confusing

Comment (igor-tkachev) [reply Source/LinqToDB/TempTable.cs:1172]: The difference is IntoTempTable automatically adds TableOptions.IsTemporary option.

**Review by sdanyliv — COMMENTED** [review]
There are missing tests for
IntoTempTable(IEnumerable)  
IntoTempTableAsync() - 2 overloads

Missed tests in especially in SelectMany variant
IsTemporary(with boo IsTemporary)
TableOptions()

At least one test for `Insert`, `Update`, `Detete`, `Merge` but with TableOptions and temporary tables.

File: Source/LinqToDB/DataProvider/IDataProvider.cs [hunk 11]
```diff
@@ -20,6 +20,7 @@ public interface IDataProvider
 		Type               DataReaderType        { get; }
 		MappingSchema      MappingSchema         { get; }
 		SqlProviderFlags   SqlProviderFlags      { get; }
+		TableOptions       SupportedTableOptions { get; }
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/IDataProvider.cs:23]: Do we use it or this property is for informational purposes only?

File: Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs [hunk 12]
```diff
@@ -51,6 +51,14 @@ static DateTime GetDateTime(IDataReader dr, int idx)
 			return value;
 		}
 
+		public override TableOptions SupportedTableOptions =>
+			TableOptions.IsTemporary                |
+			TableOptions.IsLocalTemporaryStructure  |
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs:56]:
```suggestion
```

File: Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs [hunk 13]
```diff
@@ -74,6 +74,14 @@ public override ISchemaProvider GetSchemaProvider()
 				new DB2LUWSchemaProvider(this);
 		}
 
+		public override TableOptions SupportedTableOptions =>
+			TableOptions.IsTemporary                |
+			TableOptions.IsGlobalTemporaryStructure |
+			TableOptions.IsLocalTemporaryData       |
+			TableOptions.IsTransactionTemporaryData |
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs:81]:
```suggestion
```

File: Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs [hunk 14]
```diff
@@ -51,6 +51,14 @@ static DateTime GetDateTime(IDataReader dr, int idx)
...
+			TableOptions.IsGlobalTemporaryStructure |
+			TableOptions.IsLocalTemporaryData       |
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs:58]:
```suggestion
			TableOptions.IsLocalTemporaryData       |
			TableOptions.IsTransactionTemporaryData |
```

**Review by MaceWindu — CHANGES_REQUESTED** [review]

File: Source/LinqToDB/TableOptions.cs [hunk 15]
```diff
@@ -0,0 +1,109 @@
...
+		/// <para>Supported by: DB2, Firebird, Informix, MySql, Oracle, PostgreSQL, SQLite, SQL Server, Sybase ASE.</para>
+		/// </summary>
+		DropIfExists               = 0b000000100,
+		/// <summary>
+		/// Table is temporary (not visible to other sessions). This option will have effect only for databases that support temporary tables.
+		/// <para>Supported by: DB2, Firebird, Informix, MySql, Oracle, PostgreSQL, SQLite, SQL Server, SAP Hana, Sybase ASE.</para>
+		/// </summary>
+		IsTemporary                = 0b000001000,
+		/// <summary>
+		/// Table is temporary (table structure is not visible to other sessions). This option will have effect only for databases that support temporary tables.
```
[the remark this answers is not in the document]
Comment (igor-tkachev) [reply Source/LinqToDB/TableOptions.cs:32]: yes

File: Source/LinqToDB/DataProvider/IDataProvider.cs (hunk 11 above)
Comment (igor-tkachev) [reply Source/LinqToDB/DataProvider/IDataProvider.cs:23]: For information. I use it in tests.

**Review by MaceWindu — APPROVED** [review]
