### PR TITLE
Fix for #2642. Added missing null reference check.

### LINKED ISSUE #2642: System.Reflection.TargetInvocationException in LoadWith
When using join and LoadWith in the same query, TargetInvocationException is thrown. If I remove LoadWith or join, query works ok.

```
Stack trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at LinqToDB.Linq.Builder.EagerLoading.GenerateDetailsExpression(IBuildContext context, MappingSchema mappingSchema, Expression expression) in D:\a\1\s\Source\LinqToDB\Linq\Builder\EagerLoading.cs:line 1308
   at LinqToDB.Linq.Builder.EagerLoading.GenerateAssociationExpression(ExpressionBuilder builder, IBuildContext context, Expression expression, AssociationDescriptor association) in D:\a\1\s\Source\LinqToDB\Linq\Builder\EagerLoading.cs:line 711
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 733
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.SetLoadWithBindings(Type objectType, ParameterExpression parentObject, List`1 exprs) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 211
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Tuple`2[] index) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 412
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Tuple`2[] index) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 279
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 626
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 725
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 717
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\PassThroughContext.cs:line 39
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\PassThroughContext.cs:line 39
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 173
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 252
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1371
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 239
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass40_0.<BuildExpression>b__0(IBuildContext ctx, Expression ex, Int32 l) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 162
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction, Boolean throwOnError) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 1060
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 159
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 183
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1371
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 132
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 89
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 173
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 532
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in D:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 494
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in D:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 75
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in D:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 314
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Doit7() in D:\BCS\APPs\BozhenovAY\ConsoleApp1\Program.cs:line 322
```

### Steps to reproduce
```c#
        [Table("mails")]
        class Email
        {
            [Column]
            public int Id { get; set; }
            [Column]
            public DateTime AddTime{ get; set; }
            [Association(ThisKey = "Id", OtherKey = "EmailId")]
            public IEnumerable<EmailAttachment> Attachments { get; set; }
        }
        [Table("EmailAttachments")]
        class EmailAttachment
        {
            [Column]
            public int Id { get; set; }
            [Column]
            public int EmailId { get; set; }
            [Column]
            public string Data { get; set; }
        }
        [Table("IIRs")]
        class Iir
        {
            [Column]
            public  int Id { get; set; }
        }
        private static void Doit7()
        {
            DataConnection.AddOrSetConfiguration("SMSDb", "Server=.;Database=SmsDb;Trusted_Connection=True;Enlist=False;", "SqlServer");
            LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
            using (var db = new DataConnection("SMSDb"))
            {
                try
                {
                    var data = (from p in db.GetTable<Email>().LoadWith(c => c.Attachments)
                                join i in db.GetTable<Iir>() on p.Id equals i.Id
                                where p.AddTime > DateTime.Now
                                orderby p.AddTime
                                select p).ToArray();
                }
                catch (Exception ex)
                { }
            }
        }

```

### Environment details
linq2db version: 3.1.6 (also crashes on 3.0.1)
Database Server: Ms Sql Server
Database Provider: SqlServer
Operating system: Windows 10
.NET Framework: 4.8

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #2642

### CODE REVIEW

File: Tests/Linq/UserTests/Issue2642Tests.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+		class Iir
+		{
+			[Column]
+			public int Id { get; set; }
+		}
+
+		[Test]
+		public void SampleSelectTest([IncludeDataSources(TestProvName.AllSQLite)] string context)
+		{
+			using (new AllowMultipleQuery())
```
Comment (viceroypenguin) [inline Tests/Linq/UserTests/Issue2642Tests.cs:45]: Don't forget to remove this when merging w/ #2656

**Review by viceroypenguin — APPROVED** [review]

File: Tests/Linq/UserTests/Issue2642Tests.cs (hunk 1 above)
Comment (MaceWindu) [inline Tests/Linq/UserTests/Issue2642Tests.cs:45]:
```suggestion
```

**Review by MaceWindu — APPROVED** [review]
