### PR TITLE
Fix `~` operator translation

### LINKED ISSUE #5286: Translation error for binary enum operations with PostgreSQL
### Description

The translation for `~enumValue` is incorrect. When I do a query for updating flags in a database such as:
```
var addMask = Enum.SomeValue | Enum.SecondValue;
var removeMask = Enum.SomeOtherValue | Enum.FourthValue;

await connection
            .GetTable<WarehouseTableDto>()
            .Where(w => w.ClearingWarehouseId == clearingWarehouseId.ToInt64())
            .Set(w => w.Attributes, w => (w.Attributes | addMask) & ~removeMask)
            .UpdateAsync(cancellationToken);
```
This query is getting translated into:
```
UPDATE
		warehouses
	SET
		attribute_flags = warehouses.attribute_flags | $1 & (1 = 0)
	WHERE
		warehouses.clearing_warehouse_id = $2
```
While it is expected it to be:
```
UPDATE
		warehouses
	SET
		attribute_flags = warehouses.attribute_flags | $1 & (~$2)
	WHERE
		warehouses.clearing_warehouse_id = $3
```

There exists a workaround to flip the bits before sending to the query (which I'm using in the meantime):
```
var addMask = Enum.SomeValue | Enum.SecondValue;
var removeMask = ~(Enum.SomeOtherValue | Enum.FourthValue);

await connection
            .GetTable<WarehouseTableDto>()
            .Where(w => w.ClearingWarehouseId == clearingWarehouseId.ToInt64())
            .Set(w => w.Attributes, w => (w.Attributes | addMask) & removeMask)
            .UpdateAsync(cancellationToken);
```
Which is correctly translated as:
```
UPDATE
		warehouses
	SET
		attribute_flags = warehouses.attribute_flags | $1 & $2
	WHERE
		warehouses.clearing_warehouse_id = $3
```

But it would be nice if it got fixed

### Reproduction Steps

```
var addMask = Enum.SomeValue | Enum.SecondValue;
var removeMask = Enum.SomeOtherValue | Enum.FourthValue;

await connection
            .GetTable<WarehouseTableDto>()
            .Where(w => w.ClearingWarehouseId == clearingWarehouseId.ToInt64())
            .Set(w => w.Attributes, w => (w.Attributes | addMask) & ~removeMask)
            .UpdateAsync(cancellationToken);
```

### Exception details

ERROR:  operator does not exist: bigint & boolean at character 75
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

### Regression?

Yes, worked well on 5.4.1

### Linq To DB version

6.1.0

### .NET version

10.0.100

### Database

PostgreSQL 13

### Database provider

Npgsql 10

### Operating system

macOS

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #5286

- implement bitwise NOT operator for all providers
- improve type inference for parameters with unmapped type with underlying base type
- fix bitwise OR precedence for MySQL and Acces
- fix Access bitwise operators rewrite location and use proper naming for operators

### CODE REVIEW

**Review by sdanyliv — DISMISSED** [review]

File: Source/LinqToDB/Internal/DataProvider/Ydb/YdbSqlExpressionConvertVisitor.cs [hunk 1]
```diff
@@ -124,58 +139,61 @@ public override ISqlExpression ConvertSqlFunction(SqlFunction func)
...
-				//				func.Parameters[0],    // substring
-				//				func.Parameters[1],    // source
-				//				func.Parameters[2]);   // start
-				//	}
-
-				//	break;
+				case PseudoFunctions.REPLACE:
+					return func.WithName("Unicode::ReplaceAll");
+
+					////----------------------------------------------------------------
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/DataProvider/Ydb/YdbSqlExpressionConvertVisitor.cs:145]: why keep commented code?

**Review by viceroypenguin — DISMISSED** [review]

File: Source/LinqToDB/Internal/DataProvider/Ydb/YdbSqlExpressionConvertVisitor.cs (hunk 1 above)
Comment (MaceWindu) [reply Source/LinqToDB/Internal/DataProvider/Ydb/YdbSqlExpressionConvertVisitor.cs:145]: because I still work on it

**Review by viceroypenguin — APPROVED** [review]
