### PR TITLE
#4172: Fixes issue with empty string check in Oracle

### LINKED ISSUE #4172: Issue when using NotEqual check with Enums that map to empty string in Oracle
We're facing issue when trying to use NotEqual check with Enums that map to empty string ("").
Earlier Linq2Db used to just compare the value to NULL, but now it's comparing it to empty string and adding (OR [col] IS NULL) to the predicate.
It works for when we're checking for Equal to empty string but fails for Not Equal to empty string

### Scenario 1 : Checking with "Equal" (Works)
```c#
var data = (
 from pe in db.USER
 where pe.ROLE == Role.Unknown
 select pe).ToList();
```

SQL Generated
```sql
SELECT
	pe.ROLE
FROM
	"USER" pe
WHERE
	(pe.ROLE = '' OR pe.ROLE IS NULL)
```

### Scenario 2 : Checking with "NotEqual" (Doesn't work)
```c#
// Doesn't work	
var data = (
 from pe in db.USER
 where pe.ROLE != Role.Unknown
 select pe).ToList();
```

SQL Generated
```sql
SELECT
	pe.ROLE
FROM
	"USER" pe
WHERE
	(pe.ROLE <> '' OR pe.ROLE IS NULL)
```

### Environment details

`Linq To DB` version: 5.2.1

Database (with version): Oracle 12

.NET Version: 6

[LinqToDbOracleNullValueIssue.zip](https://github.com/linq2db/linq2db/files/11796321/LinqToDbOracleNullValueIssue.zip)

### PR DESCRIPTION
**Pull request by divyanshbhatia1**
Update Oracle11SqlOptimizer to add null check based on operator

Fix #4172

### CODE REVIEW

**Review by MaceWindu — CHANGES_REQUESTED** [review]
We need test(s), that demonstrate this behavior

File: Tests/Linq/DataProvider/OracleTests.cs [hunk 1]
```diff
@@ -4277,5 +4277,79 @@ public void Issue3740Test2([IncludeDataSources(TestProvName.AllOracle12Plus)] st
...
+		}
+
+		[Test]
+		public static void Issue4172Test1([IncludeDataSources(TestProvName.Oracle12Managed)] string context)
+		{
+			using var db = GetDataConnection(context);
+
+			try
+			{
+				using var users = db.CreateTable<ISSUE4172TABLE>();
```
Comment (MaceWindu) [inline Tests/Linq/DataProvider/OracleTests.cs:4308]: Use CreateLocalTable helper instead of try/catch with delete

File: Tests/Linq/DataProvider/OracleTests.cs [hunk 2]
```diff
@@ -4277,5 +4277,79 @@ public void Issue3740Test2([IncludeDataSources(TestProvName.AllOracle12Plus)] st
...
+		}
+
+		[Test]
+		public static void Issue4172Test2([IncludeDataSources(TestProvName.Oracle12Managed)] string context)
+		{
+			using var db = GetDataConnection(context);
+
+			try
+			{
+				using var users = db.CreateTable<ISSUE4172TABLE>();
```
Comment (MaceWindu) [inline Tests/Linq/DataProvider/OracleTests.cs:4334]: use CreateLocalTable

**Review by MaceWindu — CHANGES_REQUESTED** [review]

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs [hunk 3]
```diff
@@ -90,7 +90,17 @@ public override ISqlPredicate ConvertPredicateImpl(ISqlPredicate predicate, Conv
...
+								if (expr.Operator == SqlPredicate.Operator.Equal)
+								{
+									// When checking Equal to Empty String, adding 'OR [col] IS NULL'
+									sc.Conditions.Add(new SqlCondition(false, new SqlPredicate.IsNull(expr.Expr2, false), true));
+								}
+								else if (expr.Operator == SqlPredicate.Operator.NotEqual)
+								{
+									// When checking NotEqual to Empty String, adding 'AND [col] IS NOT NULL'
+									sc.Conditions.Add(new SqlCondition(false, new SqlPredicate.IsNull(expr.Expr2, true), false));
+								}
```
Comment (jods4) [inline Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs:103]: This changes the behaviors of operators >= and <=. 
It's a breaking change for `Code >= ""`, admittedly an edge case but there's no good reason to break this.

I suggest to simplify to:
```csharp 
bool isNotEqual = expr.Operator == SqlPredicate.Operator.NotEqual;

sc.Conditions.Add(new(
  isNot: false, 
  new SqlPredicate.IsNull(expr.Expr2, isNot: isNotEqual),
  isOr: !isNotEqual)
);
```

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs [hunk 4]
```diff
@@ -102,7 +112,17 @@ public override ISqlPredicate ConvertPredicateImpl(ISqlPredicate predicate, Conv
...
+								if (expr.Operator == SqlPredicate.Operator.Equal)
+								{
+									// When checking Equal to Empty String, adding 'OR [col] IS NULL'
+									sc.Conditions.Add(new SqlCondition(false, new SqlPredicate.IsNull(expr.Expr1, false), true));
+								}
+								else if (expr.Operator == SqlPredicate.Operator.NotEqual)
+								{
+									// When checking NotEqual to Empty String, adding 'AND [col] IS NOT NULL'
+									sc.Conditions.Add(new SqlCondition(false, new SqlPredicate.IsNull(expr.Expr1, true), false));
+								}
```
Comment (jods4) [inline Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs:125]: Same as comment on `expr.Expr2 == ""`

**Review by jods4 — CHANGES_REQUESTED** [review]

File: Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs [hunk 5]
```diff
@@ -113,16 +113,16 @@ public override ISqlPredicate ConvertPredicateImpl(ISqlPredicate predicate, Conv
...
-									// When checking NotEqual to Empty String, adding 'AND [col] IS NOT NULL'
-									sc.Conditions.Add(new SqlCondition(false, new SqlPredicate.IsNull(expr.Expr1, true), false));
-								}
+								bool isNotEqual = expr.Operator == SqlPredicate.Operator.NotEqual;
+
+								// Add 'AND [col] IS NOT NULL' when checking Not Equal to Empty String,
+								// else add 'OR [col] IS NULL'
+								sc.Conditions.Add(new(
+								  isNot: false,
+								  new SqlPredicate.IsNull(expr.Expr2, isNot: isNotEqual),
```
Comment (jods4) [inline Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs:122]: Copy-paste mistake. It should be `expr.Expr1` on this side.

**Review by jods4 — APPROVED** [review]

**Review by MaceWindu — APPROVED** [review]
