### PR TITLE
Fix for #3462. Added another prediction for FirstSingleContext.

### LINKED ISSUE #3462: Cross apply within cross apply does not execute as a single query
Executing a cross apply within another cross apply should result in a single query, but instead it is split into two queries.  Prior to #3459 it would fail to execute at all, but with #3459 it incorrectly executes as two separate queries.

See:
- #3161 
- #3459 

## Failing test:

```cs
using System;
using System.Linq;
using FluentAssertions;
using LinqToDB;
using LinqToDB.Mapping;
using NUnit.Framework;

namespace Tests.UserTests
{
	[TestFixture]
	public class Issue3462Tests : TestBase
	{
		[Table("TABLE1")]
		public partial class Table1
		{
			[Column("ID1"), PrimaryKey, NotNull] public int Id1 { get; set; }
			[Column("NAME1"), Nullable] public string? Name1 { get; set; }
		}

		[Table("TABLE2")]
		public partial class Table2
		{
			[Column("ID2"), PrimaryKey, NotNull] public int Id2 { get; set; }
			[Column("PARENTID2"), NotNull] public int ParentId2 { get; set; }
			[Column("NAME2"), Nullable] public string? Name2 { get; set; }
		}

		[Table("TABLE3")]
		public partial class Table3
		{
			[Column("ID3"), PrimaryKey, NotNull] public int Id3 { get; set; }
			[Column("PARENTID3"), NotNull] public int ParentId3 { get; set; }
			[Column("NAME3"), Nullable] public string? Name3 { get; set; }
		}

		[Test]
		public void CrossApplyTwice([IncludeDataSources(TestProvName.AllSqlServer2008Plus)] string context)
		{
			using var db = GetDataContext(context);
			using var tbl1 = db.CreateLocalTable(new[]
			{
				new Table1 { Id1 = 1, Name1 = "Some1" },
				new Table1 { Id1 = 2, Name1 = "Some2" },
			});
			using var tbl2 = db.CreateLocalTable(new[]
			{
				new Table2 { Id2 = 11, ParentId2 = 1, Name2 = "Child11" },
				new Table2 { Id2 = 12, ParentId2 = 1, Name2 = "Child12" },
				new Table2 { Id2 = 13, ParentId2 = 2, Name2 = "Child13" },
			});
			using var tbl3 = db.CreateLocalTable(new[]
			{
				new Table3 { Id3 = 21, ParentId3 = 11, Name3 = "Child21" },
				new Table3 { Id3 = 22, ParentId3 = 11, Name3 = "Child22" },
				new Table3 { Id3 = 23, ParentId3 = 12, Name3 = "Child23" },
			});
			var ret = db.GetTable<Table1>()
				.Select(t1 => new
				{
					Name1 = t1.Name1,
					Value1 = db.GetTable<Table2>()
						.Where(x => x.ParentId2 == t1.Id1)
						.Select(t2 => new
						{
							//first cross apply
							Name2 = t2.Name2,
							Value2 = db.GetTable<Table3>()
								.Where(x => x.ParentId3 == t2.Id2)
								.Select(t3 => new
								{
									//nested cross apply
									Name3 = t3.Name3,
									Value3 = t3.Id3
								})
								.FirstOrDefault()
						})
						.FirstOrDefault()
				})
				.ToList();
			Assert.That(ret.Count, Is.EqualTo(2));

			// validate that the prior statement executed as a single query, not two distinct queries
			// LastQuery will only return a single query, so if it was split into two queries, not all name fields would be present
			var lastQuery = ((DataConnection)db).LastQuery;
			Assert.That(lastQuery, Contains.Substring("NAME1"));
			Assert.That(lastQuery, Contains.Substring("NAME2"));
			Assert.That(lastQuery, Contains.Substring("NAME3"));
		}
	}
}
```

## Incorrect SQL currently generated

```sql
DECLARE @take Int -- Int32
SET     @take = 1

SELECT
	[t1_1].[ID1],  -- notice here it is pulling the id from table1, not the name
	[detail].[NAME2],
	[t1].[Name3],
	[t1].[Value3]
FROM
	[TABLE1] [t1_1]
		INNER JOIN [TABLE2] [detail] ON [detail].[PARENTID2] = [t1_1].[ID1]
		OUTER APPLY (
			SELECT TOP (@take)
				[_x].[NAME3] as [Name3],
				[_x].[ID3] as [Value3]
			FROM
				[TABLE3] [_x]
			WHERE
				[_x].[PARENTID3] = [detail].[ID2]
		) [t1]
```
and
```sql
SELECT
	[t1].[NAME1],
	[t1].[ID1]
FROM
	[TABLE1] [t1]
```

## Expected SQL

```sql
DECLARE @take Int -- Int32
SET     @take = 1

SELECT
        [t1_1].[NAME1],   -- it should pull the name and not the id from table1
	[detail].[NAME2],
	[t1].[Name3],
	[t1].[Value3]
FROM
	[TABLE1] [t1_1]
		INNER JOIN [TABLE2] [detail] ON [detail].[PARENTID2] = [t1_1].[ID1]
		OUTER APPLY (
			SELECT TOP (@take)
				[_x].[NAME3] as [Name3],
				[_x].[ID3] as [Value3]
			FROM
				[TABLE3] [_x]
			WHERE
				[_x].[PARENTID3] = [detail].[ID2]
		) [t1]
```

## Invalid SQL generated prior to #3459 

See issue:
- #3161

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #3462

### CODE REVIEW

File: Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs [hunk 1]
```diff
@@ -282,15 +282,11 @@ static bool HasSubQuery(IBuildContext context)
 					{
 						foreach (var member in sc.Members.Values)
 						{
-							var found = null != member.Find(ctx, static(c, e) =>
+							if (member is MethodCallExpression mc && context.Builder.IsSubQuery(ctx, mc))
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs:285]: in context here, wouldn't this be simpler:
```csharp
return member is MethodCallExpression mc && context.Builder.IsSubQuery(ctx, mc);
```

**Review by viceroypenguin — APPROVED** [review]

File: Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs (hunk 1 above)
Comment (sdanyliv) [reply Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs:285]: Don't worry about this place. I'm planning completely remove such code in new version.

Comment (viceroypenguin) [reply Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs:285]: Works for me. :)

File: Tests/Linq/UserTests/Issue3161Tests.cs [hunk 2]
```diff
@@ -112,10 +112,9 @@ public void CrossApplyTwice([IncludeDataSources(TestProvName.AllSqlServer2008Plu
 				.ToList();
 			Assert.That(ret.Count, Is.EqualTo(2));
 
-			// uncomment after 3161 fixed
-			//var baselines = GetCurrentBaselines();
-			//baselines.Should().Contain("SELECT", Exactly.Twice());
-			//baselines.Should().Contain("SELECT TOP", Exactly.Once());
+			var baselines = GetCurrentBaselines();
+			baselines.Should().Contain("SELECT", Exactly.Times(3));
+			baselines.Should().Contain("SELECT TOP", Exactly.Twice());
```
Comment (Shane32) [inline Tests/Linq/UserTests/Issue3161Tests.cs:117]: Without the fix, "SELECT" occurs 3 times and "SELECT TOP" occurs once.  It would seem it it could be coincidental that these checks serve to validate that the query is executed as a single statement.  I suggest adding additional tests here along with comments to reinforce the issue we are trying to test for.

```suggestion
			// validate that the prior statement executed as a single query, not two distinct queries
			var baselines = GetCurrentBaselines();
			baselines.Should().Contain("SELECT", Exactly.Times(3));
			baselines.Should().Contain("SELECT TOP", Exactly.Twice());

			// LastQuery will only return a single query, so if it was split into two queries, not all name fields would be present
			var lastQuery = ((DataConnection)db).LastQuery;
			lastQuery.Should().Contain("NAME1", Exactly.Once());
			lastQuery.Should().Contain("NAME2", Exactly.Once());
			lastQuery.Should().Contain("NAME3", Exactly.Once());
```

Comment (Shane32) [reply Tests/Linq/UserTests/Issue3161Tests.cs:117]: Note that `using LinqToDB.Data;` is required to be added for the above change.

**Review by MaceWindu — DISMISSED** [review]
Ignore clickhouse failures. I suspect september release of ClickHouse introduced a lot of breaking changes. Will look at it later

**Review by Shane32 — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]
