### PR TITLE
Stub Type.GetInterfaceMap on CoreRT

### LINKED ISSUE #2680: SQLite.Ms wants to use System.Data.Sqlite in Release mode
I use linq2db and linq2db.SQLite.MS. Compiling to Debug mode does not produce any Error.
But on doing this in Release mode, the first time it tries to create a DataConnection it shuts down with the Error below.

```
Exception message: 
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Cannot load assembly System.Data.SQLite
  Quelle = <Die Ausnahmequelle kann nicht ausgewertet werden.>
  Stapelüberwachung:
<Die Ausnahmestapelüberwachung kann nicht ausgewertet werden.>

Stack trace:
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.CreateAdapter(String assemblyName, String clientNamespace, String prefix) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteProviderAdapter.cs:line 52
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.GetInstance(String name) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteProviderAdapter.cs:line 78
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider..ctor(String name, MappingSchema mappingSchema) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteDataProvider.cs:line 32
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider..ctor(String name) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteDataProvider.cs:line 27
   at LinqToDB.DataProvider.SQLite.SQLiteTools.<>c.<.cctor>b__21_0() in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteTools.cs:line 17
   at System.Func`1.Invoke()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Lazy.cs:line 324
```

### Steps to reproduce
I use the code below to build my LinqToDbConnectionOptions. Nothing else has been used.

```c#
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
            var connectionString = @"Data Source=internal.db";

            // create options builder
            var builder = new LinqToDbConnectionOptionsBuilder();

            // configure connection string
            builder.UseSQLite(connectionString);

            return builder.Build();
```

### Environment details
linq2db version: *3.1.6*
Database Server: *?*
Database Provider: *SQlite MS*
Operating system: *Windows*
.NET Framework: *.Net Standard 2.0*

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #2680 

Note that this issue applies only to CoreRT runtime, enabled by `Compile with .NET Native tool chain` build option.
Implementation for this method were added to corert by [this](https://github.com/dotnet/corert/pull/8144) PR but it looks like it was never released and whole CoreRT stuff [looks like dead horse](https://github.com/dotnet/corert/issues/7200).

@Daveismus, I'm replacing GetInterfaceMap implementation with noop method, which means you cannot use interfaces in your data model (linq2db will not see them). Another option to make it work is to disable AOT buid for your project...

### CODE REVIEW

File: Source/LinqToDB/Extensions/ReflectionExtensions.cs [hunk 1]
```diff
@@ -288,7 +317,7 @@ static void GetAttributesTreeInternal(List<object> list, Type type)
 				{
 					var getAttr = false;
 
-					foreach (var mi in type.GetInterfaceMap(intf).TargetMethods)
+					foreach (var mi in type.GetInterfaceMapEx(intf).TargetMethods)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Extensions/ReflectionExtensions.cs:320]: If we return `default` above, does that mean we're going to get an NRE on `.TargetMethods`?

File: Source/LinqToDB/Extensions/ReflectionExtensions.cs [hunk 2]
```diff
@@ -241,12 +241,41 @@ public static MemberInfo[] GetPublicMemberEx(this Type type, string name)
...
+			// (added here https://github.com/dotnet/corert/pull/8144)
+#if NETSTANDARD2_0
+			if (_getInterfaceMap == null)
+			{
+				_getInterfaceMap = (t, i) => t.GetInterfaceMap(i);
+				try
+				{
+					return _getInterfaceMap(interfaceType):
+				}
+				catch (PlatformNotSupportedException)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Extensions/ReflectionExtensions.cs:259]: If we catch `PlatformNotSupportedException` even once, doesn't that mean we'll get it for all functions? So maybe would be better to use a simple `bool? flag` of some kind to track unsupported (`null` means untested, `true`/`false` mean known, etc.

Comment (MaceWindu) [reply Source/LinqToDB/Extensions/ReflectionExtensions.cs:259]: we will enter this `if` only first  time when  `_getInterfaceMap` is not yet initialized

File: Source/LinqToDB/Extensions/ReflectionExtensions.cs (hunk 1 above)
Comment (MaceWindu) [reply Source/LinqToDB/Extensions/ReflectionExtensions.cs:320]: yep, will fix it tomorrow

File: Source/LinqToDB/Extensions/ReflectionExtensions.cs (hunk 2 above)
Comment (viceroypenguin) [reply Source/LinqToDB/Extensions/ReflectionExtensions.cs:259]: Ah. Yup. Misread that as a dictionary to be initialized for each (type, type) rather than a func. I'm good w/ this.

**Comment by MaceWindu** [comment]
Tested stub with sqlite - as expected only 4 tests that use interface mappings failed. Also managed to run some queries in UWP using MS sqlite provider.

**Review by viceroypenguin — APPROVED** [review]
