### PR TITLE
Unify SqlExpression and SqlFunction code bases

### LINKED ISSUE #4933: Sql.FunctionAttribute.IsPredicate is ignored
### Description

Mapping  SQL Server FTS function `CONTAINS` (returns bool):

```csharp
    [Function(FunctionType.BuiltInFunction, "CONTAINS", StoreFunctionName = "CONTAINS")]
    [return: Parameter(DbType = "bit", ClrType = typeof(bool))]
    public static bool FtxContains([Parameter(DbType = "varbinary(max)")] byte[] columnOrColumns, [Parameter(DbType = "nvarchar(max)")] string search)
    {
        throw new NotSupportedException();
    }
```

Mapped with attribute:

```csharp
  new Sql.FunctionAttribute(functionAttribute.FunctionName)
  {
      ServerSideOnly = true,
      CanBeNull = false,
      InlineParameters = false,
      PreferServerSide = true,
      IsPredicate = true
  }
```

```sql
SELECT
        COUNT(*)
FROM
        [dbo].[AccountManagers] [x]
WHERE
        [x].[IsDeleted] = 0 AND [x].[Active] = @Value AND CONTAINS([x].[UniversalSearch], @Value_1) = 1


DECLARE Value Boolean = True
DECLARE Value_1 String = '"brett"'
```

It still generates unnecessary comparison. It seems that `IsPredicate` is only used in extensions.

### Reproduction Steps

```csharp
public static bool FtxContains(byte[] column, string search)
{
    throw new NotSupportedException();
}

new Sql.FunctionAttribute("CONTAINS")
{
    ServerSideOnly = true,
    CanBeNull = false,
    InlineParameters = false,
    PreferServerSide = true,
    IsPredicate = true
}
```

### Exception details

_No response_

### Regression?

_No response_

### Linq To DB version

6.0.0-preview.4

### .NET version

9.0.2

### Database

_No response_

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #4933

- Unify SqlExpression and SqlFunction code bases
- add SqlFragment node for untyped SQL expression
- fix IsPredicate support for Sql.Function and Sql.Extension

### CODE REVIEW

File: Source/LinqToDB/SqlQuery/SqlParametrizedExpressionBase.cs [hunk 1]
```diff
@@ -0,0 +1,110 @@
+﻿using System;
+using System.Diagnostics.CodeAnalysis;
+using System.Linq;
+
+using LinqToDB.Common;
+
+namespace LinqToDB.SqlQuery
+{
+	public abstract class SqlParametrizedExpressionBase : SqlExpressionBase
```
Comment (viceroypenguin) [inline Source/LinqToDB/SqlQuery/SqlParametrizedExpressionBase.cs]: sp: `Parameterized`

Comment (MaceWindu) [reply Source/LinqToDB/SqlQuery/SqlParametrizedExpressionBase.cs]: dont really care, but looks like nobody knows proper spelling :) https://en.wiktionary.org/wiki/parametrization

Comment (viceroypenguin) [reply Source/LinqToDB/SqlQuery/SqlParametrizedExpressionBase.cs]: Ha. Probably US vs UK again. :)

**Review by viceroypenguin — APPROVED** [review]

File: Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs [hunk 2]
```diff
@@ -291,7 +291,7 @@ public static void MakeAlternativeInsertOrUpdate(Query query)
 			else
 			{
 				firstStatement.SelectQuery.Select.Columns.Clear();
-				firstStatement.SelectQuery.Select.Columns.Add(new SqlColumn(firstStatement.SelectQuery, new SqlExpression("1")));
+				firstStatement.SelectQuery.Select.Columns.Add(new SqlColumn(firstStatement.SelectQuery, new SqlExpression(typeof(int), "1")));
```
Comment (sdanyliv) [inline Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs]: Can we remove constructor overload which acccepts `System.Type`. MappingSchema defines `DbDataType`. In future it should be right TypeMapping type.

Comment (MaceWindu) [reply Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs]: done

**Review by viceroypenguin — APPROVED** [review]
