### PR TITLE
Fix pgsql enum parameters evaluation

### LINKED ISSUE #3548: SQL query not generated properly when using enums in PostgreSQL
In linq2db v3.7.0 enum support for PostgreSQL was added.
Today I noticed that one of my queries that previously worked now is not working correctly. I found that this happens when I mark the column as DataType.Enum
I created an example that demonstrates this issue:

Here is the database schema:
```sql
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_type_enum;
CREATE TYPE user_type_enum AS ENUM ('org', 'org_user');
CREATE TABLE IF NOT EXISTS users
(
  id INT NOT NULL CONSTRAINT schedule_pk PRIMARY KEY,
  type user_type_enum NOT NULL,
  organization_id INT
);
INSERT INTO users(id,type,organization_id) VALUES (1,'org',null),(2,'org_user',1),(3,'org_user',1),(4,'org',null),(5,'org_user',4);
```

and here is the console sample app:
```cs
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;
using Npgsql;
using NpgsqlTypes;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace test
{
    [Table(Schema = "public", Name = "users")]
    public partial class User
    {
        [Column("id"), PrimaryKey, NotNull] public int Id { get; set; }
        [Column("type", DataType = DataType.Enum), NotNull] public UserTypeEnum Type { get; set; }
        [Column("organization_id"), Nullable] public int? OrganizationId { get; set; }

        [ExpressionMethod(nameof(InYourOrganizationSelector))]
        public bool InYourOrganization(User callingUser)
        {
            throw new NotImplementedException();
        }

        internal static Expression<Func<User, User, bool>> InYourOrganizationSelector()
        {
            return (user, callingUser) => (user.Type == UserTypeEnum.Organization && user.Id == callingUser.Id)
                    || (user.Type == UserTypeEnum.Organization && callingUser.Type == UserTypeEnum.OrganizationUser && user.Id == callingUser.OrganizationId)
                    || (user.Type == UserTypeEnum.OrganizationUser && callingUser.Type == UserTypeEnum.Organization && user.OrganizationId == callingUser.Id)
                    || (user.Type == UserTypeEnum.OrganizationUser && callingUser.Type == UserTypeEnum.OrganizationUser && user.OrganizationId == callingUser.OrganizationId);
        }
    }

    [PgName("user_type_enum")]
    public enum UserTypeEnum
    {
        [PgName("org")]
        [MapValue("org")]
        Organization = 1,

        [PgName("org_user")]
        [MapValue("org_user")]
        OrganizationUser = 2,
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            var options = new JsonSerializerOptions { Converters = { new JsonStringEnumConverter() } };
            DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Verbose);
            DataConnection.WriteTraceLine = (s1, s2, level) => Console.WriteLine($"{level}: {s1}, {s2}");
            var db = new DataConnection(ProviderName.PostgreSQL, "Server=localhost;Port=5432;Database=test;User Id=postgres;Password=postgres;");
            NpgsqlConnection.GlobalTypeMapper.MapEnum<UserTypeEnum>();
            try
            {
                var callingUser = await db.GetTable<User>().FirstOrDefaultAsync(x => x.Id == 3);
                var users = await db.GetTable<User>().Where(x => x.InYourOrganization(callingUser)).Select(x => x.Id.ToString()).ToListAsync();
                Console.WriteLine($"Users in your organization: {string.Join(",", users)}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            Console.WriteLine("Done!");
            Console.ReadKey();
        }
    }
}
```

This will generate following query that is not correct:
```sql
SELECT
        x.id
FROM
        "public".users x
WHERE
        (x.type = 'org' AND x.id = :Id)
```
and there are no results found but there should be.

If I change this:
```cs
        [Column("type", DataType = DataType.Enum), NotNull] public UserTypeEnum Type { get; set; }
```
to this (remove DataType = DataType.Enum)
```cs
        [Column("type"), NotNull] public UserTypeEnum Type { get; set; }
```

Then the generated query is correct:
```sql
SELECT
        x.id
FROM
        "public".users x
WHERE
        ((x.type = 'org' AND x.id = :Id OR x.type = 'org' AND x.id = :OrganizationId) OR x.type = 'org_user' AND x.organization_id = :OrganizationId)
```
And the result is correct:
```
Users in your organization: 1,2,3
```

### Environment details
linq2db version: 3.7.0
Database Server: PostgreSQL 14.1
Database Provider: Npgsql
Operating system: Windows 10
.NET Framework: 6.0

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #3548

### CODE REVIEW

File: Source/LinqToDB/Mapping/ColumnDescriptor.cs [hunk 1]
```diff
@@ -516,6 +518,23 @@ public static DataType CalculateDataType(MappingSchema mappingSchema, Type syste
...
+		/// </summary>
+		/// <returns>Returns Lambda which extracts member value.</returns>
+		public LambdaExpression GetOriginalValueLambda()
+		{
+			if (_getOriginalValueLambda != null)
+				return _getOriginalValueLambda;
+
+			var objParam   = Expression.Parameter(MemberAccessor.TypeAccessor.Type, "obj");
+			var getterExpr = MemberAccessor.GetterExpression.GetBody(objParam);
+
```
Comment (viceroypenguin) [inline Source/LinqToDB/Mapping/ColumnDescriptor.cs:532]: Remove extra blank line

```suggestion
```

File: Source/LinqToDB/Sql/Sql.cs [hunk 2]
```diff
@@ -668,6 +668,7 @@ void IExtensionCallBuilder.Build(ISqExtensionBuilder builder)
 			{
 				var str = builder.GetExpression("str");
 
+				var whiteSpaces = $"%[^{WHITESPACES}]%";
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.cs:671]: Under C#10, interpolated strings with constant parameters can also be constant. (also for other similar lines later in file)

```suggestion
				const string whiteSpaces = $"%[^{WHITESPACES}]%";
```

File: Source/LinqToDB/SqlQuery/QueryHelper.Evaluate.cs [hunk 3]
```diff
@@ -109,6 +116,15 @@ static bool TryEvaluateExpressionInternal(this IQueryElement expr, EvaluationCon
 					    !exprExpr.Expr2.TryEvaluateExpression(context, out var value2, out errorMessage))
 						return false;
 
+					if (value1 != null && value2 != null)
+					{
+						if (value1.GetType().IsEnum != value2.GetType().IsEnum)
```
Comment (viceroypenguin) [inline Source/LinqToDB/SqlQuery/QueryHelper.Evaluate.cs:121]: Confirming this correctly handles the case where they are both `IsEnum`, but different enum types (through other `.GetType()` checks later/earlier?)

**Review by viceroypenguin — APPROVED** [review]
