### PR TITLE
Fix build of interface member as association 

### LINKED ISSUE #5069: Generic interface based query filteres fail traversing associations
### Description

When using somewhat complex set of generic interfaces and generically defined query filters, then association definitions seem to break.

I want to remark, just in case, that maybe I've made some kind of mistake in `EntityFilterHelper.GetLambda<...>()` method. If that is so, I apologize. But as of right now, I'm unable to find any issues with that particular logic. (This code works with `[ExpressionMethod]`-based methods very well - issues only exist with `[Association]`-based methods)

### Reproduction Steps

Mini project is implemented here:
https://github.com/Seramis/Linq2Db_BugHunt/tree/queryFilters_associations

Initially it works, showing that `x.GetOwnerUsers()` is translatable when being selected by query.

If line 26 in `Program.cs` is uncommented, it enables the filtering (Implemented in `IUserOwned.Filter<T>`) That uses the same `x.GetOwnerUsers()` asssociation, but this time it fails to translate the LINQ into SQL.

### Exception details

```
Unhandled exception. LinqToDB.LinqToDBException: The LINQ expression could not be converted to SQL.
Expression:
x.GetOwnerUsers()
        .Any(y => (int?)y.Id == db.Attributes.UserId)
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.Build[T](IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.GetQuery(IDataContext dataContext, IQueryExpressions& expressions, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetQuery(IQueryExpressions& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in /home/joonatan/src/Linq2Db_Bug/Linq2Db_Bug/Program.cs:line 32

Process finished with exit code 134.
```

### Regression?

_No response_

### Linq To DB version

6.0.0-rc.2

### .NET version

9.0.303

### Database

SQLite

### Database provider

System.Data.SQLite 1.0.119

### Operating system

Linux

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #5069

### CODE REVIEW

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs [hunk 1]
```diff
@@ -145,17 +145,28 @@ public bool IsAssociation(Expression expression, [NotNullWhen(true)] out MemberI
 		{
 			AssociationDescriptor? descriptor = null;
 
-			if (accessorMember.MemberInfo.MemberType == MemberTypes.Method)
+			if (accessorMember.MemberInfo is { MemberType: MemberTypes.Method, DeclaringType: not null })
 			{
-				var attribute = MappingSchema.GetAttribute<AssociationAttribute>(
-					accessorMember.MemberInfo.DeclaringType!, accessorMember.MemberInfo);
+				var memberInfo = accessorMember.MemberInfo;
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs]:
```suggestion
			if (accessorMember.MemberInfo is { MemberType: MemberTypes.Method, DeclaringType: not null } memberInfo)
			{
```

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs [hunk 2]
```diff
@@ -145,17 +145,28 @@ public bool IsAssociation(Expression expression, [NotNullWhen(true)] out MemberI
...
+
+				var attribute = MappingSchema.GetAttribute<AssociationAttribute>(memberInfo.DeclaringType!, accessorMember.MemberInfo);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs]:
```suggestion
				var attribute = MappingSchema.GetAttribute<AssociationAttribute>(memberInfo.DeclaringType!, memberInfo);
```

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs [hunk 3]
```diff
@@ -145,17 +145,28 @@ public bool IsAssociation(Expression expression, [NotNullWhen(true)] out MemberI
...
+
+				if (attribute == null && memberInfo.DeclaringType?.IsInterface == true && !entityDescriptor.ObjectType.IsInterface)
+				{
+					var newInfo = entityDescriptor.ObjectType.GetImplementation(accessorMember.MemberInfo);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.Associations.cs]:
```suggestion
					var newInfo = entityDescriptor.ObjectType.GetImplementation(memberInfo);
```

**Review by viceroypenguin — DISMISSED** [review]

**Review by viceroypenguin — APPROVED** [review]
