### PR TITLE
Do not combine aggregation query with complex parent query.

### LINKED ISSUE #5381: Invalid SQL generated when joining a non-grouped aggregation query
### Description

Invalid SQL is generated when joining a non-grouped query (i.e. `SELECT MAX(Date) FROM MyTable` without a GROUP BY clause)

Reproduction is provided below

### Reproduction Steps

The following produces the exception reliably

```csharp
var records = db
    .GetTable<DateRanges>()
    .GroupBy(_ => Sql.GroupBy.None)
    .Select(grouping => new
    {
        MinDate = grouping.Min(d => d.StartDate),
        MaxDate = grouping.Max(d => d.EndDate)
    })
    .InnerJoin(db.GetTable<SmallerDateRanges>(),
        (date1, date2) => date1.MinDate <= date2.EndDate && date1.MaxDate >= date2.StartDate,
        (date1, date2) => new { date2.StartDate, date2.EndDate })
    .ToList();

// POCO classes
public class DateRanges
{
    public DateOnly StartDate { get; set; }
    public DateOnly EndDate { get; set; }
}

public class SmallerDateRanges
{
    public DateOnly StartDate { get; set; }
    public DateOnly EndDate { get; set; }
}
```

Generated SQL is 
```sql
SELECT
        [date2].[StartDate],
        [date2].[EndDate]
FROM
        [DateRanges] [date1]
                INNER JOIN [SmallerDateRanges] [date2] ON MIN([date1].[StartDate]) <= [date2].[EndDate] AND MAX([date1].[EndDate]) >= [date2].[StartDate]
```

### Exception details

```
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): An aggregate cannot appear in an ON clause unless it is in a subquery contained in a HAVING clause or select list, and the column being aggregated is an outer reference.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Async.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Regression?

Works in 5.4.1

### Linq To DB version

6.x (6.0.0 and 6.1.0)

### .NET version

8.0

### Database

SQL Server 2022

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #5381

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by viceroypenguin** [comment]
@sdanyliv see https://github.com/linq2db/linq2db/pull/5201/changes/3530de0c95d3bd5dd04f37112ebbd5af1ba45e02

File: Tests/Linq/Linq/JoinTests.cs [hunk 1]
```diff
@@ -2490,6 +2492,7 @@ where fact.Id > 3
 			}
 		}
 
+		[ActiveIssue(Details = "Wrong result set is returned.", Configuration = TestProvName.AllClickHouse)]
```
Comment (MaceWindu) [inline Tests/Linq/Linq/JoinTests.cs]:
```suggestion
```
