### PR TITLE
Stack use optimizations

### LINKED ISSUE #5265: Stack overflow
### Description

Perhaps a duplicate of the previous one, but:

### Reproduction Steps

var rawOutputQuery = db.GetTable<SomeType>();
var outputItems = rawOutputQuery.ToArrayAsync();

SomeType is complex type with many associations && calculated properties

[StackTrace.txt](https://github.com/user-attachments/files/24237281/StackTrace.txt)

### Exception details

_No response_

### Regression?

_No response_

### Linq To DB version

6.1

### .NET version

8.0

### Database

_No response_

### Database provider

Postgre 15

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Implement different improvements to stack use. Helps fix #5265

- Apply Accept pattern to AST visitor
- migrate most of old expression visitors to use our base visitor
- Split some methods with branching and a big stackframe to sub-methods

### CODE REVIEW

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionTreeOptimizationContext.cs [hunk 1]
```diff
@@ -504,16 +504,13 @@ public bool IsImmutable(Expression expr)
...
 		#region PreferServerSide
 
-		private FindVisitor<ExpressionTreeOptimizationContext>? _enforceServerSideVisitorTrue;
-		private FindVisitor<ExpressionTreeOptimizationContext>? _enforceServerSideVisitorFalse;
-
 		[MethodImpl(MethodImplOptions.AggressiveInlining)]
-		private FindVisitor<ExpressionTreeOptimizationContext> GetVisitor(bool enforceServerSide)
+		private bool PreferServerSide(bool enforceServerSide, Expression expr)
 		{
 			if (enforceServerSide)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionTreeOptimizationContext.cs]: See `RemoveNullPropagationTransformation` - maintain consistency between the two...

File: Source/LinqToDB/Internal/SqlQuery/IQueryExtension.cs [hunk 2]
```diff
@@ -1,9 +1,6 @@
-﻿using LinqToDB.Internal.SqlQuery.Visitors;
-
-namespace LinqToDB.Internal.SqlQuery
+﻿namespace LinqToDB.Internal.SqlQuery
 {
 	public interface IQueryExtension : IQueryElement
 	{
-		IQueryElement Accept(QueryElementVisitor visitor);
 	}
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/SqlQuery/IQueryExtension.cs]:
```suggestion
	public interface IQueryExtension : IQueryElement;
```

**Review by sdanyliv — APPROVED** [review]
