### PR TITLE
Fix custom type collection mapping

### LINKED ISSUE #5057: Cannot generate SQL in 6.0.0-rc.2 that was generated in 5.4.1
### Description

See repro: https://github.com/timbze/Linq2Db4539/blob/master/Program.cs

5.4.1 did generate SQL properly but had a different error with this same code. I think the similar issue that was fixed in #4798 would make this work, if the SQL could be generated.

This specific thing I can fix by making my list to be Guid, but I don't understand why it should not work when the type is List<TenderId>.

```csharp
List<TenderId> tenderIds2 = new List<TenderId> {TenderId.From(Guid.NewGuid()), TenderId.From(Guid.NewGuid())};
var tender2 = await db
    .GetTable<Tender>()
    .Where(i => tenderIds2.Any(id => id == i.Id))
    .FirstOrDefaultAsync();
```

### Reproduction Steps

See code above.

### Exception details

```
Unhandled exception. LinqToDB.LinqToDBException: The LINQ expression could not be converted to SQL.
Expression:
<>c__DisplayClass0_0.tenderIds2
        .Any(id => id == i.Id)
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.Build[T](IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.GetQuery(IDataContext dataContext, IQueryExpressions& expressions, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetQuery(IQueryExpressions& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.LinqToDB.Internal.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

### Regression?

_No response_

### Linq To DB version

6.0.0-rc.2

### .NET version

9.0.7

### Database

_No response_

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #5057

### CODE REVIEW

File: Source/LinqToDB/Internal/Linq/Builder/EnumerableContext.cs [hunk 1]
```diff
@@ -17,9 +17,9 @@ namespace LinqToDB.Internal.Linq.Builder
 {
 	sealed class EnumerableContext : BuildContextBase
 	{
-		public override Expression?    Expression    { get; }
-		public override MappingSchema  MappingSchema => Builder.MappingSchema;
-		public          SqlValuesTable Table         { get; }
+		public override Expression? Expression { get; }
+		public override MappingSchema MappingSchema => Builder.MappingSchema;
+		public SqlValuesTable Table { get; }
```
Comment (sdanyliv) [inline Source/LinqToDB/Internal/Linq/Builder/EnumerableContext.cs]: Alignment broken

File: Source/LinqToDB/Internal/Linq/Builder/EnumerableContext.cs [hunk 2]
```diff
@@ -34,8 +34,8 @@ public EnumerableContext(TranslationModifier translationModifier, ExpressionBuil
 		EnumerableContext(TranslationModifier translationModifier, ExpressionBuilder builder, Expression expression, SelectQuery query, SqlValuesTable table, Type elementType)
 			: base(translationModifier, builder, elementType, query)
 		{
-			Parent     = null;
-			Table      = table;
+			Parent = null;
+			Table = table;
```
Comment (sdanyliv) [inline Source/LinqToDB/Internal/Linq/Builder/EnumerableContext.cs]: Alignment broken

**Review by sdanyliv — APPROVED** [review]
