### PR TITLE
Corrected string interpollation nullability.

### LINKED ISSUE #5035: Unable to generate SQL for string interpolation inside `.All()` predicate block
### Description

`Unhandled exception. LinqToDB.LinqToDBException: The LINQ expression could not be converted to SQL.`

### Reproduction Steps

[dotnet fiddle minimal repro](https://dotnetfiddle.net/8S9mvn)

<details>
<summary>Code</summary>

```cs
// linq2db: 6.0.0-rc.1
// linq2db.SQLite: 6.0.0-rc.1

using System;
using System.Linq;
using System.Threading.Tasks;
using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using LinqToDB.Mapping;
using Microsoft.Data.Sqlite;

[Table(Name = "People")]
public sealed class Person
{
    [Column, PrimaryKey, Identity]
    public int Id { get; set; }

    [Column]
    public string? Name { get; set; }

    [Column]
    public string? Street { get; set; }

    [Column]
    public string? City { get; set; }

    [Column]
    public string? Country { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using var sqlite = new SqliteConnection("Data Source=:memory:");
        sqlite.Open();

        // Create a linq2db connection
        using var db = new DataConnection(
            new DataOptions()
                .UseDataProvider(LinqToDB.DataProvider.SQLite.SQLiteTools.GetDataProvider())
                .UseConnection(sqlite)
        );

        // Prepare table & data
        await db.CreateTableAsync<Person>();
        await db.InsertAsync(
            new Person
            {
                Name = "Alice",
                Street = "1 Main",
                City = "Copenhagen",
                Country = "DK",
            }
        );
        await db.InsertAsync(
            new Person
            {
                Name = null,
                Street = null,
                City = "Aarhus",
                Country = "DK",
            }
        );

        var searchWords = new string[] { "alice", "main" };

		// Works in 6.0
		var query1 = db.GetTable<Person>()
            .Where(it =>
                    $"{it.Name ?? ""} {it.Street ?? ""} {it.City ?? ""} {it.Country ?? ""}"
                        .ToLower()
                        .Contains(searchWords[0]) && $"{it.Name ?? ""} {it.Street ?? ""} {it.City ?? ""} {it.Country ?? ""}"
                        .ToLower()
                        .Contains(searchWords[1])
            )
			.ToArrayAsync();
		
	    var query2 = db.GetTable<Person>()
            .Where(it =>
                searchWords.All(word =>
                    ((it.Name ?? "") + " " +
					(it.Street ?? "") + " " +
					(it.City ?? "") + " " +
					(it.Country ?? ""))
                        .ToLower()
                        .Contains(word)
                )
            )
			.ToArrayAsync();
		
        // Query that worked in 5.4
        var query3 = db.GetTable<Person>()
            .Where(it =>
                searchWords.All(word =>
                    $"{it.Name ?? ""} {it.Street ?? ""} {it.City ?? ""} {it.Country ?? ""}"
                        .ToLower()
                        .Contains(word)
                )
            );

        // throws when evaluated
        var result = await query3.ToArrayAsync();
    }
}
```

</details>

### Exception details

From the minimal repro:
```
Unhandled exception. LinqToDB.LinqToDBException: The LINQ expression could not be converted to SQL.
Expression:
<>c__DisplayClass0_0.searchWords
    .All(word => string.Format(
        format: "{0} {1} {2} {3}", 
        args: new object[]
        { 
            it.Name ?? "", 
            it.Street ?? "", 
            it.City ?? "", 
            it.Country ?? "" 
        }).ToLower().Contains(word))
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.Build[T](IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, IQueryExpressions& expressions)
   at LinqToDB.Internal.Linq.Query`1.GetQuery(IDataContext dataContext, IQueryExpressions& expressions, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetQuery(IQueryExpressions& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Async.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Program.Main()
   at Program.<Main>()
```

### Regression?

Worked in 5.4

### Linq To DB version

6.0.0-rc.1

### .NET version

9

### Database

_No response_

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #5035

- Expressions inside string interpolation automatically wrapped by `Coalesce` operator.
- Handling additional overload for `string.Format`

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs [hunk 1]
```diff
@@ -2309,15 +2310,31 @@ public bool HandleFormat(MethodCallExpression node, [NotNullWhen(true)] out Expr
...
 					{
-						var expr = BuildSqlExpression(node.Arguments[i]);
+						inputArguments = arrayExpr.Expressions;
+						startIndex     = 0;
+					}
+					else
+					{
+						inputArguments = node.Arguments;
+						startIndex     = 1;
+					}
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs]:
```suggestion
					var inputArguments = node.Arguments switch
					{
						[_, NewArrayExpression arrayExpr] => arrayExpr.Expressions.AsSpan(),
						_ => node.Arguments.AsSpan()[1..],
					}
```

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs [hunk 2]
```diff
@@ -2309,15 +2310,31 @@ public bool HandleFormat(MethodCallExpression node, [NotNullWhen(true)] out Expr
...
+
+					var arguments = new ISqlExpression[inputArguments.Count - startIndex];
+
+					var stringType = MappingSchema.GetDbDataType(typeof(string));
+
+					for (var i = startIndex; i < inputArguments.Count; i++)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs:2329]:
```suggestion
					for (var i = 0; i < inputArguments.Count; i++)
```

**Review by viceroypenguin — DISMISSED** [review]

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs (hunk 1 above)
Comment (sdanyliv) [reply Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs]: I would avoid polifils for such simple task.

Comment (viceroypenguin) [reply Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs]: Oh! forgot about Span not being in ns2.0. Derp. Will give you alternative in just a sec

Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs]:
```suggestion
					var (inputArguments, startIndex) = node.Arguments switch
					{
						[_, NewArrayExpression arrayExpr] => (arrayExpr.Expressions, 0),
						_ => (node.Arguments, 1),
					}
```

File: Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs [hunk 3]
```diff
@@ -2309,19 +2309,42 @@ public bool HandleFormat(MethodCallExpression node, [NotNullWhen(true)] out Expr
...
+					};
+
+					var arguments = new ISqlExpression[inputArguments.Count - startIndex];
+
+					DbDataType stringType;
+
+					if (CurrentDescriptor?.MemberType == typeof(string))
+						stringType = CurrentDescriptor.GetDbDataType(true);
+					else
+						stringType = MappingSchema.GetDbDataType(typeof(string));
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs:2325]: one more nit, only because declaration and assignment being separate is a personal pet peeve. feel free to disregard if wanted:

```suggestion
					var stringType = CurrentDescriptor?.MemberType == typeof(string))
						? CurrentDescriptor.GetDbDataType(true)
						: MappingSchema.GetDbDataType(typeof(string));
```

Comment (sdanyliv) [reply Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs:2325]: Please do not post such suggestions, I know how to write conditional operator. Everything for debugging.

**Review by igor-tkachev — DISMISSED** [review]

**Review by MaceWindu — APPROVED** [review]
