### PR TITLE
Custom operators mapping improvements

### LINKED ISSUE #5254: Implicit conversion no longer works
### Description

Not sure if it should work, but 5.4.1.9 it works, and in 6.1.0 it does not.

In short:
```c#
// works in 5.4.1.9 but not in 6.1.0
// ShortId struct has implicit conversion for Guid > ShortId
await db
    .GetTable<Tender>()
    .Select(i => new Output { Id = (Guid) i.Id })
    .FirstOrDefaultAsync();

class Output
{
    public ShortId Id { get; set; }
}
```

### Reproduction Steps

Minimal repro.

https://github.com/timbze/Linq2Db4539/blob/d4199b72cb5295a070f1895164ecfacbc7405322/Program.cs#L22-L26

### Exception details

```
Mapper has switched to slow mode. Mapping exception: Cannot convert value 'Linq2Db4539.TenderId: Linq2Db4539.TenderId' to type 'Linq2Db4539.ShortId'DataConnection
Total Execution Time (Completed) (async): 00:00:00.2337466. Rows Count: 0.
DataConnection
Unhandled exception. LinqToDB.Common.LinqToDBConvertException: Cannot convert value 'Linq2Db4539.TenderId: Linq2Db4539.TenderId' to type 'Linq2Db4539.ShortId'
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at LinqToDB.Internal.Conversion.ConvertBuilder.ConvertDefault(Object value, Type conversionType) in /_/Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs:line 26
   --- End of inner exception stack trace ---
   at LinqToDB.Internal.Conversion.ConvertBuilder.ConvertDefault(Object value, Type conversionType) in /_/Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs:line 30
   at lambda_method29(Closure, IQueryRunner, DbDataReader)
   at LinqToDB.Internal.Linq.QueryRunner.Mapper`1.ReMapOnException(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader, ReaderMapperInfo& mapperInfo, Exception ex) in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 130
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 588
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 600
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 600
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 601
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Impl|59_0[TSource](IAsyncEnumerable`1 source, TSource defaultValue, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Impl|59_0[TSource](IAsyncEnumerable`1 source, TSource defaultValue, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass22_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext() in /_/Source/LinqToDB/Internal/Linq/Builder/FirstSingleBuilder.cs:line 230
--- End of stack trace from previous location ---
   at LinqToDB.Internal.Linq.ExpressionQuery`1.LinqToDB.Internal.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 112
   at LinqToDB.Internal.Linq.ExpressionQuery`1.LinqToDB.Internal.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 115
   at Program.<Main>$(String[] args) in /home/timmy/Repos/Linq2Db4539/Program.cs:line 23
   at Program.<Main>(String[] args)
```

### Regression?

Worked in 5.4.1.9

### Linq To DB version

6.1.0

### .NET version

10.0

### Database

Postgresql 16

### Database provider

_No response_

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
- fix/add support for unary/binary operators mapping using `Sql.ExpressionAttribute`, `MemberExpressionAttribute` or `IMemberTranslator`
- fix v6 regressions where mapper loose custom operator calls: fix #5254, fix #5295

### CODE REVIEW

**Comment by MaceWindu** [comment]
baselines issues:
- `IssueTests.Issue73Test` will be addressed by https://github.com/linq2db/linq2db/issues/5299
- fixed: ~`ValueConversionTests.InsertExpression` parameter type change - looking into it~

File: Source/LinqToDB/Expressions/MemberHelper.cs [hunk 1]
```diff
@@ -100,6 +100,12 @@ public static MemberInfo GetMemberInfo(Expression expr)
 		/// <exception cref="ArgumentException">Only simple, non-navigational, member names are supported in this context (e.g.: x =&gt; Sql.Property(x, \"SomeProperty\")).</exception>
 		public static MemberInfoWithType GetMemberInfoWithType(Expression expr)
 		{
+			if (expr is UnaryExpression { Method: { } } ue)
+				return new MemberInfoWithType(ue.Method.ReflectedType, ue.Method);
+
+			if (expr is BinaryExpression { Method: { } } be)
+				return new MemberInfoWithType(be.Method.ReflectedType, be.Method);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Expressions/MemberHelper.cs]:
```suggestion
			while (expr is UnaryExpression { Method: { } method })
				return new MemberInfoWithType(method.ReflectedType, method);

			while (expr is BinaryExpression { Method: { } method })
				return new MemberInfoWithType(method.ReflectedType, method);
```

File: Source/LinqToDB/Expressions/MemberHelper.cs [hunk 2]
```diff
@@ -100,6 +100,12 @@ public static MemberInfo GetMemberInfo(Expression expr)
 		/// <exception cref="ArgumentException">Only simple, non-navigational, member names are supported in this context (e.g.: x =&gt; Sql.Property(x, \"SomeProperty\")).</exception>
 		public static MemberInfoWithType GetMemberInfoWithType(Expression expr)
 		{
+			if (expr is UnaryExpression { Method: { } method1 })
```
Comment (viceroypenguin) [inline Source/LinqToDB/Expressions/MemberHelper.cs:103]: @MaceWindu FYI, the code is the same with `if` vs `while`; the only difference is whether you can reuse `method` or not. 🤷🏼‍♂️

**Review by viceroypenguin — APPROVED** [review]
