### PR TITLE
fix #1606 Implement schema table population for MySql on our side

### LINKED ISSUE #1606: Implement `IndexColumns` schema table population for MySql on our side
I'm able to use linq2db to connect to my database successfully in the create connection dialog using the test button.  However, when I go to actually expand the tree view to start using the connect, It throws a SqlNullValueException, with the message "Data is Null. This method or property cannot be called on Null Values". I've attached the MessageBox with the full call stack below.

Connection string: `Server=<redacted>.amazonaws.com;Database=<redacted>;Uid=<redacted>;Pwd=<redacted>;`

I do have rows with null values in them.

Full error MessageBox:

image

([via](https://forum.linqpad.net/discussion/comment/4152/#Comment_4152))

### PR DESCRIPTION
**Pull request by GonzoSpire**
fix #1606

### CODE REVIEW

File: Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs [hunk 1]
```diff
@@ -79,33 +79,26 @@ protected override List<TableInfo> GetTables(DataConnection dataConnection)
...
+					k.ORDINAL_POSITION                                          as Ordinal
+				FROM
+					INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
+					JOIN
+						INFORMATION_SCHEMA.TABLE_CONSTRAINTS c
+					ON
+						k.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG AND
+						k.CONSTRAINT_SCHEMA  = c.CONSTRAINT_SCHEMA AND
+						k.CONSTRAINT_NAME    = c.CONSTRAINT_NAME AND
+                        k.TABLE_NAME         = c.TABLE_NAME
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs]: fix line alignment

File: Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs [hunk 2]
```diff
@@ -79,33 +79,26 @@ protected override List<TableInfo> GetTables(DataConnection dataConnection)
...
+				WHERE
+					c.CONSTRAINT_TYPE='PRIMARY KEY' AND
+                    c.CONSTRAINT_SCHEMA = database()  ")
```
Comment (MaceWindu) [inline Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs]: fix alignment

File: Tests/Linq/DataProvider/MySqlTests.cs [hunk 3]
```diff
@@ -841,6 +862,7 @@ public void TestTestOutputParametersWithoutTableProcedure([MySqlDataContext(fals
 				Assert.AreEqual(1, res);
 			}
 		}
+
```
Comment (MaceWindu) [inline Tests/Linq/DataProvider/MySqlTests.cs]: extra line added

File: Tests/Linq/DataProvider/MySqlTests.cs [hunk 4]
```diff
@@ -785,6 +785,27 @@ public static IEnumerable<ProcedureSchema> ProcedureTestCases
 				}
 			}
 		}
+
+		[Table("FullTextIndexTest")]
+		private class FullTextIndexTable
```
Comment (MaceWindu) [inline Tests/Linq/DataProvider/MySqlTests.cs]: nused
