### PR TITLE
Fix #1721 - CreateTable generation for DateTime2 with Precision.

### LINKED ISSUE #1721: CreateTable: DateTime2 with Precision incorrectly generated
Given a record type with any DateTime2 field with a precision value, as generated by the T4 templates when `GenerateDataTypes` is enabled, the type cannot be used to create a table or a temporary table in any database due to an error in the SQL generation for the type.

### Steps to reproduce

Simple example (reformatted from T4 template output):

    public class DateTime2Test
    {
        [Column(DataType = DataType.DateTime2, Precision = 7), NotNull]
        public DateTime LastUpdate { get; set; } // datetime2(7)
    }

    public static class Test
    {
        public static void TestCreate(IDataContext ctx)
        {
            using (var tmp = ctx.CreateTempTable<DateTime2Test>("tmp"))
            {
            }
        }
    }

Attempting to create this table via `CreateTable` or `CreateTempTable` results in the following exception:

    System.Data.SqlClient.SqlException: 'Incorrect syntax near ')'.'

(The stack trace for this is long, boring and irrelevant.)

The generated query is as follows:

    CREATE TABLE [tmp]
    (
        [LastUpdate] DateTime2(7,) NOT NULL
    )

The bad type specifier is generated by `LinqToDB.SqlProvider.BasicSqlBuilder` method [`BuildDataType`][1] and the behavior is not overridden.  By default `BuildDataType` assumes that having a precision is only the case when there is a size as well.  This does not work for DateTime2 types.

Fix should be a simple override  in `LinqToDB.DataProvider.SqlServer.SqlServer2008Builder` like this (not tested):

    protected override void BuildDataType(SqlDataType type, bool createDbType)
    {
        switch (type.DataType)
        {
            case DataType.DateTime2:
                if (type.Precision > 0)
                {
                    StringBuilder.Append(type.DataType).Append('(').Append(type.Precision).Append(')');
                    return;
                }
                break;
        }

        base.BuildDataType(type, createDbType);
    }

(This is laid out approximately the same as a couple of the other overrides for consistency.)

### Environment details
linq2db version: *2.7.0*
Database Server: *Microsoft Sql Server 2017 (14.0.2002)*
Database Provider: *Native?*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.7.2*

[1]: https://github.com/linq2db/linq2db/blob/bb54f89c5752fcf93d85b9b056b02c4e14265cb4/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L2506-2536

### PR DESCRIPTION
**Pull request by Corey-M**
DateTime2 type first available in MS SQL 2008.  Added override to `SqlServer2008SqlBuilder` to correctly generate type string for DateTime2 with Precision.

Test add but not tested, fix confirmed in external program.  Please check this test.

### CODE REVIEW

**Comment by Corey-M** [comment]
Fixes #1721

**Comment by Corey-M** [comment]
OK, I made a bad assumption without checking, assumed that the various `SqlServerXXXXSqlBuilder` versions built off each other.  I'll shift the fix into the root `SqlServerSqlBuilder` class.

File: Tests/Linq/UserTests/Issue1721Tests.cs [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+	[TestFixture]
+	public class Issue1721Tests : TestBase
+	{
+		public class I1721Model
+		{
+			[Column(DataType = DataType.DateTime2, Precision = 7), NotNull]
+			public DateTime BadField { get; set; }
+		}
+
+		[ActiveIssue(1721, Configuration = ProviderName.SqlServer2008)]
```
Comment (sdanyliv) [inline Tests/Linq/UserTests/Issue1721Tests.cs]: ActiveIssue is not needed if bug fixed.

Comment (Corey-M) [reply Tests/Linq/UserTests/Issue1721Tests.cs]: I was copying from another test.  Will fix.

**Comment by Corey-M** [comment]
Hopefully this is the last change.  It's not super important but not specifying the precision defaults to 7 for `DateTimeOffset`, `DateTime2` and `Time` types if you don't specify.  This should properly handle all the things.

File: Tests/Linq/UserTests/Issue1721Tests.cs [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+		[Test]
+		public void Issue1721Test([IncludeDataSources(TestProvName.AllSqlServer2008Plus)] string context)
+		{
+			using (var db = GetDataContext(context))
+			{
+				Assert.DoesNotThrow(() =>
+				{
+					using (var temp = db.CreateTempTable<I1721Model>("Issue1721"))
+					{ }
```
Comment (sdanyliv) [inline Tests/Linq/UserTests/Issue1721Tests.cs]: I think we have to check here that `LastQuery` contains DataType(Precision) text for every type.

Comment (Corey-M) [reply Tests/Linq/UserTests/Issue1721Tests.cs]: You're right.  And while working on this I found an error that the test runner didn't throw.

**Comment by Corey-M** [comment]
Previous code was falling through to the default code when `Precision` is specified as the default value of `7` for all types.  Fixed that and added testing of generated SQL to ensure that the right values are created.
