### PR TITLE
Fix DynamicColumnInfo.GetCustomAttributes

### LINKED ISSUE #4079: Access EF Core shadow property problem
I have a model defined in EF Core database context. An entity has a shadow property and this couldn't be refactored by some reasons.

A shadow property defined like this:
```csharp
modelBuilder.Entity<Entry>(eb =>eb.Property<int?>(Consts.ShadowColumn));
```

Then I want to make a query translated by Linq2DB where data is filtered by this shadow property:
```csharp
var db = _db.CreateLinqToDBContext(); // Making Linq2DB context from the injected EF Core context
var data = await db.GetTable<Entry>()
    .Where(e => Sql.Property<int?>(e, Consts.ShadowColumn) != 10)
    .ToListAsyncLinqToDB();
```

However, it throws with the following exception:
```
An unhandled exception has occurred while executing the request.
      System.InvalidCastException: Unable to cast object of type 'System.Object[]' to type 'System.Attribute[]'.
         at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
         at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
         at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
         at LinqToDB.Extensions.AttributesExtensions.<>c.<GetInheritAttributes>b__4_0(ICustomAttributeProvider source)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Extensions.AttributesExtensions.GetInheritAttributes(ICustomAttributeProvider source)
         at LinqToDB.Extensions.AttributesExtensions.GetAttributesInternal[T](ICustomAttributeProvider source, Boolean inherit)
         at LinqToDB.Extensions.AttributesExtensions.<>c__7`1.<GetAttributes>b__7_0(ICustomAttributeProvider source)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Extensions.AttributesExtensions.GetAttributes[T](ICustomAttributeProvider source, Boolean inherit)
         at LinqToDB.Extensions.AttributesExtensions.GetAttribute[T](ICustomAttributeProvider source, Boolean inherit)
         at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes(Type type, MemberInfo memberInfo)
         at LinqToDB.Metadata.MetadataReader.<.ctor>b__8_1(Type type, ICustomAttributeProvider source)
         at LinqToDB.Metadata.MappingAttributesCache.<>c.<GetNoInheritMappingAttributes>b__9_0(Key key, Func`3 attributesGetter)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at LinqToDB.Metadata.MappingAttributesCache.GetNoInheritMappingAttributes(Key key)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
         at LinqToDB.Metadata.MetadataReader.GetAttributes[T](Type type, MemberInfo memberInfo)
         at LinqToDB.Mapping.MappingSchema.GetAllAttributes[T](Type type, MemberInfo memberInfo)
         at LinqToDB.Mapping.MappingSchema.<CreateAttributeCaches>b__51_0(Type sourceOwner, ICustomAttributeProvider source)
         at LinqToDB.Metadata.MappingAttributesCache.<>c.<GetNoInheritMappingAttributes>b__9_0(Key key, Func`3 attributesGetter)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at LinqToDB.Metadata.MappingAttributesCache.GetNoInheritMappingAttributes(Key key)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
         at LinqToDB.Mapping.MappingSchema.GetAttributes[T](Type type, MemberInfo memberInfo, Boolean forFirstConfiguration)
         at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, MemberInfo memberInfo)
         at LinqToDB.Extensions.MappingExtensions.GetExpressionAttribute(MemberInfo member, MappingSchema mappingSchema)
         at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.IsServerSideOnly(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeCompiledFind(CanBeCompiledContext context, Expression ex)
         at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.<>c.<GetCanBeCompiledVisitor>b__33_0(CanBeCompiledContext ctx, Expression e)
         at LinqToDB.Expressions.FindVisitor`1.Find(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeCompiled(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.CanBeCompiled(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTransformer(Expression e)
         at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<ConvertExpression>b__138_0(ExpressionBuilder ctx, Expression e)
         at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpression(Expression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTransformer(Expression e)
         at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<ConvertExpression>b__138_0(ExpressionBuilder ctx, Expression e)
         at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
         at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpression(Expression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
         at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
         at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
         at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
         at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
         at DistinctTestApp.Controllers.TestController.TryUntyped2() in C:\projects\DistinctTest\DistinctTestApp\Controllers\TestController.cs:line 132
         at lambda_method6(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arg
uments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Is there any way to access shadow properties defined in EF Core when a query is being processed by the Linq2DB?

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #4079

### CODE REVIEW

File: Source/LinqToDB/Mapping/DynamicColumnInfo.cs [hunk 1]
```diff
@@ -89,17 +89,15 @@ public override int GetHashCode()
 		public static bool operator !=(DynamicColumnInfo? a, DynamicColumnInfo? b)
 			=> !a?.Equals(b) ?? !ReferenceEquals(b, null);
 
-
 #pragma warning disable RS0030 // Do not used banned APIs
 		public override object[] GetCustomAttributes(bool inherit)
 #pragma warning restore RS0030 // Do not used banned APIs
 			=> Array<object>.Empty;
```
Comment (MaceWindu) [inline Source/LinqToDB/Mapping/DynamicColumnInfo.cs:95]: Method return value type not changed as this method never called by runtime

**Review by viceroypenguin — APPROVED** [review]
