### PR TITLE
Fixed aggregation case with complex Select.

### LINKED ISSUE #5256: [Regression 6.1.0] Invalid SQL Generated for Nested Sum Aggregations in Subquery
### Description

linq2db 6.1.0 generates invalid SQL when a query contains a nested subquery with grouped aggregations where `Sum()` is applied both inside the group selection and on the outer result set (Sum of Sums pattern).

The generated SQL incorrectly references columns outside of aggregate functions or the GROUP BY clause, resulting in the following SQL Server error:

```
Column '[TableName].[ColumnName]' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

This appears to be a regression in version 6.1.0, as the same query pattern has worked in 6.0.0-rc.2 and previous versions.

### Reproduction Steps

```csharp
var query =
    from product in db.Products
    select new {
        ProductId = product.Id,
        OnOrder = (
            from s in db.PurchaseOrderLineItems
            group s by s.Id into testGroup
            select testGroup.Sum(x => (decimal?)x.Quantity)
        ).Sum() ?? 0
    };

var result = await query.ToListAsync();
```

### Exception details

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Column 'PurchaseOrderLineItem.Quantity' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken) in /_/Source/LinqToDB/Data/DataConnection.Async.cs:line 696
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken) in /_/Source/LinqToDB/Data/DataConnection.Async.cs:line 696
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken) in /_/Source/LinqToDB/Data/DataConnection.Async.cs:line 745
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken) in /_/Source/LinqToDB/Data/DataConnection.Async.cs:line 745
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken) in /_/Source/LinqToDB/Data/DataConnection.QueryRunner.cs:line 691
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 548
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 600
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 601
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 218
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 218
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 218
   at LinqToDB.Async.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token) in /_/Source/LinqToDB/Async/AsyncExtensions.cs:line 281
   at ConsoleApp.Apps.TestWarehouseProductQuery.RunAsync() in C:\Users\shanek\source\repos\ZboxGlobal\HiveServer\ConsoleApp\Apps\TestWarehouseProductQuery.cs:line 34
   at ConsoleApp.Apps.TestWarehouseProductQuery.RunAsync() in C:\Users\shanek\source\repos\ZboxGlobal\HiveServer\ConsoleApp\Apps\TestWarehouseProductQuery.cs:line 35
   at ConsoleApp.Program.Main(String[] args) in C:\Users\shanek\source\repos\ZboxGlobal\HiveServer\ConsoleApp\Program.cs:line 44
   at ConsoleApp.Program.<Main>(String[] args)
ClientConnectionId:6c4927c1-b893-4bf7-ad8e-ed2db03d7069
Error Number:8120,State:1,Class:16
```

### Incorrectly generated SQL

```sql

SELECT
	[product_1].[Id],
	(
		SELECT
			SUM(SUM([t2].[Quantity]))
		FROM
			(
				SELECT
					[t1].[Quantity]
				FROM
					[PurchaseOrderLineItem] [t1]
				GROUP BY
					[t1].[Id]
			) [t2]
	)
FROM
	[Product] [product_1]
```

### Regression?

| Version | Query works as expected |
|-|-|
| 6.0.0-rc.2 | Yes |
| 6.0.0-rc.3 | Unknown |
| 6.0.0 | No |
| 6.1.0 | No |

### Workaround

Using `AsCte()` seems to be a workaround:

```csharp
var query =
    from product in db.Products
    select new {
        ProductId = product.Id,
        OnOrder = (
            from cte in (
                from s in db.PurchaseOrderLineItems
                group s by s.Id into testGroup
                select testGroup.Sum(x => (decimal?)x.Quantity)
            ).AsCte()
            select cte
        ).Sum() ?? 0
    };
var result = await query.ToListAsync();
```

```sql
WITH [CTE_1] ([OnOrder])
AS
(
	SELECT
		SUM([testGroup].[Quantity])
	FROM
		[PurchaseOrderLineItem] [testGroup]
	GROUP BY
		[testGroup].[Id]
)
SELECT
	[product_1].[Id],
	(
		SELECT
			SUM([t1].[OnOrder])
		FROM
			[CTE_1] [t1]
	)
FROM
	[Product] [product_1]
```

### Linq To DB version

6.1.0

### .NET version

.NET 8.0

### Database

Azure SQL Server Managed Instance

### Database provider

Microsoft.Data.SqlClient 6.1.0

### Operating system

Windows

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #5256

### CODE REVIEW

**Review by igor-tkachev — APPROVED** [review]

**Review by Shane32 — APPROVED** [review]

File: Tests/Linq/UserTests/Issue5256Tests.cs [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+						group s by s.Id into testGroup
+						select testGroup.Sum(x => (decimal?)x.Quantity)
+					).Sum() ?? 0
+				};
+
+			AssertQuery(query);
+		}
+
+		[ThrowsRequiresCorrelatedSubquery]
+		[ThrowsRequiredOuterJoins(TestProvName.AllMySql57, TestProvName.AllMariaDB, TestProvName.AllAccess, TestProvName.AllDB2)]
```
Comment (MaceWindu) [inline Tests/Linq/UserTests/Issue5256Tests.cs:71]: Not directly related so could be done later, but can we move providers to attribute as we do with ThrowsRequiresCorrelatedSubquery or it could vary? Also rename to `ThrowsRequires...`
