### PR TITLE
Fix temporary table drop statement for MySQL

### LINKED ISSUE #4439: DDL [drop table] causes MySql transactions to fail to roll back
### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Mapping;
using System.Diagnostics;

namespace Linq2dbTestMySqlTempTable.Tests
{
    [Table("TMP_MIN_TEMPORARY")]
    public partial class TMP_MIN_TEMPORARY
    {
        [Column(IsPrimaryKey = true, IsIdentity = true, CanBeNull = false)]
        public int IDX { get; set; }

        [Column(CanBeNull = false, Length = 80)]
        public string KEY_A { get; set; }
    }

    [Table("TEST_TB_A1")]
    public class TEST_TB_AA
    {
        [Column(IsPrimaryKey = true, IsIdentity = true, CanBeNull = false)]
        public int AID { get; set; }

        [Column(CanBeNull = false, Length = 80)]
        public string CODE_AA { get; set; }
    }

    [TestClass()]
    public class ProgramTests
    {
        [TestMethod()]
        public void TestMySqlTranTest()
        {
            using (var db = new MyDataConn())
            {
                db.CreateTable<TEST_TB_AA>(tableOptions: TableOptions.CreateIfNotExists);
            }
            var code = $"{DateTime.Now:HH:mm:ss.fffff}.{Guid.NewGuid():N}";
            using (var db = new MyDataConn())
            {
                try
                {
                    db.BeginTransaction();
                    db.Insert(new TEST_TB_AA() { CODE_AA = code });
                    using (var tempTB = db.CreateTempTable<TMP_MIN_TEMPORARY>(tableOptions: TableOptions.IsTemporary | TableOptions.CheckExistence))
                    {
                        Debug.WriteLine(db.LastQuery);
                    }
                    //expected: DROP TEMPORARY TABLE IF EXISTS `TMP_MIN_TEMPORARY`
                    //actual:             DROP TABLE IF EXISTS `TMP_MIN_TEMPORARY`
                    Debug.WriteLine(db.LastQuery);
                    db.Insert(new TEST_TB_AA() { CODE_AA = code });
                    throw new Exception("Need Call RollbackTransaction!");
                    db.CommitTransaction();
                }
                catch (Exception ex)
                {
                    db.RollbackTransaction();
                }
            }

            using (var db = new MyDataConn())
            {
                //DDL [drop table] causes MySql transactions to fail to roll back, and all DML statements in the context have been committed
                var exists = db.GetTable<TEST_TB_AA>().Any(x => x.CODE_AA == code);
                Assert.IsFalse(exists);
            }
        }


        [TestMethod()]
        public void TestDropTamporaryTable()
        {
            using (var db = new MyDataConn())
            {
                db.DropTable<TMP_MIN_TEMPORARY>(tableOptions: TableOptions.DropIfExists | TableOptions.IsTemporary);
                Assert.IsTrue(db.LastQuery.Contains(" TEMPORARY "), db.LastQuery);
            }
        }
    }
}
```

### Environment details

`Linq To DB` version: *5.4*

Database (with version): *MySql 8.0.16*

ADO.NET Provider (with version): *MySqlConnector 2.3.5*

Operating system: *any*

.NET Version: *.net6*

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #4439

### CODE REVIEW

File: Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs [hunk 1]
```diff
@@ -464,7 +464,48 @@ protected override void BuildTruncateTable(SqlTruncateTableStatement truncateTab
...
+			{
+				if (IsTemporaryTable(dropTable.Table.TableOptions))
+					command = "DROP TEMPORARY TABLE ";
+				else
+					throw new InvalidOperationException($"Incompatible table options '{dropTable.Table.TableOptions & TableOptions.IsTemporaryOptionSet}'");
+			}
+			else
+			{
+				command = "DROP TABLE ";
+			}
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:480]:
```suggestion
			var command = (dropTable.Table.TableOptions.IsTemporaryOptionSet(), IsTemporaryTable(dropTable.Table.TableOptions)) switch
			{
				(true, true) => "DROP TEMPORARY TABLE ",
				(true, _) => throw new InvalidOperationException($"Incompatible table options '{dropTable.Table.TableOptions & TableOptions.IsTemporaryOptionSet}'"),
				_ => "DROP TABLE ",
			};
```

File: Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs [hunk 2]
```diff
@@ -464,7 +464,48 @@ protected override void BuildTruncateTable(SqlTruncateTableStatement truncateTab
...
+					case TableOptions.IsTemporary | TableOptions.IsLocalTemporaryStructure                                     :
+					case TableOptions.IsTemporary | TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData :
+					case                                                                     TableOptions.IsLocalTemporaryData :
+					case                            TableOptions.IsLocalTemporaryStructure                                     :
+					case                            TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData :
+						return true;
+				}
+			}
+
+			return false;
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:508]:
```suggestion
			if (!tableOptions.IsTemporaryOptionSet())
				return false;
			
			return (tableOptions & TableOptions.IsTemporaryOptionSet) is
				TableOptions.IsTemporary                                                                              or
				TableOptions.IsTemporary |                                          TableOptions.IsLocalTemporaryData or
				TableOptions.IsTemporary | TableOptions.IsLocalTemporaryStructure                                     or
				TableOptions.IsTemporary | TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData or
				                                                                     TableOptions.IsLocalTemporaryData or
				                           TableOptions.IsLocalTemporaryStructure                                     or
				                           TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData;
			}

```

File: Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs [hunk 3]
```diff
@@ -520,20 +561,10 @@ protected override void BuildCreateTableCommand(SqlTable table)
...
-					case TableOptions.IsTemporary | TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData :
-					case                                                                     TableOptions.IsLocalTemporaryData :
-					case                            TableOptions.IsLocalTemporaryStructure                                     :
-					case                            TableOptions.IsLocalTemporaryStructure | TableOptions.IsLocalTemporaryData :
-						command = "CREATE TEMPORARY TABLE ";
-						break;
-					case var value :
-						throw new InvalidOperationException($"Incompatible table options '{value}'");
-				}
+				if (IsTemporaryTable(table.TableOptions))
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:564]: See previous comment

File: Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs (hunk 1 above)
Comment (viceroypenguin) [reply Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:480]: does it make sense to call `IsTemporaryOptionSet()` in the first branch _and_ inside of `IsTemporaryTable()`?

Comment (MaceWindu) [reply Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:480]: if we move exception to IsTemporaryTable, then no

Comment (viceroypenguin) [reply Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:480]: Since the code is the same in both places, that may make sense anyway:
```cs
private bool IsTemporaryTable()
{
  // check validity; throw if not valid, return true/false
}

var command = IsTemporaryTable() ? "DROP TEMPORARY TABLE " : "DROP TABLE ";
```

File: Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs [hunk 4]
```diff
@@ -464,7 +464,39 @@ protected override void BuildTruncateTable(SqlTruncateTableStatement truncateTab
...
+			if (dropTable.Table.TableOptions.HasDropIfExists())
+				StringBuilder.Append("IF EXISTS ");
+
+			BuildPhysicalTable(dropTable.Table!, null);
+			StringBuilder.AppendLine();
+		}
+
+		private static bool IsTemporaryTable(TableOptions tableOptions)
+		{
+			if (tableOptions.IsTemporaryOptionSet())
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs:480]: optional:
```cs
if (!tableOptions.IsTemporaryOptionsSet())
  return false;
var tempOptions = ...;
if (tempOptions is 
    IsTemporary or
    IsTemporary | IsLocalTemporaryData or
    ...)
{
    throw new InvalidOperationException(...);
}

return true;
```

**Review by viceroypenguin — APPROVED** [review]
