### PR TITLE
Various fixes and performance improvements.

### LINKED ISSUE #2288: Bit (bool) fields and result ms sql query with <>
Hello guys!
I have trouble with boolean fields and simple ! operator (or == false). In my C# code: _db.TableName.Any(x=>!x.BoooleanField) or _db.TableName.Any(x=>x.BoooleanField == false)
I expected to see it on the way out this : ... WHERE TableName.BooleanField **== 0**, but i see this: WHERE TableName.BooleanField **<>** 1. As a result my index in MS SQL does not work. 
Help me guys, please 8)

linq2db version: *2.9.8*
Database Server: *MS SQL 2016*
Database Provider: *SqlServer*
Operating system: *Windows 2016, Windows 10*
.NET Framework: *4.8*

### PR DESCRIPTION
**Pull request by sdanyliv**
In this PR

- Added logic for correct building predicates based on boolean values.
- Optimized SQL Query building performance.
- Added PostgreSQL extensions.
- Fixed many found issues.
- Added support arrays in PostgreSql.
- Added `FromSqlScalar` method.
- Improved type handling for generic extensions.
- Changed default types mapping for PosgreSQL: string -> text, TimeSpan -> interval
- Fixes #2288

Tasks TODO:

- [ ] Cover all new PostgreSQL functions with tests.

### CODE REVIEW

**Comment by Shane32** [comment]
FYI the new "BoolTest" and "BoolNotTest" that was added fails with SQL Server 2000.  Here's the produced SQL for `BoolTest` along with the SQL error message.  BoolNotTest fails for the same reason.
```sql
DECLARE @BoolValue_1 VarChar -- AnsiString
SET     @BoolValue_1 = N'Y'

SELECT
	[t].[Id],
	[t].[Value1],
	[t].[Value2],
	[t].[BoolValue]
FROM
	[ValueConversion] [t]
WHERE
	[t].[BoolValue] = @BoolValue_1
```
SQL Error:
```
The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.
```

File: Source/LinqToDB/DataExtensions.cs [hunk 1]
```diff
@@ -1356,6 +1356,44 @@ public override Expression PrepareForCache(Expression expression)
...
+		///         <code>context.FromSqlScalar&lt;Blogs&gt;($"UNNEST({array})");</code>
+		///     </para>
+		/// </summary>
+		/// <typeparam name="TEntity">Source query record type.</typeparam>
+		/// <param name="dataContext">Database connection context.</param>
+		/// <param name="sql"> The interpolated string representing a SQL query. </param>
+		/// <remarks>Additional parentheses will be added to the query if first word in raw query is 'SELECT', otherwise users are responsible to add them themselves.</remarks>
+		/// <returns> An <see cref="IQueryable{T}" /> representing the raw SQL query. </returns>
+		[StringFormatMethod("sql")]
+		public static IQueryable<TEntity> FromSqlScalar<TEntity>(
```
Comment (MaceWindu) [inline Source/LinqToDB/DataExtensions.cs:1381]: it is not clear why it has Scalar suffix

Comment (sdanyliv) [reply Source/LinqToDB/DataExtensions.cs:1381]: I decided to create new one because of ambiguous usage. `FromSql` also detects scalar selects but sometimes it doesn't, it needs mapping schema tuning.
