### PR TITLE
Remove sync APIs from remote context transport interface

### LINKED ISSUE #4618: [Refactoring] Remove or obsolete sync APIs from remote context
We should see if we can get rid of sync APIs or at least disable them using option.

As discussed below, it creates issues for WASM runtime and using blocking calls in newtwork calls is not a good idea in general.

### Discussed in https://github.com/linq2db/linq2db/discussions/4617

<div type='discussions-op-text'>

<sup>Originally posted by **vadimb7** September 15, 2024</sup>
Scenario: Blazor WASM hosted client application using LinqToDB.Remote.Grpc
Appears that when attempting to query from blazor wasm code, we run into an issue:

```
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
   at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[GrpcConfiguration,LinqServiceInfo](Method`2 method, String host, CallOptions options, GrpcConfiguration request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[GrpcConfiguration,LinqServiceInfo](GrpcConfiguration req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[GrpcConfiguration,LinqServiceInfo](GrpcConfiguration request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[GrpcConfiguration,LinqServiceInfo](Method`2 method, String host, CallOptions options, GrpcConfiguration request)
   at ProtoBuf.Grpc.Internal.Proxies.ClientBase.IGrpcLinqService_Proxy_0.IGrpcLinqService.GetInfo(GrpcConfiguration , CallContext )
   at LinqToDB.Remote.Grpc.GrpcLinqServiceClient.LinqToDB.Remote.ILinqService.GetInfo(String configuration)
   at LinqToDB.Remote.RemoteDataContextBase.**GetConfigurationInfo()**
   at LinqToDB.Remote.RemoteDataContextBase.**get_MappingSchema()**
   at LinqToDB.Linq.Table`1[[TestApp.Client.DataModels.TestData, TestApp.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InitTable(IDataContext dataContext, Expression expression, EntityDescriptor tableDescriptor)
   at LinqToDB.Linq.Table`1[[TestApp.Client.DataModels.TestData, TestApp.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(IDataContext dataContext)
   at LinqToDB.DataExtensions.GetTable[TestData](IDataContext dataContext)
   at TestApp.Client.DataModels.TestStuffDataContext.get_TestDatas() in C:\test\projects\TestApp\TestApp\TestApp.Client\TestStuffDatabase.generated.cs:line 36
   at TestApp.Client.Pages.Weather.<OnInitializedAsync>b__4_0() in C:\test\projects\TestApp\TestApp\TestApp.Client\Pages\Weather.razor:line 32
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at TestApp.Client.Pages.Weather.OnInitializedAsync() in C:\test\projects\TestApp\TestApp\TestApp.Client\Pages\Weather.razor:line 28
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```
Blazor attempts to run simple code:

```
var dc = new TestStuffDataContext();

var q = await ((from a in dc.TestData select a).ToListAsync());
```

Failure above is occuring when running the linq query. As obvious from the stack trace, 
As seen on the stack trace, MappingSchema accessor calls GetConfigurationInfo and subsequently attempts a synchronous call which then fails due to the nature of webasm. 

Please advise</div>

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #4618

- remove blocking transport calls
- make sure we preload info asynchronously

User still could access some context properties to trigger blocking calls, but there is nothing we can do here.

### CODE REVIEW

File: Source/LinqToDB/Internal/Async/SafeAwaiter.cs [hunk 1]
```diff
@@ -10,25 +11,101 @@ internal static class SafeAwaiter
...
+				var awaitable = Task.Run(async () => await task().ConfigureAwait(false));
+				awaitable.Wait();
 
-			return awaitable.Result;
+				return awaitable.Result;
+			}
+			catch (AggregateException ex) when (ex.InnerException != null)
+			{
+				throw ex.InnerException;
+			}
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Async/SafeAwaiter.cs]: If you do the following, you can avoid the wrapping try/catch. Also, you won't break the stacktrace in the inner exception by throwing it directly. (same for others in this file)
```suggestion
			// awaited ValueTask retrieved in Task.Run context as doing it in main thread could cause deadlock too
			var awaitable = Task.Run(async () => await task().ConfigureAwait(false));
			awaitable.Wait();
			return awaitable.GetAwaiter().GetResult();
```

**Comment by igor-tkachev** [comment]
Sync API does not work only for WASM. Should we remove it for everything else?

**Comment by MaceWindu** [comment]
there is no much sense to have both sync and async api. it is implementation details anyways

File: Source/LinqToDB/Internal/Async/SafeAwaiter.cs [hunk 2]
```diff
@@ -12,23 +13,47 @@ public static T Run<T>(Func<ValueTask<T>> task)
...
-			awaitable.Wait();
 
-			return awaitable.Result;
+			return awaitable.GetAwaiter().GetResult();
+		}
+
+		public static T Run<T>(Func<CancellationToken, ValueTask<T>> task)
+		{
+			// awaited ValueTask retrieved in Task.Run context as doing it in main thread could cause deadlock too
+			var awaitable = Task.Run(async () => await task(default).ConfigureAwait(false));
```
Comment (sdanyliv) [inline Source/LinqToDB/Internal/Async/SafeAwaiter.cs:23]: We have SafeAwaiter, isn't?

**Review by sdanyliv — APPROVED** [review]
