### PR TITLE
Fix race condition in mapping schema

### LINKED ISSUE #3312: Rare NullReferenceException in expression building
Hello.
After upgrading to 3.4.4 (error also appears in 3.5.1) from 3.2.3 a very rare NullReferenceException began to appear on simple queries.
It mostly appears in a project that runs very often - about every 2 minutes (some tasks). At this run frequency the error repeats constantly ~ 3 times per day. Also I once caught this exception in tests in another project with a different query and database.
I think it has something to do with initialization (sometimes things go wrong, for example, due to concurrency), because I have never seen this error in heavily loaded web services yet, only in frequently performed tasks.
Tried to reproduce issue in tests but no success.

```
Exception message: Object reference not set to an instance of an object.
Stack trace in tasks (repeated): at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Mapping.MappingSchema.ReduceDefaultValue(Expression expr)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(DbDataType from, DbDataType to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(Type from, Type to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.ColumnDescriptor.ApplyConversions(MappingSchema mappingSchema, Expression getterExpr, DbDataType dbDataType, IValueConverter valueConverter, Boolean includingEnum)
   at LinqToDB.Mapping.ColumnDescriptor.ApplyConversions(Expression getterExpr, DbDataType dbDataType, Boolean includingEnum)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildConstant(Expression expr, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSqlExpression(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildSetter|9_0(MemberExpression memberExpression, Expression expression, <>c__DisplayClass9_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildMemberInit|9_2(MemberInitExpression expression, Expression path, <>c__DisplayClass9_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetterWithContext(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext[] sequences)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext sequence)
   at LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.InsertAsync[T](ITable`1 target, Expression`1 setter, CancellationToken token)
   
Stack trace in tests (failed only once by now):
at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Mapping.MappingSchema.ReduceDefaultValue(Expression expr)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(DbDataType from, DbDataType to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(Type from, Type to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeConstantFind(Expression ex)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.<>c.<CanBeConstant>b__37_0(ExpressionTreeOptimizationContext ctx, Expression e)
   at LinqToDB.Expressions.FindVisitor`1.Find(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeConstant(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CanBeConstant(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTransformer(Expression e)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<ConvertExpression>b__136_0(ExpressionBuilder ctx, Expression e)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpression(Expression expression)
   at LinqToDB.Linq.Builder.MergeBuilder.InsertWhenNotMatched.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

### Steps to reproduce

```c#
[Table("ProcessingJobs")]
	public class ProcessingJob
	{
		[Column]
		[PrimaryKey]
		public string FileName { get; set; }

		[Column]
		public string HostName { get; set; }

		[Column]
		public string TypeName { get; set; }

		[Column]
		public DateTime? StartedOn { get; set; }


		[Column]
		public DateTime? FinishedOn { get; set; }
		[Column]
		public ProcessedFileStatus Status { get; set; }
	}

	public enum ProcessedFileStatus
	{
		Started, Finished
	}

	public class MyDataConnection : DataConnection
	{

		static MyDataConnection()
		{
			Configuration.ContinueOnCapturedContext = false;
			Configuration.OptimizeForSequentialAccess = true;
		}

		public MyDataConnection(string connectionString) : base(ProviderName.SqlServer, connectionString)
		{
		}

		protected override Task<DbDataReader> ExecuteReaderAsync(IDbCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken)
		{
			return base.ExecuteReaderAsync(command, commandBehavior | CommandBehavior.SequentialAccess, cancellationToken);
		}
	}

	public class Test
	{
		// code that fails in tasks
		public async Task Tasks()
		{
			var fileName = "somename";
			var typeName = "somename";

			using (var connection = new MyDataConnection("connectionstring"))
			{
				// fail here
				await connection.GetTable<ProcessingJob>().InsertAsync(() => new ProcessingJob()
				{
					FileName = fileName,
					FinishedOn = null,
					HostName = Environment.MachineName,
					StartedOn = DateTime.Now,
					Status = ProcessedFileStatus.Started,
					TypeName = typeName
				}).ConfigureAwait(false);
			}
		}

		// code that failed once in tests (code is more complex there, and I don't known which table it was, but it is close to this one)
		public async Task Tests()
		{
			using (var connection = new MyDataConnection("connectionstring"))
			{
				var data = new SomeTable
				{
					UpdatedOn = DateTime.Now,
					Version = 0
				};

				var query = connection.GetTable<SomeTable>().Merge()
					.Using(new[] { data })
					.OnTargetKey()
					.InsertWhenNotMatched();

				// fail here
				await query.MergeAsync().ConfigureAwait(false);
			}
		}
	}

	[Table("SomeTable")]
	public class SomeTable
	{
		[PrimaryKey]
		public Guid UserId { get; set; }

		[Column]
		public byte[] Data { get; set; }

		[Column]
		public DateTime? UpdatedOn { get; set; }

		[Column]
		public int Version { get; set; }
	}
```

### Environment details
linq2db version: 3.5.1
Database Server: Sql Server 2017
.NET Framework: net5.0

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #3312

TIL that `(x =?? new T())` code is not thread-safe and parallel thread could get uninitialized `x` instance.

### CODE REVIEW

**Comment by MaceWindu** [comment]
Probably expected behavior and documented somewhere in .net memory model documentation, but I still plan to look into it a bit more. We could have more code like that

File: Source/LinqToDB/Mapping/MappingSchema.cs [hunk 1]
```diff
@@ -805,11 +807,10 @@ static bool Simplify(ref DbDataType type)
 
 		Expression ReduceDefaultValue(Expression expr)
 		{
-			return (_reduceDefaultValueTransformer ??= TransformVisitor<MappingSchema>.Create(this, static (ctx, e) => ctx.ReduceDefaultValueTransformer(e)))
-				.Transform(expr);
```
Comment (MaceWindu) [inline Source/LinqToDB/Mapping/MappingSchema.cs:809]: 1. here first thread allocates visitor (and initialize it's fields in constructor). Second thread receives visitor instance and call Transform

Comment (MaceWindu) [reply Source/LinqToDB/Mapping/MappingSchema.cs:809]: 2. [here](https://github.com/linq2db/linq2db/blob/677bb0e08db9acb225a546192e0b4f531d0070a7/Source/LinqToDB/Expressions/ExpressionVisitors/TransformVisitor.cs#L51) second thread fails, because both `_staticFunc` and `_func` are `null` which is "impossible" as one of them set by constructor

**Comment by jods4** [comment]
@MaceWindu 
> Probably expected behavior and documented somewhere in .net memory model documentation, but I still plan to look into it a bit more. We could have more code like that

Talk to me about it on slack if you want to. It's a topic I know rather well and it's difficult to find good, accurate information on the net.

Rule of thumb is that unless you're sure that something is documented as thread-safe, you should never assume it is. Some stuff could be really surprising (did you know `long` writes are not guaranteed to be atomic even on x64?).
If you're writing concurrent code it's generally safer to stick to simple locks, no clever tricks.

The simplest thing to do if you don't want to initialize a rarely used expensive field in ctor is to rely on .net `Lazy<T>`.
You may think that `Lazy<T>` is trivial but it's not, there's a fair amount of knowledge hidden in there.

`x ??= new X()` is not thread-safe in several respects:

1. The read/compare to null/write are not atomic at all. 
So several threads may see the `null` value, create multiple `X()` concurrently, and overwrite each other in `x` (so one thread may see a `X` instance that later is _not_  `x` anymore.
All these races may be fine or not depending on what `x` does. `Lazy<T>` lets you choose between different policies to control how `X` is created. If you want to write lock-less code, this is where `CompareExchange` usually comes into play.

2. Read/writes in memory can be reordered, meaning another thread can see the reference written in `x` _before_ fields of `X` have been initialized. Uninitialized data means bugs.
The tool to control this is to use _acquire_ and _release_ reads and writes.  There are multiple APIs for that in .net but the simplest is to mark `x` as `volatile`.

I hope that gives you some research pointers, or just hit me in chat.

**Comment by MaceWindu** [comment]
NOW it's strange...
