### PR TITLE
Fix for #3432. Localized bug with Outer Apply.

### LINKED ISSUE #3432: LINQ Any translated differently from v2
### Discussed in https://github.com/linq2db/linq2db/discussions/3429

<div type='discussions-op-text'>

<sup>Originally posted by **hkarask** February 17, 2022</sup>
Hi all,

I'm trying to bump the `linq2sql` version in an older codebase, from `1.10.2` to `2.0.0` and noticed that `LINQ` `Any` gets translated a bit differently:

Given a contrived LINQ statement:

```csharp
var query =
    from task in con.GetTable<Task>()
    from party in con.GetTable<Party>()
        .Where(p => task.AdminPartyId == p.Id ||
                    con.GetTable<PartyAccess>().Any(pa => pa.PartyId == p.Id && pa.Role == Roles.Admin)
        ).DefaultIfEmpty()
...
```

I'm seeing different SQL between versions 1 and 2

### v 1.10.2
```sql
SELECT
 	t.Description,
 	p.Name
 FROM
 	Task t
 		LEFT JOIN Party p ON t.AdminPartyId = p.Id OR EXISTS(
 			SELECT
 				*
 			FROM
 				PartyAccess pa
 			WHERE
 				pa.PartyId = p.Id AND pa.Role = 'Admin'
 		)
```
### v 2.0.0
```sql
SELECT
 	j.Description,
 	t2.Name
 FROM
 	Task t
 		LEFT JOIN (
 			SELECT
 				p.Name,
 				p.Id
 			FROM
 				Party p
 			WHERE
 				(EXISTS(
 					SELECT
 						*
 					FROM
 						PartyAccess pa
 					WHERE
 						pa.PartyId = p.Id AND pa.Role = 'Admin'
 				))
 		) t2 ON t.AdminPartyId = t2.Id
```

There's now a full sub-query instead of join a level filter. This is causing a full table scan for some reason (using MySql 5.6). Is there a way to revert back to the old behaviour?

## 

### Environment details
linq2db version: `1.10.2` & `2.0.0`
Database Server: `MySql 5.6`
Database Provider: `MySql.Data 8.0.25`
.NET Framework: `.NET 4.8`

Thanks!
</div>

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #3432

Note that OUTER APPLY will be removed only if `Configuration.Linq.PreferApply = false`

### CODE REVIEW

File: Tests/Linq/UserTests/Issue3432Tests.cs [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+		[Table]
+		public class PartyAccess
+		{
+			[Column] public int     PartyId { get; set; }
+			[Column] public string? Role    { get; set; }
+		}
+
+		[Test]
+		public void OuterApplyOptimization([IncludeDataSources(TestProvName.AllSqlServer)] string context, [Values]bool preferApply)
```
Comment (MaceWindu) [inline Tests/Linq/UserTests/Issue3432Tests.cs:34]: could we have mysql tests too?

Comment (sdanyliv) [reply Tests/Linq/UserTests/Issue3432Tests.cs:34]: Well, it needs LATERAL check. Just simplified.

**Review by viceroypenguin — COMMENTED** [review]
I don't see where `PreferApply` is actually used by the query system at all? I only see the declaration in Query.cs, and a change in SelectQueryOptimizer.cs that does not rely on that value.

**Comment by sdanyliv** [comment]
`PreferApply` is used when we are trying to convert OUTER APPLY to LEFT JOIN and only in specific cases. Bug was that convert algorithm almost never reached point which checks this flag.

**Review by MaceWindu — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]
