### PR TITLE
Fixed empty values selection for type-specific operations

### LINKED ISSUE #5147: Empty Query does not cast columns as data types which breaks some usages
### Description

When creating an empty query with `Enumerable.Empty<TEntity>().AsQueryable(db)`, the query that is generated is something like
```sql
SELECT NULL Prop1, NULL Prop2, NULL Prop3 WHERE 1=0
```
The issue with this is that it's not usable for type-specific operations, like SUM, AVG, etc.
It would be good if these selected properties could be cast as their respective scalar types, which would allow them to produce valid SQL when they're used in the place of a table.
```sql
SELECT CAST(NULL AS INT) Prop1, CAST(NULL AS NVARCHAR(200)) Prop2, CAST(NULL AS MONEY) Prop3 WHERE 1=0
```

### Reproduction Steps

```csharp
await using var db = new DataConnection(options);

await db.DropTableAsync<TestEntity>(tableOptions: TableOptions.DropIfExists);
await db.DropTableAsync<OtherTestEntity>(tableOptions: TableOptions.DropIfExists);
await db.CreateTableAsync<TestEntity>();
await db.CreateTableAsync<OtherTestEntity>();

var emptyQuery = Enumerable.Empty<TestEntity>().AsQueryable(db);

var testEntities = await emptyQuery
    .GroupBy(entity => new { entity.Prop1, entity.Prop2, entity.Value })
    .Select(group => new
    {
        Prop1 = group.Key.Prop1,
        Prop2 = group.Key.Prop2,
        Value = group.Sum(entity => entity.Value)
    })
    .ToListAsync();


// Helper classes
public class TestEntity
{
    public int Prop1 { get; set; }
    public int Prop2 { get; set; }
    public decimal Value { get; set; }
}
```

### Exception details

```
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Operand data type NULL is invalid for sum operator.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Async.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Regression?

_No response_

### Linq To DB version

5.4.1, 6.0.0-rc3

### .NET version

8

### Database

SQL Server 2019

### Database provider

System.Data.SqlClient

### Operating system

_No response_

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by AidenFuller**
Fixes #5147

### CODE REVIEW

File: Tests/Linq/Linq/EnumerableSourceTests.cs [hunk 1]
```diff
@@ -830,6 +830,26 @@ from t in table
 					table.GetCacheMissCount().ShouldBe(cacheMiss);
 			}
 		}
+		
+		[Test]
+		public void EmptyValuesWithTypeSpecificUsage([DataSources(TestProvName.AllClickHouse, TestProvName.AllAccess, ProviderName.DB2, TestProvName.AllSybase, TestProvName.AllSybase, TestProvName.AllInformix)] string context, [Values(1, 2)] int iteration)
```
Comment (AidenFuller) [inline Tests/Linq/Linq/EnumerableSourceTests.cs]: Not 100% sure if this is the right place to put this test, nor if the name of the test is acceptable. This definitely covers the issue I was seeing though, so tried to make it consistent given the fact that the test above this already covers the baseline functionality

Comment (sdanyliv) [reply Tests/Linq/Linq/EnumerableSourceTests.cs]: Looks good.

**Comment by viceroypenguin** [comment]
@AidenFuller failing tests; ensure the failing tests are not affected by your change

**Comment by AidenFuller** [comment]
@viceroypenguin looks like they are related to these changes, I'll have a look in the morning unless one of you guys spot a quick fix for it and end up doing it yourself in the meantime

**Comment by AidenFuller** [comment]
@viceroypenguin I could be wrong, but I feel like this is actually an issue with the specific test that's failing ( #5057 / #5063 ). Should the TenderId scalar type have an underlying DataType defined? Adding `ms.SetDataType(typeof(TenderId), DataType.Guid)` is fixing the issue for me locally, but I'm not sure if this is correct and whether it's expected that all scalar types are should have an underlying data type

Edit: worst case is that we just revert to the existing behaviour only for properties/columns whose data types are undefined, but that feels like it could be confusing from an implementation perspective if things go wrong and you end up with a SQL error.

**Comment by AidenFuller** [comment]
I've just updated the problematic test case to include the data type, as the more I look at it, the more I think it's definitely the right solution, and not that the functionality itself is broken. Let me know if there's a reason why this is not the case though.

**Comment by viceroypenguin** [comment]
@AidenFuller based on <https://github.com/timbze/Linq2Db4539/blob/master/TenderId.cs>, that is not the correct solution. the test needs to reflect the code that actually worked in 5.4.1 and should continue to work. if you look at the test code that is provided, it does not provide such a `SetDataType()`. You will need to address this without changing the test code.

**Comment by AidenFuller** [comment]
@viceroypenguin Fair enough. I missed the specific reason as to why the empty values was being used for SQLite in the way that it is in that test, and knowing that extra context now, it makes sense that the existing behaviour should work. I believe I've got a fix, just not sure if it matches the convention, because I'm not totally content that it's clean. Perhaps one of you have a suggestion for how it could be tweaked if you feel it's necessary.

File: Source/LinqToDB/Internal/DataProvider/SQLite/SQLiteSqlBuilder.cs [hunk 2]
```diff
@@ -219,7 +219,7 @@ protected override void BuildSqlValuesTable(SqlValuesTable valuesTable, string a
 
 				StringBuilder.AppendLine();
 				AppendIndent();
-				BuildEmptyValues(valuesTable);
+				BuildEmptyValues(valuesTable, false);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/DataProvider/SQLite/SQLiteSqlBuilder.cs]:
```suggestion
				BuildEmptyValues(valuesTable, useTypedExpression: false);
```

**Comment by AidenFuller** [comment]
Am I right to assume those CI pipeline failures are the result of an external issue (transient or otherwise) and not based on this PR's content?

**Comment by MaceWindu** [comment]
Only test-all pipeline configured for external prs

File: Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLFactory.cs [hunk 3]
```diff
@@ -23,7 +23,7 @@ public override IDataProvider GetDataProvider(IEnumerable<NamedValue> attributes
 				_               => PostgreSQLVersion.AutoDetect,
 			};
 
-			return PostgreSQLTools.GetDataProvider();
+			return PostgreSQLTools.GetDataProvider(version);
```
Comment (AidenFuller) [inline Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLFactory.cs:26]: @sdanyliv just an FYI, I boyscouted this change as part of this PR which I guess was intended to be included in #4676. Not sure if you care whether it's in a separate PR for scoping purposes.

File: Tests/Linq/Linq/EnumerableSourceTests.cs (hunk 1 above)
Comment (viceroypenguin) [inline Tests/Linq/Linq/EnumerableSourceTests.cs]:
```suggestion
		public void EmptyValuesWithTypeSpecificUsage([DataSources(TestProvName.AllClickHouse, TestProvName.AllAccess, ProviderName.DB2, TestProvName.AllSybase, TestProvName.AllInformix)] string context, [Values(1, 2)] int iteration)
```

**Comment by MaceWindu** [comment]
Thanks!
