### PR TITLE
Fix LEFT JOIN with aggregate value in condition.

### LINKED ISSUE #4800: Regression: wrong table name is specified
After updating version 3.x to 6.x I have an issue with query, it is big, I cannot simplify it yet, but maybe it is not needed.

Scroll to this row: 
```
MIN(`t1`.`TesteeId`) as `MIN_1`, -- Bug, must be MIN(`elements_1`.`TesteeId`) as `MIN_1`
```

Entire query:
```sql
--  MariaDB.10.MySqlConnector MySql
SET @clubId = 0x123;
SET @Type = 54285;
SET @DateMin = '2020-01-01';
SET @DateMax = '2020-12-31';
SET @Item1 = 0;
SET @Item2 = 0;
SET @Item1_1 = 23;
SET @Item2_1 = 59;
SET @PercentMin = 0;
SET @PercentMax = 5;
SET @DistanceMin = 0;
SET @DistanceMax = 500;
SET @PlacementMin = 1;
SET @PlacementMax = 20;
SET @QualityMin = 1;
SET @QualityMax = 6;
SET @RelevanceMin = 1;
SET @RelevanceMax = 6;
SET @AirTempMin = -30;
SET @AirTempMax = 15;
SET @AirHumidityMin = 0;
SET @AirHumidityMax = 100;
SET @InsolationMin = 0;
SET @InsolationMax = 100;
SET @ClarityMin = 0;
SET @ClarityMax = 1000;
SET @WindMin = 0;
SET @WindMax = 20;
SET @SnowTempMin = -30;
SET @SnowTempMax = 0;
SET @SnowHumidityMin = 0;
SET @SnowHumidityMax = 100;

SELECT
	`t1`.`Token`,
	`t1`.`MIN_1`,
	`account_1`.`Name`,
	`account_1`.`Surname`,
	`outfit_2`.`AccountId`,
	`outfit_2`.`Reference`,
	`structure_1`.`Name`,
	`t1`.`StructureId`,
	`sole_1`.`Name`,
	`t1`.`SoleId`,
	`t1`.`SUM_1`,
	`t1`.`COUNT_1`,
	CAST(`t1`.`SUM_1` AS FLOAT) / `t1`.`COUNT_1`,
	`t1`.`AVG_1`,
	`t1`.`AVG_2`
FROM
	(
		SELECT
			MIN(`elements_1`.`StructureId`) as `StructureId`,
			MIN(`elements_1`.`SoleId`) as `SoleId`,
			`elements_1`.`Token`,
			MIN(`t1`.`TesteeId`) as `MIN_1`, -- Bug, must be MIN(`elements_1`.`TesteeId`) as `MIN_1`,
			SUM(`elements_1`.`Win`) as `SUM_1`,
			COUNT(*) as `COUNT_1`,
			AVG(`elements_1`.`Distance`) as `AVG_1`,
			AVG(`elements_1`.`Placement`) as `AVG_2`,
			`elements_1`.`TesteeId`
		FROM
			(
				SELECT
					`elements`.`Token`,
					`elements`.`TesteeId`,
					`elements`.`StructureId`,
					`elements`.`SoleId`,
					CASE
						WHEN `elements`.`Placement` = 1 THEN 1
						ELSE 0
					END as `Win`,
					`elements`.`Distance`,
					`elements`.`Placement`
				FROM
					(
						SELECT
							`item_1`.`ClubId`,
							`item_1`.`Type` as `Type_1`,
							`item_1`.`Mode` as `Mode_1`,
							`item_1`.`Time` as `Time_1`,
							Extract(hour from `item_1`.`Time`) as `Hour_1`,
							Extract(minute from `item_1`.`Time`) as `Minute_1`,
							`item_1`.`BranchId`,
							`item_1`.`PlaceId`,
							`item_1`.`Difference`,
							`item_1`.`Distance`,
							`item_1`.`Placement`,
							`item_1`.`Quality`,
							`item_1`.`Relevance`,
							`item_1`.`AirTemp`,
							`item_1`.`AirHumidity`,
							`item_1`.`Insolation`,
							`item_1`.`Clarity`,
							`item_1`.`Wind`,
							`item_1`.`SnowTemp`,
							`item_1`.`SnowHumidity`,
							`item_1`.`ArtificialTypeId`,
							`item_1`.`NaturalTypeId`,
							`item_1`.`TextureId`,
							`item_1`.`HardnessId`,
							`item_1`.`TrackConsistencyId`,
							`item_1`.`PrecipitationTypeId`,
							`item_1`.`CloudTypeId`,
							`item_1`.`Token`,
							`item_1`.`TesteeId`,
							`item_1`.`TestId`,
							`item_1`.`StructureId`,
							`item_1`.`SoleId`
						FROM
							`TesteeCoverage` `item_1`
								INNER JOIN `Test` `test_1` ON `item_1`.`TestId` = `test_1`.`Id`
								LEFT JOIN `Executant` `executant_1` ON `test_1`.`Id` = `executant_1`.`TestId`
								LEFT JOIN `Testee` `testee_1` ON `item_1`.`TesteeId` = `testee_1`.`Id`
								LEFT JOIN `Outfit` `outfit_1` ON `testee_1`.`WorkblankId` = `outfit_1`.`WorkblankId`
						WHERE
							`item_1`.`Status` = 14650
					) `elements`
				WHERE
					`elements`.`ClubId` = @clubId AND
					`elements`.`Type_1` = @Type AND
					`elements`.`Mode_1` IN (56180) AND
					@DateMin <= `elements`.`Time_1` AND
					@DateMax >= `elements`.`Time_1` AND
					(@Item1 < `elements`.`Hour_1` OR @Item1 = `elements`.`Hour_1` AND @Item2 <= `elements`.`Minute_1`) AND
					(@Item1_1 > `elements`.`Hour_1` OR @Item1_1 = `elements`.`Hour_1` AND @Item2_1 >= `elements`.`Minute_1`) AND
					@PercentMin <= `elements`.`Difference` AND
					@PercentMax >= `elements`.`Difference` AND
					(`elements`.`Mode_1` <> 56180 OR @DistanceMin <= `elements`.`Distance`) AND
					(`elements`.`Mode_1` <> 56180 OR @DistanceMax >= `elements`.`Distance`) AND
					@PlacementMin <= `elements`.`Placement` AND
					@PlacementMax >= `elements`.`Placement` AND
					@QualityMin <= `elements`.`Quality` AND
					@QualityMax >= `elements`.`Quality` AND
					@RelevanceMin <= `elements`.`Relevance` AND
					@RelevanceMax >= `elements`.`Relevance` AND
					@AirTempMin <= `elements`.`AirTemp` AND
					@AirTempMax >= `elements`.`AirTemp` AND
					@AirHumidityMin <= `elements`.`AirHumidity` AND
					@AirHumidityMax >= `elements`.`AirHumidity` AND
					@InsolationMin <= `elements`.`Insolation` AND
					@InsolationMax >= `elements`.`Insolation` AND
					@ClarityMin <= `elements`.`Clarity` AND
					@ClarityMax >= `elements`.`Clarity` AND
					@WindMin <= `elements`.`Wind` AND
					@WindMax >= `elements`.`Wind` AND
					@SnowTempMin <= `elements`.`SnowTemp` AND
					@SnowTempMax >= `elements`.`SnowTemp` AND
					@SnowHumidityMin <= `elements`.`SnowHumidity` AND
					@SnowHumidityMax >= `elements`.`SnowHumidity`
				GROUP BY
					`elements`.`Token`,
					`elements`.`TesteeId`,
					`elements`.`TestId`,
					`elements`.`StructureId`,
					`elements`.`SoleId`,
					`elements`.`Distance`,
					`elements`.`Placement`
			) `elements_1`
		GROUP BY
			`elements_1`.`Token`
	) `t1`
		LEFT JOIN `Testee` `testee_2` ON MIN(`t1`.`TesteeId`) = `testee_2`.`Id`
		LEFT JOIN `Outfit` `outfit_2` ON `testee_2`.`WorkblankId` = `outfit_2`.`WorkblankId`
		LEFT JOIN `Account` `account_1` ON `outfit_2`.`AccountId` = `account_1`.`Id`
		LEFT JOIN `Structure` `structure_1` ON `t1`.`StructureId` = `structure_1`.`Id`
		LEFT JOIN `Sole` `sole_1` ON `t1`.`SoleId` = `sole_1`.`Id`
```

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #4800

Additional fixes:

- Change default mapping for `System.Decimal` from `DECIMAL` to `DECIMAL(18,10)` for DB2, Acess, SQLCE, SqlServer, ASE to avoid issues with db-specific type defaults
- [SQLCE] fix overflow exception on reading decimal value with long decimal part
- [SQLCE] fix issue when MONEY type name could include precision/scale
- [MSSQL, ASE] fix issue when MONEY and SMALLMONEY type names could include precision/scale
- [SQL Server] fix issue when  decimal parameter could use smaller precision/scale than parameter value
- fix expression type precision/scale infer

### CODE REVIEW

File: Source/LinqToDB/Linq/Builder/BuildProxyBase.cs [hunk 1]
```diff
@@ -63,37 +78,35 @@ public override Expression    MakeExpression(Expression path,  ProjectFlags flag
...
 
-			if (ExpressionEqualityComparer.Instance.Equals(translated, currentExpression))
-				return path;
+			if (!(flags.IsExpression() && !flags.IsForSetProjection())) 
+			{
+				if (ExpressionEqualityComparer.Instance.Equals(translated, currentExpression))
+					return path;
 
-			var handled = ProcessTranslated(translated, ownersPath);
+				if (translated is ContextRefExpression contextRef && contextRef.BuildContext.Equals(OwnerContext))
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/BuildProxyBase.cs:86]:
```suggestion
				if (translated is ContextRefExpression { BuildContext: var buildContext } && buildContext.Equals(OwnerContext))
```

**Review by viceroypenguin — APPROVED** [review]

**Review by MaceWindu — APPROVED** [review]

File: Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs [hunk 2]
```diff
@@ -27,19 +29,23 @@ private SqlCeProviderAdapter(
 
 			Action<DbParameter, SqlDbType>   dbTypeSetter,
 			Func  <DbParameter, SqlDbType>   dbTypeGetter,
-			Func  <string,      SqlCeEngine> sqlCeEngineCreator)
+			Func  <string,      SqlCeEngine> sqlCeEngineCreator,
+
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs:33]:
```suggestion
```

File: Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs [hunk 3]
```diff
@@ -101,13 +109,31 @@ public static SqlCeProviderAdapter GetInstance()
...
 			}
 
 			return _instance;
 		}
 
+		static decimal ConvertToDecimal(SqlDecimal sqlDecimal)
+		{
+			// workaround bug in GetDecimal implementation not trimming scale value but throwing overflow exception
+
+			// trim trailing scale numbers, will throw for out-of-range values
```
Comment (viceroypenguin) [inline Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs:124]: There is no way to check for this without throwing? Or is that a separate PR?

File: Source/LinqToDB/Linq/Builder/SequenceHelper.cs [hunk 4]
```diff
@@ -879,9 +890,16 @@ public static Expression UnwrapDefaultIfEmpty(Expression expression)
 		{
 			if (expression is SqlDefaultIfEmptyExpression defaultIfEmptyExpression)
 				return UnwrapDefaultIfEmpty(defaultIfEmptyExpression.InnerExpression);
+
 			return expression;
 		}
 
+		public static Expression UnwrapProxy(Expression expression)
+		{
+			if (expression is ContextRefExpression contextRefExpression && contextRefExpression.BuildContext is IBuildProxy proxy)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/SequenceHelper.cs:899]:
```suggestion
			if (expression is ContextRefExpression { BuildContext: IBuildProxy proxy })
```

**Review by viceroypenguin — APPROVED** [review]

File: Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs (hunk 3 above)
Comment (MaceWindu) [reply Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs:124]: I'm not excited to copy all this code https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs#L216-L260

Comment (viceroypenguin) [reply Source/LinqToDB/DataProvider/SqlCe/SqlCeProviderAdapter.cs:124]: Fair enough. Didn't realize that it ultimately threw in external library code

**Review by viceroypenguin — APPROVED** [review]
