### PR TITLE
Fix primary key detection logic for SQLite. Fixes #5014.

### LINKED ISSUE #5014: `ColumnModel.Metadata.[IsDiscriminator,IsIdentity,IsPrimaryKey]` are `false` for Primary Keys when using SQLite
### Description

When using scaffolding interceptor class (`public sealed class Interceptor : ScaffoldInterceptors`) and going through `EntityModel.Columns` in `public override void PreprocessEntity(ITypeParser typeParser, EntityModel entityModel)`, columns that have Primary Key index in database don't have `.Metadata.IsPrimaryKey` `.Metadata.IsIdentity` nor `.Metadata.IsDiscriminator` set to `true`.

It seems to be SQLite-specific issue as I have not observed similar behavior with PostgreSQL nor with MariaDB/MySQL.

### Reproduction Steps

Create SQLite database with a table that has primary key column.
Create Scaffolding interceptor that goes through entity's columns using method `public override void PreprocessEntity(ITypeParser typeParser, EntityModel entityModel)`.
Observe that the following linq provides always `false` value:
`entityModel.Columns.Any(x => x.Metadata.IsIdentity || x.Metadata.IsPrimaryKey || x.Metadata.IsDiscriminator);`

### Error details

No error, just wrong values in `Metadata` object.

### Regression?

_No response_

### Linq To DB CLI version

5.4.1, 6.0.0-preview.4, latest nuget from main branch build

### .NET version

8.0

### Database

SQLite

### Operating system

Linux

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by Seramis**
- Fix primary key detection for SQLite schema provider
- Add test case for Issue #5014 with proper primary key validation
- Improved consistency for `TableID` value generation

### CODE REVIEW

File: Source/LinqToDB/Internal/DataProvider/SQLite/SQLiteSchemaProvider.cs [hunk 1]
```diff
@@ -77,23 +77,47 @@ protected override IReadOnlyCollection<PrimaryKeyInfo> GetPrimaryKeys(DataConnec
...
+						Ordinal        = pk.Field<int>   ("ORDINAL_POSITION"),
+					}
+				)
+			;
+
+			// Return distinct primary keys, prefer index-based over column-based
+			return indexedPrimaryKeys.Concat(colPrimaryKeys)
+				.GroupBy(
+					x => new { x.TableID, x.ColumnName },
+					(_, x) => x.First() // GroupBy guarantees the ordering of the source sequence
```
Comment (Seramis) [inline Source/LinqToDB/Internal/DataProvider/SQLite/SQLiteSchemaProvider.cs:118]: Just as a comment - `GroupBy` guarantees the ordering by documentation, while `DistinctBy` is not guaranteeing item order by documentation. The implementation of `DistinctBy` does provide stable order of items, but as it is not documented, I chose to go with `GroupBy` that documents this guarantee.

**Review by MaceWindu — APPROVED** [review]
