### PR TITLE
Address Query Construction Bug

### LINKED ISSUE #4337: Query does not work after Update from Linq2db 5.2.2 to 5.3.0 (or newer)
It's a very complex query, I create a reduced test case here.

It does not work in Sqlite and MsSql

Exception:

        LinqToDB.Linq.LinqException: ''<>h__TransparentIdentifier12.<>h__TransparentIdentifier11.<>h__TransparentIdentifier10.<>h__TransparentIdentifier9.<>h__TransparentIdentifier8.c1.Id' cannot be converted to SQL.'

image

### PR DESCRIPTION
**Pull request by jogibear9988**
Fixes #4337

### CODE REVIEW

**Comment by MaceWindu** [comment]
still fails with new parser
```sql
System.InvalidOperationException : Element: 't100[91].Id' has unknown source.
-----------------------------------------
In Statement:
-----------------------------------------
(89) SELECT 
	*
FROM (
		(73) SELECT 
			*
		FROM (
				(57) SELECT 
					t57[58].ResourceID = t70[57].ResourceID
				FROM (
						(38) SELECT 
							t38[49].Id = t54[48].Id
						FROM (
								(21) SELECT 
									t21[29].Id = t16[28].Id
								FROM (
										(16) SELECT 
											t16[5].MaterialID = t10[4].MaterialID,
											t16[28].Id        = t10[27].Id
										FROM (
												(10) SELECT 
													t10[1].AisleID    = t11.AisleID,
													t10[4].MaterialID = t11.MaterialID,
													t10[27].Id        = t11.Id
												FROM [ChannelDTO(11)] as t11 (<none>)
											) as t10 (c)
												INNER JOIN (
													(18) SELECT 
														t18[3].Id = t13[2].Id
													FROM (
															(13) SELECT 
																t13[2].Id = t14.Id
															FROM [AisleDTO(14)] as t14 (<none>)
														) as t13 (a)
												) as t18 (<none>) ON ([UID:65](t10[1].AisleID) = (t18[3].Id))
									) as t16 (<none>)
										OUTER APPLY (
											(35) SELECT 
												*
											FROM (
													(33) SELECT 
														t33[17].Id                    = t30[7].Id,
														t33[18].MaterialNumber        = t30[8].MaterialNumber?,
														t33[19].MaterialDescription_1 = t30[9].MaterialDescription_1?,
														t33[20].MaterialDescription_2 = t30[10].MaterialDescription_2?,
														t33[21].MaterialDescription_3 = t30[11].MaterialDescription_3?,
														t33[22].CategoryABC           = t30[12].CategoryABC?,
														t33[23].CategoryCustoms       = t30[13].CategoryCustoms?,
														t33[24].CategoryDimensions    = t30[14].CategoryDimensions?,
														t33[25].CategoryQuality       = t30[15].CategoryQuality?,
														t33[26].CategoryTemperature   = t30[16].CategoryTemperature?
													FROM (
															(30) SELECT 
																t30[7].Id                     = t31.Id,
																t30[8].MaterialNumber         = t31.MaterialNumber?,
																t30[9].MaterialDescription_1  = t31.MaterialDescription_1?,
																t30[10].MaterialDescription_2 = t31.MaterialDescription_2?,
																t30[11].MaterialDescription_3 = t31.MaterialDescription_3?,
																t30[12].CategoryABC           = t31.CategoryABC?,
																t30[13].CategoryCustoms       = t31.CategoryCustoms?,
																t30[14].CategoryDimensions    = t31.CategoryDimensions?,
																t30[15].CategoryQuality       = t31.CategoryQuality?,
																t30[16].CategoryTemperature   = t31.CategoryTemperature?
															FROM [MaterialDTO(31)] as t31 (<none>)
														) as t30 (m)
													WHERE
														(([UID:87](t16[5].MaterialID) = (t30[7].Id)))
												) as t33 (m)
										) as t35 (m) ON 
							) as t21 (<none>)
								OUTER APPLY (
									(54) SELECT 
										t54[48].Id = t51[40].Id
									FROM (
											(51) SELECT 
												t51[40].Id              = t48[34].Id,
												t51[41].ChannelID       = t48[32].ChannelID,
												t51[42].Name            = t48[35].Name?,
												t51[43].Status          = t48[36].Status,
												t51[44].AisleNumber     = t48[37].AisleNumber,
												t51[45].CategoryABC     = t48[38].CategoryABC?,
												t51[46].HeightClass     = t48[39].HeightClass,
												t51[47].DepthCoordinate = t48[33].DepthCoordinate
											FROM (
													(48) SELECT 
														t48[32].ChannelID       = t49.ChannelID,
														t48[33].DepthCoordinate = t49.DepthCoordinate,
														t48[34].Id              = t49.Id,
														t48[35].Name            = t49.Name?,
														t48[36].Status          = t49.Status,
														t48[37].AisleNumber     = t49.AisleNumber,
														t48[38].CategoryABC     = t49.CategoryABC?,
														t48[39].HeightClass     = t49.HeightClass
													FROM [StorageShelfDTO(49)] as t49 (<none>)
												) as t48 (a1)
											WHERE
												((([UID:111](t21[29].Id) = (t48[32].ChannelID))) AND (([UID:112](1) = (t48[33].DepthCoordinate))))
										) as t51 (a1)
								) as t54 (a1) ON 
					) as t38 (<none>)
						OUTER APPLY (
							(70) SELECT 
								t70[57].ResourceID = t68[56].ResourceID
							FROM (
									(68) SELECT 
										t68[54].Id             = t65[52].Id,
										t68[55].StorageShelfID = t65[51].StorageShelfID,
										t68[56].ResourceID     = t65[53].ResourceID
									FROM (
											(65) SELECT 
												t65[51].StorageShelfID = t66.StorageShelfID,
												t65[52].Id             = t66.Id,
												t65[53].ResourceID     = t66.ResourceID
											FROM [RefResourceStorageShelfDTO(66)] as t66 (<none>)
										) as t65 (b1)
									WHERE
										(([UID:125](t38[49].Id)? = (t65[51].StorageShelfID)))
								) as t68 (b1)
						) as t70 (b1) ON 
			) as t57 (<none>)
				OUTER APPLY (
					(86) SELECT 
						*
					FROM (
							(84) SELECT 
								t84[71].Id            = t81[60].Id,
								t84[72].Status        = t81[61].Status,
								t84[73].ResourceLabel = t81[62].ResourceLabel?,
								t84[74].CustomField1  = t81[63].CustomField1,
								t84[75].CustomField2  = t81[64].CustomField2,
								t84[76].CustomField3  = t81[65].CustomField3,
								t84[77].CustomLong1   = t81[66].CustomLong1,
								t84[78].CustomLong2   = t81[67].CustomLong2,
								t84[79].CustomLong3   = t81[68].CustomLong3,
								t84[80].HeightClass   = t81[69].HeightClass,
								t84[81].TypeID        = t81[70].TypeID
							FROM (
									(81) SELECT 
										t81[60].Id            = t82.Id,
										t81[61].Status        = t82.Status,
										t81[62].ResourceLabel = t82.ResourceLabel?,
										t81[63].CustomField1  = t82.CustomField1,
										t81[64].CustomField2  = t82.CustomField2,
										t81[65].CustomField3  = t82.CustomField3,
										t81[66].CustomLong1   = t82.CustomLong1,
										t81[67].CustomLong2   = t82.CustomLong2,
										t81[68].CustomLong3   = t82.CustomLong3,
										t81[69].HeightClass   = t82.HeightClass,
										t81[70].TypeID        = t82.TypeID
									FROM [WmsLoadCarrierDTO(82)] as t82 (<none>)
								) as t81 (c1)
							WHERE
								(([UID:154](t57[58].ResourceID)? = (t81[60].Id)))
						) as t84 (c1)
				) as t86 (c1) ON 
	) as t73 (<none>)
		OUTER APPLY (
			(123) SELECT 
				*
			FROM (
					(121) SELECT 
						t121[107].Id             = t118[95].Id,
						t121[108].Status         = t118[94].Status,
						t121[109].ResourceID     = t118[96].ResourceID,
						t121[110].ProductStatus  = t118[97].ProductStatus,
						t121[111].BatchNumber    = t118[98].BatchNumber?,
						t121[112].BundleUnit     = t118[99].BundleUnit,
						t121[113].CustomField1   = t118[100].CustomField1,
						t121[114].CustomField2   = t118[101].CustomField2,
						t121[115].CustomField3   = t118[102].CustomField3,
						t121[116].MaterialID     = t118[103].MaterialID,
						t121[117].InfeedAdviceID = t118[104].InfeedAdviceID?,
						t121[118].ExpiryDate     = t118[105].ExpiryDate,
						t121[119].CustomDate1    = t118[106].CustomDate1
					FROM (
							(118) SELECT 
								t118[94].Status          = t119.Status,
								t118[95].Id              = t119.Id,
								t118[96].ResourceID      = t119.ResourceID,
								t118[97].ProductStatus   = t119.ProductStatus,
								t118[98].BatchNumber     = t119.BatchNumber?,
								t118[99].BundleUnit      = t119.BundleUnit,
								t118[100].CustomField1   = t119.CustomField1,
								t118[101].CustomField2   = t119.CustomField2,
								t118[102].CustomField3   = t119.CustomField3,
								t118[103].MaterialID     = t119.MaterialID,
								t118[104].InfeedAdviceID = t119.InfeedAdviceID?,
								t118[105].ExpiryDate     = t119.ExpiryDate,
								t118[106].CustomDate1    = t119.CustomDate1
							FROM [InventoryResourceDTO(119)] as t119 (<none>)
						) as t118 (i1)
					WHERE
						(([UID:240](t118[94].Status) < (99))) AND (([UID:241](t100[91].Id) = (t118[95].Id)))
				) as t121 (i1)
		) as t123 (i1) ON 
```

**Comment by MaceWindu** [comment]
sql in 5.2.2
```sql
    -- SQLite.MS SQLite
DECLARE @take  -- Int32
SET     @take = 1
DECLARE @take_1  -- Int32
SET     @take_1 = 1

SELECT
	[x_10].[Id],
	[x_10].[AisleID],
	[x_10].[MaterialID],
	[x_10].[Id_1],
	[x_10].[AisleNumber],
	[x_10].[PlantID],
	[x_10].[Name],
	[x_10].[m_1],
	[x_10].[MaterialNumber],
	[x_10].[MaterialDescription_1],
	[x_10].[MaterialDescription_2],
	[x_10].[MaterialDescription_3],
	[x_10].[CategoryABC],
	[x_10].[CategoryCustoms],
	[x_10].[CategoryDimensions],
	[x_10].[CategoryQuality],
	[x_10].[CategoryTemperature],
	[x_10].[Id_2],
	[x_10].[ChannelID],
	[x_10].[Name_1],
	[x_10].[Status],
	[x_10].[AisleNumber_1],
	[x_10].[CategoryABC_1],
	[x_10].[HeightClass],
	[x_10].[DepthCoordinate],
	[x_10].[c1],
	[x_10].[ResourceLabel],
	[x_10].[Status_1],
	[x_10].[CustomLong2],
	[x_10].[HeightClass_1],
	[x_10].[TypeID],
	[x_10].[m1],
	[x_10].[MaterialNumber_1],
	[x_10].[MaterialDescription_1_1],
	[x_10].[CategoryABC_2],
	[x_10].[i1],
	[x_10].[BatchNumber],
	[x_10].[ProductStatus],
	[x_10].[ExpiryDate],
	[x_10].[CustomDate1],
	[x_10].[ir1ic],
	[x_10].[ror1],
	[x_10].[ir1mim],
	[a2n].[Id],
	[a2n].[ChannelID],
	[a2n].[Name],
	[a2n].[Status],
	[a2n].[AisleNumber],
	[a2n].[CategoryABC],
	[a2n].[HeightClass],
	[a2n].[DepthCoordinate],
	[c2n].[Id],
	[c2n].[ResourceLabel],
	[c2n].[Status],
	[c2n].[CustomLong2],
	[c2n].[HeightClass],
	[c2n].[TypeID],
	[m2n].[Id],
	[m2n].[MaterialNumber],
	[m2n].[MaterialDescription_1],
	[m2n].[CategoryABC],
	[t2].[i2],
	[t2].[BatchNumber],
	[t2].[ProductStatus],
	[t2].[ExpiryDate],
	[t2].[CustomDate1],
	(
		SELECT
			Count(*)
		FROM
			[InventoryResourceDTO] [x_3]
		WHERE
			[x_3].[Status] < 99 AND [x_3].[ResourceID] = [c2n].[Id]
	),
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[RefOutfeedTransportOrderResourceDTO] [x_4]
			WHERE
				[x_4].[ResourceID] = [c2n].[Id]
		)
			THEN 1
		ELSE 0
	END,
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				[InventoryResourceDTO] [x_5]
			WHERE
				[x_5].[Status] < 99 AND [x_5].[ResourceID] = [c2n].[Id] AND
				([x_5].[InfeedAdviceID] IS NULL OR EXISTS(
					SELECT
						*
					FROM
						[InfeedAdvicePositionDTO] [y_1]
					WHERE
						[y_1].[Id] = [x_5].[InfeedAdviceID] AND [y_1].[InfeedAdviceType] = 10
				))
		)
			THEN 1
		ELSE 0
	END
FROM
	(
		SELECT
			[c_1].[Id],
			[c_1].[AisleID],
			[c_1].[MaterialID],
			[a].[Id] as [Id_1],
			[a].[AisleNumber],
			[a].[PlantID],
			[a].[Name],
			[mn].[Id] as [m_1],
			[mn].[MaterialNumber],
			[mn].[MaterialDescription_1],
			[mn].[MaterialDescription_2],
			[mn].[MaterialDescription_3],
			[mn].[CategoryABC],
			[mn].[CategoryCustoms],
			[mn].[CategoryDimensions],
			[mn].[CategoryQuality],
			[mn].[CategoryTemperature],
			[a1n].[Id] as [Id_2],
			[a1n].[ChannelID],
			[a1n].[Name] as [Name_1],
			[a1n].[Status],
			[a1n].[AisleNumber] as [AisleNumber_1],
			[a1n].[CategoryABC] as [CategoryABC_1],
			[a1n].[HeightClass],
			[a1n].[DepthCoordinate],
			[c1n].[Id] as [c1],
			[c1n].[ResourceLabel],
			[c1n].[Status] as [Status_1],
			[c1n].[CustomLong2],
			[c1n].[HeightClass] as [HeightClass_1],
			[c1n].[TypeID],
			[m1n].[Id] as [m1],
			[m1n].[MaterialNumber] as [MaterialNumber_1],
			[m1n].[MaterialDescription_1] as [MaterialDescription_1_1],
			[m1n].[CategoryABC] as [CategoryABC_2],
			[t1].[i1],
			[t1].[BatchNumber],
			[t1].[ProductStatus],
			[t1].[ExpiryDate],
			[t1].[CustomDate1],
			(
				SELECT
					Count(*)
				FROM
					[InventoryResourceDTO] [x]
				WHERE
					[x].[Status] < 99 AND [x].[ResourceID] = [c1n].[Id]
			) as [ir1ic],
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						[RefOutfeedTransportOrderResourceDTO] [x_1]
					WHERE
						[x_1].[ResourceID] = [c1n].[Id]
				)
					THEN 1
				ELSE 0
			END as [ror1],
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						[InventoryResourceDTO] [x_2]
					WHERE
						[x_2].[Status] < 99 AND [x_2].[ResourceID] = [c1n].[Id] AND
						([x_2].[InfeedAdviceID] IS NULL OR EXISTS(
							SELECT
								*
							FROM
								[InfeedAdvicePositionDTO] [y]
							WHERE
								[y].[Id] = [x_2].[InfeedAdviceID] AND [y].[InfeedAdviceType] = 10
						))
				)
					THEN 1
				ELSE 0
			END as [ir1mim]
		FROM
			[ChannelDTO] [c_1]
				INNER JOIN [AisleDTO] [a] ON [c_1].[AisleID] = [a].[Id]
				LEFT JOIN [MaterialDTO] [mn] ON [c_1].[MaterialID] = [mn].[Id]
				LEFT JOIN [StorageShelfDTO] [a1n] ON [c_1].[Id] = [a1n].[ChannelID] AND 1 = [a1n].[DepthCoordinate]
				LEFT JOIN [RefResourceStorageShelfDTO] [b1n] ON [a1n].[Id] = [b1n].[StorageShelfID]
				LEFT JOIN [WmsLoadCarrierDTO] [c1n] ON [b1n].[ResourceID] = [c1n].[Id]
				LEFT JOIN (
					SELECT
						[x_6].[Id] as [i1],
						[x_6].[MaterialID],
						[x_6].[BatchNumber],
						[x_6].[ProductStatus],
						[x_6].[ExpiryDate],
						[x_6].[CustomDate1]
					FROM
						[InventoryResourceDTO] [x_6]
					WHERE
						[x_6].[Status] < 99
				) [t1] ON (
					SELECT
						[x_7].[Id]
					FROM
						[InventoryResourceDTO] [x_7]
					WHERE
						[x_7].[Status] < 99 AND [x_7].[ResourceID] = [b1n].[ResourceID]
					LIMIT @take
				) = [t1].[i1]
				LEFT JOIN [MaterialDTO] [m1n] ON [t1].[MaterialID] = [m1n].[Id]
	) [x_10]
		LEFT JOIN [StorageShelfDTO] [a2n] ON [x_10].[Id] = [a2n].[ChannelID] AND 2 = [a2n].[DepthCoordinate]
		LEFT JOIN [RefResourceStorageShelfDTO] [b2n] ON [a2n].[Id] = [b2n].[StorageShelfID]
		LEFT JOIN [WmsLoadCarrierDTO] [c2n] ON [b2n].[ResourceID] = [c2n].[Id]
		LEFT JOIN (
			SELECT
				[x_8].[Id] as [i2],
				[x_8].[MaterialID],
				[x_8].[BatchNumber],
				[x_8].[ProductStatus],
				[x_8].[ExpiryDate],
				[x_8].[CustomDate1]
			FROM
				[InventoryResourceDTO] [x_8]
			WHERE
				[x_8].[Status] < 99
		) [t2] ON (
			SELECT
				[x_9].[Id]
			FROM
				[InventoryResourceDTO] [x_9]
			WHERE
				[x_9].[Status] < 99 AND [x_9].[ResourceID] = [b2n].[ResourceID]
			LIMIT @take_1
		) = [t2].[i2]
		LEFT JOIN [MaterialDTO] [m2n] ON [t2].[MaterialID] = [m2n].[Id]
```

**Comment by igor-tkachev** [comment]
@MaceWindu, the braking commit is marked with this tag - https://github.com/linq2db/linq2db/releases/tag/issue-4337. See my commit in this PR. Changes in the TableT.cs fix this issue, but break your TestContextLeak test.

**Review by igor-tkachev — APPROVED** [review]

**Comment by jogibear9988** [comment]
LGTM

File: Source/LinqToDB/DataExtensions.cs [hunk 1]
```diff
@@ -1550,7 +1550,7 @@ public override Expression PrepareForCache(Expression expression)
 				Expression.Call(
 					null,
 					MethodHelper.GetMethodInfo(FromSql<TEntity>, dataContext, sql),
-					ExpressionConstants.DataContextParam, Expression.Constant(sql)));
+					Expression.Constant(null, typeof(IDataContext)), Expression.Constant(sql)));
```
Comment (MaceWindu) [inline Source/LinqToDB/DataExtensions.cs:1553]: we can move new constant to ExpressionConstants instead of removing it

**Review by MaceWindu — DISMISSED** [review]

**Review by igor-tkachev — APPROVED** [review]

File: Source/LinqToDB/Expressions/ExpressionInstances.cs [hunk 2]
```diff
@@ -9,6 +9,9 @@ namespace LinqToDB.Expressions
 	/// </summary>
 	public static class ExpressionInstances
 	{
+		public static readonly Expression NullIDataContext = Expression.Constant(null, typeof(IDataContext));
+		public static readonly Expression IntNegative1521134295 = Expression.Constant(-1521134295);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Expressions/ExpressionInstances.cs:13]: I would use a more descriptive name than `IntNegative1521134295`. Perhaps `HashMultiplier`?

File: Source/LinqToDB/Expressions/ExpressionEvaluator.cs [hunk 3]
```diff
@@ -33,68 +27,78 @@ public static class ExpressionEvaluator
...
 				return null;
 
-			switch (expr.NodeType)
-			{
-				case ExpressionType.Default:
-					return ReflectionExtensions.GetDefaultValue(expr.Type);
+			if (dataContext != null)
+				expr = expr.Transform(
+					dataContext,
+					static (dc, e) => e is ConstantExpression { Value : null } ce && ce.Type == typeof(IDataContext) ? Expression.Constant(dc) : e);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Expressions/ExpressionEvaluator.cs:33]:
```suggestion
					static (dc, e) => e is ConstantExpression { Value : null, Type: var t } && t == typeof(IDataContext) ? Expression.Constant(dc) : e);
```

File: Source/LinqToDB/Expressions/ExpressionEvaluator.cs [hunk 4]
```diff
@@ -33,68 +27,78 @@ public static class ExpressionEvaluator
 			if (expr == null)
 				return null;
 
-			switch (expr.NodeType)
-			{
-				case ExpressionType.Default:
-					return ReflectionExtensions.GetDefaultValue(expr.Type);
+			if (dataContext != null)
```
Comment (viceroypenguin) [inline Source/LinqToDB/Expressions/ExpressionEvaluator.cs:30]: add braces

File: Source/LinqToDB/Linq/Builder/AssociationHelper.cs [hunk 5]
```diff
@@ -32,7 +32,10 @@ static class AssociationHelper
 			List<LoadWithInfo[]>? loadWith,
 			out bool isLeft)
 		{
-			Expression dataContextExpr = ExpressionConstants.DataContextParam;
+//			var dataContextConstant = Expression.Constant(builder.DataContext, builder.DataContext.GetType());
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/AssociationHelper.cs:35]: Remove commented out line.

File: Source/LinqToDB/Linq/Builder/AssociationHelper.cs [hunk 6]
```diff
@@ -64,6 +67,7 @@ static class AssociationHelper
 				if (onMember.Arguments == null)
 				{
 					if (definedQueryMethod.Parameters.Count > 1 && typeof(IDataContext).IsSameOrParentOf(definedQueryMethod.Parameters[1].Type))
+//						parameterMatch.Add(definedQueryMethod.Parameters[1], dataContextConstant);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/AssociationHelper.cs:70]: Remove commented out line

File: Source/LinqToDB/Linq/Builder/AssociationHelper.cs [hunk 7]
```diff
@@ -150,6 +154,7 @@ static class AssociationHelper
 					}
 				}
 
+//				var queryParam = Expression.Call(Methods.LinqToDB.GetTable.MakeGenericMethod(objectType), dataContextConstant);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Linq/Builder/AssociationHelper.cs:157]: Remove commented out line

File: Source/LinqToDB/LinqExtensions.Merge.cs [hunk 8]
```diff
@@ -1099,7 +1099,7 @@ public MergeQuery(IQueryable<TTarget> query)
 					null,
 					Methods.LinqToDB.Merge.MergeWithOutputInto.MakeGenericMethod(typeof(TTarget), typeof(TSource), typeof(TOutput)),
 					currentQuery.Expression,
-					outputTable.Expression,
+					((IQueryable<TOutput>)outputTable).Expression,
```
Comment (viceroypenguin) [inline Source/LinqToDB/LinqExtensions.Merge.cs:1102]: Does `outputTable.Expression` return a different value from `((IQueryable<TOutput>)outputTable).Expression`?

**Review by viceroypenguin — CHANGES_REQUESTED** [review]

File: Source/LinqToDB/Expressions/ExpressionInstances.cs (hunk 2 above)
Comment (jogibear9988) [reply Source/LinqToDB/Expressions/ExpressionInstances.cs:13]: Don't know if it is more descriptive. It may be at the place where the expression is used, but not at the Place where it is defined. It is only a Constant Expression with this value.

Comment (viceroypenguin) [reply Source/LinqToDB/Expressions/ExpressionInstances.cs:13]: This is the equivalent of:
```cs
public const int Five = 5;
```

What happens if you need to change `Five`? What happens if someone comes along later and reads the code and wants to know what it's for? What happens if every place that needs a five specifically references `Five`, but they need five for different reasons.

Constants should be defined by their use, not their value. Then you can a) understand why the constant exists, and b) you can change the value appropriately. 

Better to have:
```cs
public const int FooCount = 5;
public const int BarCount = 5;
```

Similarly, this constant should be defined by how it's being used: as the `HashMultiplier`. Or maybe `HashMultiplierExpressionConstant`.

Comment (jogibear9988) [reply Source/LinqToDB/Expressions/ExpressionInstances.cs:13]: image

then most of those constants are wrong

Comment (viceroypenguin) [reply Source/LinqToDB/Expressions/ExpressionInstances.cs:13]: These two specifically, I would agree. Given their use in Oracle for a specific purpose, they should have a better name than `Constant26` and `Constant29`.

File: Source/LinqToDB/LinqExtensions.Merge.cs (hunk 8 above)
Comment (jogibear9988) [reply Source/LinqToDB/LinqExtensions.Merge.cs:1102]: this I can not answer, rest is resolved

Comment (jogibear9988) [reply Source/LinqToDB/LinqExtensions.Merge.cs:1102]: I looked, yes this are 2 different Expressions:

outputTable.Expression => is in the IQueryable
((IQueryable<TOutput>)outputTable).Expression => 
image

**Review by viceroypenguin — APPROVED** [review]

**Review by MaceWindu — APPROVED** [review]

**Comment by jogibear9988** [comment]
The one not workin test for me seems unrelated to this pull req. Could we merge?
