### PR TITLE
Bunch of T4-related fixes for next release

### LINKED ISSUE #2485: Can't generate data context with t4 template. PostgreSQL + MySql
First i added ```linq2db.postgresql (3.1.0)``` and generated the context with the t4 template and everything worked fine. after adding ```linq2db.mysql (3.1.0)``` and ```mysql.data (8.0.21)``` to the project, the same context stopped generating and falls off with an error in the ```GenerateModel()``` method in T4 template.

Stack trace:
```   
Microsoft.VisualStudio.TextTemplatingA5208046AF2043F523FADEBCEC39E89AD7C755BFB4575C9DACB89B9BC71CF16FD3DD7FEC14C137FA1F177710ACD95EE8B411A25F37E08636F44DA95190DC0880. GeneratedTextTransformation.TransformText() in C:\Project\statistics.tt:line 51
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()
```
image

### LINKED ISSUE #2629: Using T4 Generated DataContext with .Net Core Dependency injection
Hello, i look the article for [Configuring LINQ To DB for ASP.Net Core](https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html#add-table-property-to-the-data-connection) and it's actually work.

But when i create generated context with t4.
Context Constructor dosn't have  (LinqToDbConnectionOptions<Class> options) : base(options).
I can add of course but i don't want to add because i can update the database and re-generate to datacontext later.

**Can i add diffrently to scope or can i fix this missing constructor error ?**

lq1

### Codes

```c#
Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();

            services.AddLinqToDbContext<NorthwindDB>((provider, options) =>
            {
                options
                    .UseSqlServer(Configuration.GetConnectionString("Default"))
                    .UseDefaultLogging(provider);
            });


  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });

            using var scope = app.ApplicationServices.CreateScope();
            var dataConnection = scope.ServiceProvider.GetService<NorthwindDB>();
        }


```

### Environment details
linq2db version: 3.1.6
Database Server: MSSQL Local
Operating system: Win 10
.NET Framework: Core 3.1

```
Exception message: System.ArgumentException: 'Missing constructor accepting 'LinqToDbContextOptions' on type NorthwindDB'
Stack trace:    at LinqToDB.AspNet.ServiceConfigurationExtensions.CheckContextConstructor[TContext]()
   at LinqToDB.AspNet.ServiceConfigurationExtensions.AddLinqToDbContext[TContext,TContextImplementation](IServiceCollection serviceCollection, Action`2 configure, ServiceLifetime lifetime)
   at LinqToDB.AspNet.ServiceConfigurationExtensions.AddLinqToDbContext[TContext](IServiceCollection serviceCollection, Action`2 configure, ServiceLifetime lifetime)
   at LQTODBCORE.Startup.ConfigureServices(IServiceCollection services) in C:\Users\LookusGunes\source\repos\LQTODBCORE\LQTODBCORE\Startup.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at LQTODBCORE.Program.Main(String[] args) in \LQTODBCORE\Program.cs:line 16
```

### LINKED ISSUE #2633: Red code in T4 templates in JetBrains Rider
Jetbrains Rider reports errors in the templates after installation.
As the developer of the Rider T4 plugin, I think that this is the intended behaviour.
These templates are red in Rider because they are not self-sufficient: some templates contain references to libraries, while others contain usages of symbols from those libraries. It is absolutely impossible to resolve those symbols before both templates with assembly references and templates with usages of their symbols are included into a user file.
So templates with symbol usages implicitly assume that the user will include templates with definitions or references.
I suggest making that dependency explicit by including templates with references or definitions into the dependent templates.
For example, `Equatable.ttinclude` would include `T4Model.ttinclude` since it uses symbol `BeforeGenerateModel` defined in it.
Duplicate inclusions can be avoided by using attribute `once="true"` in such includes.

### LINKED ISSUE #2663: SQL Server - Collation conflict while generating data access classes
In cases when the collation of the catalog (`CATALOG_COLLATION` option of `CREATE DATABASE`) is different than the default collation of the database, the collation of the database name (catalog) is different than the collation of the names of the schema, tables, etc. The name of the database use the default database collation while the names of the objects in the database use the collation specified by `CATALOG_COLLATION`.

One reason for having different collations is to use a case-sensitive collation by default for the data and case-insensitive collation for the names of the database objects. For some unfathomable reason the collation is different for the database's name which means that it can be case-sensitive if the default collation is case-sensitive.

linq2db uses the following query to load the schema:

```SQL
SELECT
	TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME                          as TableID,
	TABLE_CATALOG                                                                  as CatalogName,
	TABLE_SCHEMA                                                                   as SchemaName,
	TABLE_NAME                                                                     as TableName,
	CASE WHEN TABLE_TYPE = 'VIEW' THEN 1 ELSE 0 END                                as IsView,
	ISNULL(CONVERT(varchar(8000), x.Value), '')                                    as Description,
	CASE WHEN TABLE_SCHEMA = 'dbo' THEN 1 ELSE 0 END                               as IsDefaultSchema
FROM
	INFORMATION_SCHEMA.TABLES s
	LEFT JOIN
		sys.tables t
	ON
		OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') = t.object_id
	LEFT JOIN
		sys.extended_properties x
	ON
		OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') = x.major_id AND
		x.minor_id = 0 AND 
		x.name = 'MS_Description'
WHERE
	t.object_id IS NULL OR
	t.is_ms_shipped <> 1 AND
	(
		SELECT
			major_id
		FROM
			sys.extended_properties
		WHERE
			major_id = t.object_id AND
			minor_id = 0           AND
			class    = 1           AND
			name     = N'microsoft_database_tools_support'
	) IS NULL
```

The only issue is `TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME                          as TableID` in the select list. For some reason concatenation in the where/ join clauses like `'[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']'` does not causes issues but if the same code is used in the select clause it fails as well.

```
Exception message: Running transformation: System.Data.SqlClient.SqlException (0x80131904): Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CS_AS" in add operator occurring in SELECT statement column 1.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T]()
   at LinqToDB.DataProvider.SqlServer.SqlServerSchemaProvider.GetTables(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadSqlServerMetadata(String connectionString, SqlServerVersion version, SqlServerProvider provider)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.TransformText()

```

### Steps to reproduce

Create a new database and attempt to generate data model types.

```SQL
CREATE DATABASE [TEST]
CONTAINMENT = NONE
ON PRIMARY 
(NAME = N'TEST', FILENAME = N'...' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
LOG ON (NAME = N'TEST_log', FILENAME = N'...' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CS_AS
WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS
GO

...
```

### Environment details
linq2db version: 3.1.6
Database Server: SQL Server 2019
Database Provider: Microsoft.Data.SqlClient
Operating system: Windows Server 2019
.NET Framework: .NET Core 3.1

### LINKED ISSUE #2679: T4 LinqToDB.Templates Generate Function but Case-Sensitive Schema Problem
im using postgreSQL for generate function

**result:**
`[Sql.Function(Name="SchemaName.\"fnTest\"", ServerSideOnly=true)]`

**expectation:**
`[Sql.Function(Name="\"SchemaName\".\"fnTest\"", ServerSideOnly=true)]`

**source:**
https://github.com/linq2db/linq2db/blob/ffed64756a5256f755fadc1c20cbaa05cc6eeb85/Source/LinqToDB.Templates/LinqToDB.ttinclude#L750

https://github.com/linq2db/linq2db/blob/ffed64756a5256f755fadc1c20cbaa05cc6eeb85/Source/LinqToDB.Templates/LinqToDB.ttinclude#L766

### PR DESCRIPTION
**Pull request by MaceWindu**
- Fix #2629
- Fix #2679
- Fix #2663
- Fix #2485
- Fix #2633

Other changes/fixes:
- SQL Server 2019 test provider now expects that database is case sensitive (switched to have test coverage for case-sensitive db)
- added note to `linq2db.<DB>` packages description to highlight that they should be used only if user plan to use T4 templates as it creates confusion right now
- reorganized T4 templates includes to reduce number of errors in Rider and fixed some warnings/suggestions from Rider in T4 templates. Still Rider shows errors for linq2db types despite `linq2db.dll` being referenced in template, but this looks more like Rider bug
- reorganized T4 MS Build properties to support multiple installed T4 packages
- replaced some providers, used by T4 nuget tools with better alternatives:
  - `MySql.Data` -> `MySqlConnector` (we should avoid use of `MySql.Data`)
  - native Sybase ASE provider -> `AdoNetCore.AseClient` (to not require user to have native client installed)
- added `README.md` to `Nugets` folder to document some nuget magic we do
- removed some not needed/duplicate files
- added `Humanizer.dll` to T4 nugets `tools` so user don't need to install it
- [BREAKING] Fixed typo in some T4 properties:
  - `GetAssociationExtensionSinglularName` -> `GetAssociationExtensionSingularName`
  - `GetAssociationExtensionSinglularNameDefault` -> `GetAssociationExtensionSingularNameDefault`

### CODE REVIEW

**Comment by MaceWindu** [comment]
MAybe I will add fix for #2752 later if have time left. Still need to finish some extra testing

File: Tests/Base/TestBase.cs [hunk 1]
```diff
@@ -1039,6 +1039,11 @@ protected IEnumerable<LinqDataTypes2> AdjustExpectedData(ITestDataContext db, IE
 			return data;
 		}
 
+		protected bool IsCaseSensitiveDB(string context)
+		{
+			return GetProviderName(context, out var _) == TestProvName.SqlServer2019;
```
Comment (viceroypenguin) [inline Tests/Base/TestBase.cs:1044]: Add comment here for future reference why '19 is specifically case sensitive (i.e. it's not intrinsically '19, but as a test bed for any other case-sensitive dbs)

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
Ok,  #2752 will not make it into next release. We have strange and probably unnecessary logic around FK names, don't want to break it before release. And don't have time actually.
