### PR TITLE
Fix for #2963. Corrected arguments collecting.

### LINKED ISSUE #2963: 3.3 Regression in SelectQuery?
Assume that `MySequence` is a property decored with  `Sql.Expression("MY_SEQUENCE.nextval", ServerSideOnly = true)`, so basically a placeholder for a sequence nextval.

The following query used to work in 3.2 (Oracle provider):
```csharp
db.SelectQuery(() => db.MySequence).AsEnumerable().Single()
```
It's meant to fetch the next sequence value and generates:
```sql
SELECT MY_SEQUENCE.nextval FROM DUAL
```
Note that the `AsEnumerable()` is just there to prevent LinqToDb from appending a `FETCH NEXT 1 ROW ONLY`, which would be an unsupported Oracle combination with `nextval`, and shouldn't matter.

With 3.3 it crashes during query generation.
It throws `ArgumentException` _Value does not fall within the expected range_ when trying to set the value of a DbParameter named `"db"` to the value `db` (i.e. the `DataConnection` itself).

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #2963

### CODE REVIEW

File: Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs [hunk 1]
```diff
@@ -420,9 +420,12 @@ public static ISqlExpression[] PrepareArguments(string expressionStr, int[]? arg
 					}
 					else
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs:421]:
```suggestion
					else if (addDefault)
```

File: Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs [hunk 2]
```diff
@@ -438,7 +441,7 @@ public static ISqlExpression[] PrepareArguments(string expressionStr, int[]? arg
 				if (string.IsNullOrEmpty(expressionStr))
 					throw new LinqToDBException($"Cannot retrieve SQL Expression body from expression '{expression}'.");
 
-				var parameters = PrepareArguments(expressionStr!, ArgIndices, knownExpressions, genericTypes, converter);
+				var parameters = PrepareArguments(expressionStr!, ArgIndices, false, knownExpressions, genericTypes, converter);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs:444]:
```suggestion
				var parameters = PrepareArguments(expressionStr!, ArgIndices, addDefault: false, knownExpressions, genericTypes, converter);
```

File: Source/LinqToDB/Sql/Sql.FunctionAttribute.cs [hunk 3]
```diff
@@ -97,7 +97,7 @@ public FunctionAttribute(string configuration, string name, params int[] argIndi
 				if (string.IsNullOrEmpty(expressionStr))
 					throw new LinqToDBException($"Cannot retrieve function name for expression '{expression}'.");
 
-				var parameters = PrepareArguments(expressionStr!, ArgIndices, knownExpressions, genericTypes, converter);
+				var parameters = PrepareArguments(expressionStr!, ArgIndices, true, knownExpressions, genericTypes, converter);
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.FunctionAttribute.cs:100]:
```suggestion
				var parameters = PrepareArguments(expressionStr!, ArgIndices, addDefault: true, knownExpressions, genericTypes, converter);
```

File: Source/LinqToDB/Sql/Sql.TableExpressionAttribute.cs [hunk 4]
```diff
@@ -61,7 +61,7 @@ public override void SetTable(ISqlBuilder sqlBuilder, MappingSchema mappingSchem
 				knownExpressions.Insert(0, null);
 				knownExpressions.Insert(0, null);
 
-				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, knownExpressions, genericTypes, converter).Skip(2).ToArray();
+				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, false, knownExpressions, genericTypes, converter).Skip(2).ToArray();
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.TableExpressionAttribute.cs:64]:
```suggestion
				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, addDefault: false, knownExpressions, genericTypes, converter).Skip(2).ToArray();
```

File: Source/LinqToDB/Sql/Sql.TableFunctionAttribute.cs [hunk 5]
```diff
@@ -70,7 +70,7 @@ public virtual void SetTable(ISqlBuilder sqlBuilder, MappingSchema mappingSchema
 				knownExpressions.Insert(0, null);
 				knownExpressions.Insert(0, null);
 
-				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, knownExpressions, genericTypes, converter).Skip(2).ToArray();
+				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, true, knownExpressions, genericTypes, converter).Skip(2).ToArray();
```
Comment (viceroypenguin) [inline Source/LinqToDB/Sql/Sql.TableFunctionAttribute.cs:73]:
```suggestion
				table.TableArguments = ExpressionAttribute.PrepareArguments(expressionStr!, ArgIndices, addDefault: true, knownExpressions, genericTypes, converter).Skip(2).ToArray();
```

**Review by viceroypenguin — APPROVED** [review]

**Review by MaceWindu — APPROVED** [review]
