### PR TITLE
DB2 date/time/timestamp support improvements

### LINKED ISSUE #1663: Db2 and linq2db TimeStamp / Datetime problem
I have an Issue with the delete Methode using Db2 and linq2db with C#.
I want to delete an Entry from an List with UserData-Objects. But it generates a wrong Sql- Statement the Datetime is Wrong (to short). 

**C# Code (both generate same Sql-Statement):** 
context.UserDatas.Delete(ud => ud.Equals(userData));
or context.Delete(userData);

**My data entry to delete looks like this:**
BENUTZERID=1 
PWD='8u9C5uwBJn1LqrKtrYU1d5KTgzO5xBbo'
SCHLUESSEL='HwrBTA6IZx6VW5mYTI5Gd7mFejWBtHDd'
ANLEGEZEITPUNKT='2016-12-20-15.39.38.826121' 

**Here is the generated Statement:** 
DELETE FROM
	UM.BENUTZERDATEN "t1"
WHERE
	"t1".BENUTZERID = 1 AND
	"t1".PWD = '8u9C5uwBJn1LqrKtrYU1d5KTgzO5xBbo' AND
	"t1".SCHLUESSEL = 'HwrBTA6IZx6VW5mYTI5Gd7mFejWBtHDd' AND
	"t1".ANLEGEZEITPUNKT = '2016-12-20 15:39:38.826' **<--- Where are the Last 3 Numbers**

**The UserData-Object:**
one int Field, two string Fields and a datetime Field.

**My Db2 Table looks like:**
    "BENUTZERID"    INTEGER NOT NULL ,
    "PWD"    VARCHAR(255) NOT NULL ,
    "SCHLUESSEL"    VARCHAR(255) NOT NULL ,
    "ANLEGEZEITPUNKT"    TIMESTAMP NOT NULL   DEFAULT CURRENT TIMESTAMP 

I could do a Workaround with filtering only Id,Pwd and Schluessel but thats a bad Solution. Can i do something to Fix the datetime Format?

### Environment details
linq2db version: *2.6.4*
Database Server: *DB2 10.5*
Database Provider: *IBM.Data.DB2.Core*
Operating system: *Windows 7*
Framework version: *.NET Core 2.2*

### PR DESCRIPTION
**Pull request by MaceWindu**
Fixes #1663 

- [refactoring] removed unused `MappingSchema` parameter from `IDataContext.GetReaderExpression`, `IDataProvider.GetReaderExpression`
- `InlineParameters` option applied only to parameters of types, that we can convert to literal
- fixed literal generation for DB2 date/time/timestamp types
- reenable TimeSpan literals for DB2

### CODE REVIEW

File: Tests/Linq/DataProvider/DB2Tests.cs [hunk 1]
```diff
@@ -620,5 +620,166 @@ public void TestTypes([IncludeDataSources(CurrentProvider)] string context)
...
+					Data[idx].TimeStamp12 = new DB2TimeStamp(1000, 1, 10, 2, 20, 30, i, 12);
+				}
+			}
+
+			public static TestTimeTypes[] Data;
+
+			public static Func<TestTimeTypes, TestTimeTypes, bool> Comparer = ComparerBuilder.GetEqualsFunc<TestTimeTypes>();
+		}
+
+		[ActiveIssue(SkipForNonLinqService = true, Details = "RemoteContext miss provider-specific types mappings. Could be workarounded by explicit column mappings")]
```
Comment (MaceWindu) [inline Tests/Linq/DataProvider/DB2Tests.cs]: CreateTable fails as remote context mapping schema doesn't contain type mappings for DB2 types. Not sure yet how to fix it in future. As workaround user could set dbtype/datatype on columns
