### PR TITLE
Fix for #2647. Do not create subquery for ThenBy if there are already order items.

### LINKED ISSUE #2647: Wrong OrderBy Order
following query creates wrong sql:

			using (var db = GetDataContext(context, ms))
			{
				db.DropTable<IssueClass>(throwExceptionIfNotExists: false);
				db.CreateTable<IssueClass>();
				{
					var qryUnsorted = from tt in db.GetTable<IssueClass>() select tt;
					// sort language id 
					var qry2 = qryUnsorted.OrderBy(x => x.LanguageId);
					//after that sort with a complex sub-select 
					qry2 = qry2.ThenByDescending(ss => db.GetTable<IssueClass>().Count(ss2 => ss2.Id == ss.Id) * 10000 /
														db.GetTable<IssueClass>().Count(ss3 => ss3.Id == ss.Id));
					var ll = qry2.Select(x=>x.Text).ToList();
					var sql = ((DataConnection)db).LastQuery;
					Assert.IsNotNull(sql);
					Assert.Greater(sql.IndexOf("TextId", StringComparison.OrdinalIgnoreCase), sql.IndexOf("LanguageId", StringComparison.OrdinalIgnoreCase), "error in order by order");
				}
			}

sql:

	SELECT
		[tt].[Text]
	FROM
		[Issue2699Table] [tt]
	ORDER BY
		((
			SELECT
				Count(*)
			FROM
				[Issue2699Table] [ss2]
			WHERE
				[ss2].[Id] = [tt].[Id]
		) * 10000) / (
			SELECT
				Count(*)
			FROM
				[Issue2699Table] [ss3]
			WHERE
				[ss3].[Id] = [tt].[Id]
		) DESC,
		[tt].[LanguageId]

### PR DESCRIPTION
**Pull request by jogibear9988**
Fixes #2647

### CODE REVIEW

File: Tests/Linq/UserTests/Issue2647Tests.cs [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+			public string? LanguageId { get; set; }
+			[Column]
+			public string? Text { get; set; }
+		}
+
+		[Test]
+		public void OrderBySybqueryTest([IncludeDataSources(TestProvName.AllSQLite)] string context)
+		{
+			using (var db = GetDataContext(context))
+			{
```
Comment (MaceWindu) [inline Tests/Linq/UserTests/Issue2647Tests.cs:29]:
```suggestion
			using (var table = db.CreateLocalTable<IssueClass>())
			{
```

File: Tests/Linq/UserTests/Issue2647Tests.cs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+				var qryUnsorted = db.GetTable<IssueClass>();
+				var query = qryUnsorted.OrderBy(x => x.LanguageId);
+				query = query.ThenByDescending(ss => db.GetTable<IssueClass>().Count(ss2 => ss2.Id == ss.Id) * 10000 /
+				                                     db.GetTable<IssueClass>().Count(ss3 => ss3.Id == ss.Id));
+
+				var sql = query.ToString();
```
Comment (MaceWindu) [inline Tests/Linq/UserTests/Issue2647Tests.cs:35]:
```suggestion
				query.ToList();
				var sql = query.ToString();
```

**Review by MaceWindu — APPROVED** [review]
