### PR TITLE
#615 perfomance fix

### LINKED ISSUE #615: Usage of linq2db with differnet MappingSchemas
I use linq2db in a Business Apllication.

In this I have different DataConnections, with different mapped DTO's and different Mapping Schemas.

I want to know, how should I use linq2db correctly? In the Parts of the Code where I need DB Access, I create a DataConnection, and dispose when I've finished the DB Access. But what is with the MappingSchema? I think the creation of this is expensive, so I should keep it? How do I Setup a DataConnection with a existing MappingSchema?

### PR DESCRIPTION
**Pull request by ili**
#615 Moving EntityDescriptors cache to MappingSchemaInfo to avoid performance gap on using many MappingSchemas

### CODE REVIEW

File: Source/Mapping/MappingSchemaInfo.cs [hunk 1]
```diff
@@ -239,5 +239,42 @@ public void SetDefaultFromEnumType(Type enumType, Type defaultFromType)
...
+		}
+
+		/// <summary>
+		/// Enumerate types for cached <see cref="EntityDescriptor"/>s
+		/// </summary>
+		/// <seealso cref="GetEntityDescriptor"/>
+		/// <returns><see cref="IEnumerable{T}"/></returns>
+		public IEnumerable<Type> GetEntites()
+		{
+			return _entityDescriptors.Keys;
```
Comment (sdanyliv) [inline Source/Mapping/MappingSchemaInfo.cs]: Better return list here. It is thread safe.

File: Source/Mapping/ColumnDescriptor.cs [hunk 2]
```diff
@@ -16,7 +16,6 @@ public class ColumnDescriptor
 	{
 		public ColumnDescriptor(MappingSchema mappingSchema, ColumnAttribute columnAttribute, MemberAccessor memberAccessor)
```
Comment (sdanyliv) [inline Source/Mapping/ColumnDescriptor.cs]: Something wrong here. MappingSchema used for initialization.

Comment (ili) [inline Source/Mapping/ColumnDescriptor.cs]: Yes, only for initialization

Comment (sdanyliv) [inline Source/Mapping/ColumnDescriptor.cs]: Hipothetic situation, other mapping schema changes DbType and DataType for ColumnDescriptor - it will not broke something?

Comment (ili) [inline Source/Mapping/ColumnDescriptor.cs]: Yes, but this change does not apply this, without this change the situation is the same.

**Comment by sdanyliv** [comment]
@jogibear9988, please confirm that this solution works for you.

**Comment by jogibear9988** [comment]
I think it should, looks good.
In my production application I could only test if this is merged (because if I only replace the linq2db dll's it will not run)

**Comment by jogibear9988** [comment]
merge?

**Comment by jogibear9988** [comment]
tested and works!
