### PR TITLE
Fix length -1 on varchar(max) parameters

### LINKED ISSUE #4631: GetSchema(): Incorrect syntax near '-'
### Describe your issue
Calling db.DataProvider.GetSchemaProvider().GetSchema(db) (SqlServerDataProvider2022MicrosoftDataSqlClient) results in the following exception:

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near '-'.
The batch could not be analyzed because of compile errors.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlConnection.OnError(Microsoft.Data.SqlClient.SqlException exception, bool breakConnection, System.Action<System.Action> wrapCloseInAction)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlInternalConnection.OnError(Microsoft.Data.SqlClient.SqlException exception, bool breakConnection, System.Action<System.Action> wrapCloseInAction)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(Microsoft.Data.SqlClient.TdsParserStateObject stateObj, Microsoft.Data.SqlClient.SqlCommand command, bool callerHasConnectionLock, bool asyncClose)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.TdsParser.TryRun(Microsoft.Data.SqlClient.RunBehavior runBehavior, Microsoft.Data.SqlClient.SqlCommand cmdHandler, Microsoft.Data.SqlClient.SqlDataReader dataStream, Microsoft.Data.SqlClient.BulkCopySimpleResultSet bulkCopyHandler, Microsoft.Data.SqlClient.TdsParserStateObject stateObj, out bool dataReady)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlDataReader.MetaData.get()	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(Microsoft.Data.SqlClient.SqlDataReader ds, Microsoft.Data.SqlClient.RunBehavior runBehavior, string resetOptionsString, bool isInternal, bool forDescribeParameterEncryption, bool shouldCacheForAlwaysEncrypted)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior cmdBehavior, Microsoft.Data.SqlClient.RunBehavior runBehavior, bool returnStream, bool isAsync, int timeout, out System.Threading.Tasks.Task task, bool asyncWrite, bool inRetry, Microsoft.Data.SqlClient.SqlDataReader ds, bool describeParameterEncryptionRequest)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior cmdBehavior, Microsoft.Data.SqlClient.RunBehavior runBehavior, bool returnStream, System.Threading.Tasks.TaskCompletionSource<object> completion, int timeout, out System.Threading.Tasks.Task task, out bool usedCache, bool asyncWrite, bool inRetry, string method)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior cmdBehavior, Microsoft.Data.SqlClient.RunBehavior runBehavior, bool returnStream, string method)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(System.Data.CommandBehavior behavior)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(System.Data.CommandBehavior behavior)	Unknown
 	linq2db.dll!LinqToDB.Data.DataConnection.ExecuteReader(System.Data.CommandBehavior commandBehavior)	Unknown
 	linq2db.dll!LinqToDB.Data.DataConnection.ExecuteDataReader(System.Data.CommandBehavior commandBehavior)	Unknown
 	linq2db.dll!LinqToDB.Data.CommandInfo.Query<<>f__AnonymousType93<string, bool, string, int, int, int, bool>>()	Unknown
 	linq2db.dll!LinqToDB.Data.CommandInfo.QueryProc<<>f__AnonymousType93<string, bool, string, int, int, int, bool>>()	Unknown
 	linq2db.dll!LinqToDB.Data.CommandInfo.QueryProc<<>f__AnonymousType93<string, bool, string, int, int, int, bool>>(<>f__AnonymousType93<string, bool, string, int, int, int, bool> template)	Unknown
 	linq2db.dll!LinqToDB.Data.DataConnectionExtensions.QueryProc<<>f__AnonymousType93<string, bool, string, int, int, int, bool>>(LinqToDB.Data.DataConnection connection, <>f__AnonymousType93<string, bool, string, int, int, int, bool> template, string sql, LinqToDB.Data.DataParameter[] parameters)	Unknown
 	linq2db.dll!LinqToDB.DataProvider.SqlServer.SqlServerSchemaProvider.GetProcedureSchema(LinqToDB.Data.DataConnection dataConnection, string commandText, System.Data.CommandType commandType, LinqToDB.Data.DataParameter[] parameters, LinqToDB.SchemaProvider.GetSchemaOptions options)	Unknown
 	linq2db.dll!LinqToDB.SchemaProvider.SchemaProviderBase.LoadProcedureTableSchema(LinqToDB.Data.DataConnection dataConnection, LinqToDB.SchemaProvider.GetSchemaOptions options, LinqToDB.SchemaProvider.ProcedureSchema procedure, string commandText, System.Collections.Generic.List<LinqToDB.SchemaProvider.TableSchema> tables)	Unknown
 	linq2db.dll!LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(LinqToDB.Data.DataConnection dataConnection, LinqToDB.SchemaProvider.GetSchemaOptions options)	Unknown
```

I think this is caused by a call to sp_describe_first_result_set in SqlServerSchemaProvider.cs:GetProcedureSchema():

```sql
exec sp_describe_first_result_set N'exec [dbo].[spActivateAlarm] @iAlarmTypePK, @iTermPK, @iNodePK, @iValue, @strText, @dtSourceDate, @bTestMode, @iPriority, @strCookie, @iSubscriberPK, @strSourceIP, @sourceOperatorPK, @sourceUserPK, @sourcePersonName', N'@iAlarmTypePK int, @iTermPK int, @iNodePK int, @iValue int, @strText nvarchar(-1), @dtSourceDate datetime, @bTestMode bit, @iPriority int, @strCookie varchar(-1), @iSubscriberPK int, @strSourceIP varchar(255), @sourceOperatorPK int, @sourceUserPK int, @sourcePersonName nvarchar(450)'
```

```
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near '-'.
Msg 11501, Level 16, State 1, Line 1
The batch could not be analyzed because of compile errors.
```

"nvarchar(-1)" is not the correct syntax - it should be "nvarchar(max)". I can confirm that the following query:

```cs
"SELECT
					SPECIFIC_CATALOG COLLATE DATABASE_DEFAULT + '.' + SPECIFIC_SCHEMA + '.' + SPECIFIC_NAME as ProcedureID,
					ORDINAL_POSITION                                                                        as Ordinal,
					PARAMETER_MODE                                                                          as Mode,
					PARAMETER_NAME                                                                          as ParameterName,
					DATA_TYPE                                                                               as DataType,
					CHARACTER_MAXIMUM_LENGTH                                                                as Length,
					NUMERIC_PRECISION                                                                       as [Precision],
					NUMERIC_SCALE                                                                           as Scale,
					CASE WHEN PARAMETER_MODE = 'IN'  OR PARAMETER_MODE = 'INOUT' THEN 1 ELSE 0 END          as IsIn,
					CASE WHEN PARAMETER_MODE = 'OUT' OR PARAMETER_MODE = 'INOUT' THEN 1 ELSE 0 END          as IsOut,
					CASE WHEN IS_RESULT      = 'YES'                             THEN 1 ELSE 0 END          as IsResult,
					USER_DEFINED_TYPE_CATALOG                                                               as UDTCatalog,
					USER_DEFINED_TYPE_SCHEMA                                                                as UDTSchema,
					USER_DEFINED_TYPE_NAME                                                                  as UDTName,
					1                                                                                       as IsNullable,
					ISNULL(CONVERT(varchar(8000), x.value), '')                                             as Description
				FROM
					INFORMATION_SCHEMA.PARAMETERS
					LEFT JOIN sys.extended_properties x
						ON OBJECT_ID('[' + SPECIFIC_SCHEMA + '].[' + SPECIFIC_NAME + ']') = x.major_id AND
							ORDINAL_POSITION = x.minor_id AND
							x.name = 'MS_Description' AND x.class = 2"
```

returns Length = -1 on nvarchar(max) parameters. I suspect that SchemaProviderBase.cs:GetDbType() should check if < 0:

case "max length" : paramValues[i] = length == int.MaxValue ? "max" : length?.ToString(NumberFormatInfo.InvariantInfo); break;

should be:

case "max length" : paramValues[i] = (length == int.MaxValue || length < 0) ? "max" : length?.ToString(NumberFormatInfo.InvariantInfo); break;

The strange thing is that this used to work fine... I'm unsure what changed to cause this problem. Perhaps a new version of linq2db, Microsoft.Data.SqlClient or SQL Server?

### Steps to reproduce

```sql
CREATE PROCEDURE [dbo].[spTestParm]
	@myParam NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 0;
END
GO
```

call GetSchema() on this DB.

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): SQL Server 16.0.1121.4 (2022)

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.2.2

Operating system: Windows 11

.NET Version: 8.0.8

### PR DESCRIPTION
**Pull request by cal-tlabwest**
SchemaProvider parsed max length of varchar(max) procedure parameters as "-1".
This fixes the problem for me but unsure if this causes problems in other cases...

Fixes #4631

### CODE REVIEW

**Comment by MaceWindu** [comment]
Thanks! I will check why it has `-1` value, but in general it looks good.

File: Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs [hunk 1]
```diff
@@ -627,7 +627,7 @@ protected virtual List<DataTypeInfo> GetDataTypes(DataConnection dataConnection)
 						{
 							case "size"       :
 							case "length"     : paramValues[i] = length; break;
-							case "max length" : paramValues[i] = length == int.MaxValue ? "max" : length?.ToString(NumberFormatInfo.InvariantInfo); break;
+							case "max length" : paramValues[i] = (length == int.MaxValue || length < 0) ? "max" : length?.ToString(NumberFormatInfo.InvariantInfo); break;
```
Comment (MaceWindu) [inline Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs:630]:
```suggestion
							// -1: https://learn.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/parameters-transact-sql
							case "max length" : paramValues[i] = length is int.MaxValue or -1 ? "max" : length?.ToString(NumberFormatInfo.InvariantInfo); break;
```

**Review by MaceWindu — DISMISSED** [review]

File: Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs (hunk 1 above)
Comment (MaceWindu) [reply Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs:630]: @cal-tlabwest could you please accept this change so we can merge it?
