### PR TITLE
Fix null nullable value conversion in mapper

### LINKED ISSUE #5236: Conversion operators failed for nullable type
Thank you so much for your work, but there was a small bug in the latest release.

### Description

Conversion operators failed for nullable type, when value is null.

```cs
[Table("SomeTable")]
public partial class SomeTable
{
  [Column("SomeColumn", DataType  = DataType.Int16)] public short? SomeColumn{ get; set; } 
}

public class SomeOldDto
{
  public byte? SomeColumn{ get; set; } 
}

var query = from t in db.GetTable<SomeTable>()
   select new SomeOldDto
   {
      SomeColumn = (byte?)t.SomeColumn
   }
```

On versions 6.0.0-rc.3 and earlier, this type conversion scheme worked.
The new version only works with Convert.ToByte()

### Exception details

System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at lambda_method329(Closure, IQueryRunner, DbDataReader)
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 579
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 600
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 600
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext() in /_/Source/LinqToDB/Internal/Linq/QueryRunner.cs:line 601
   at LinqToDB.Internal.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Impl|59_0[TSource](IAsyncEnumerable`1 source, TSource defaultValue, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Impl|59_0[TSource](IAsyncEnumerable`1 source, TSource defaultValue, CancellationToken cancellationToken)
   at LinqToDB.Internal.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass22_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext() in /_/Source/LinqToDB/Internal/Linq/Builder/FirstSingleBuilder.cs:line 230
--- End of stack trace from previous location ---
   at LinqToDB.Internal.Linq.ExpressionQuery`1.LinqToDB.Internal.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 112
   at LinqToDB.Internal.Linq.ExpressionQuery`1.LinqToDB.Internal.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 115

### Regression?

_No response_

### Linq To DB version

6.0.0

### .NET version

10

### Database

mssql, postgres

### Database provider

_No response_

### Operating system

windows, linux

### Configuration

_No response_

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #5236

### CODE REVIEW

File: Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs
Comment (viceroypenguin) [inline Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs:537]: take this opportunity to switch this method to `(Expression, bool)?` instead of `Tuple<>?`?

File: Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs [hunk 1]
```diff
@@ -493,32 +493,34 @@ orderby c.i
 			return null;
 		}
 
-		static Tuple<Expression,bool>? GetConverter(MappingSchema mappingSchema, Expression expr, Type from, Type to)
+		record struct Conversion(Expression Expression, bool IsLambda);
```
Comment (MaceWindu) [inline Source/LinqToDB/Internal/Conversion/ConvertBuilder.cs]: TODO: remove record as IsLambda not used and we can return only Expression
